### ISSUE TITLE
Trouble Deploying Express

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/capstone-project#196]
I have deployed, but I get a 500 when I visit my backend URL. My logs say

```
Starting process with command `npm start`
2016-06-09T19:40:10.360436+00:00 app[web.1]: > express-api-template@0.1.0 start /app
2016-06-09T19:40:10.360424+00:00 app[web.1]: 
2016-06-09T19:40:10.360442+00:00 app[web.1]: 
2016-06-09T19:40:10.360442+00:00 app[web.1]: > ./bin/express server
2016-06-09T19:40:11.171409+00:00 app[web.1]: module.js:341
2016-06-09T19:40:11.171419+00:00 app[web.1]:     throw err;
2016-06-09T19:40:11.171420+00:00 app[web.1]:     ^
2016-06-09T19:40:11.171420+00:00 app[web.1]: 
2016-06-09T19:40:11.171429+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/api.js:5:17)
2016-06-09T19:40:11.171428+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-06-09T19:40:11.171428+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-06-09T19:40:11.171425+00:00 app[web.1]: Error: Cannot find module 'request'
2016-06-09T19:40:11.171431+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-06-09T19:40:11.171429+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-06-09T19:40:11.171426+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-06-09T19:40:11.171432+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-06-09T19:40:11.171432+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-06-09T19:40:11.171433+00:00 app[web.1]:     at /app/lib/wiring/loader.js:13:39
2016-06-09T19:40:11.171430+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-06-09T19:40:11.171435+00:00 app[web.1]:     at fs.readdirSync.filter.entry.forEach (/app/lib/wiring/loader.js:12:5)
2016-06-09T19:40:11.171434+00:00 app[web.1]:     at Array.forEach (native)
```

Which leads be to believe the require for the request module is failing. It works find locally. Here is my code in that file:

```
'use strict';

const controller = require('lib/wiring/controller');
const models = require('app/models');
const request = require('request');
const eventfulKey = process.env.EVENTFUL_KEY;
const xml2json = require('xml2js').parseString

// http://api.eventful.com/rest/events/search?app_key=sXx2bDsZHXXqVNkZ&category=music&location=boston&keywords=chvrches

const eventful = (req, res, next) => {
  console.log(req.body, "request body");

  let url = `http://api.eventful.com/json/events/search?app_key=${eventfulKey}&category=music&page_size=25`;

  if(req.body.location){
    url += '&location=' + req.body.location;
  }
  if (req.body.keywords){
    let keywords = req.body.keywords.replace(/ /g,"+");
    console.log(keywords);
    url += '&keywords=' + keywords;
  }

  request(url, function(error, response, body) {
    if(error){
      console.log(error)
    }
    let dataToReturn = [];
    let singleEvent;
    let data = JSON.parse(response.body);
    console.log(data);
    if(data.total_items > 1) {
      data.events.event.forEach(function(concert){
        let parsedConcert = {
          'id': (concert.id ? concert.id : 'none'),
          'city_name': (concert.city_name ? concert.city_name : 'none'),
          'country_name': (concert.country_name ? concert.country_name : 'none'),
          'region_name': (concert.region_name ? concert.region_name : 'none'),
          'description': (concert.description ? concert.description : 'none'),
          'title': (concert.title ? concert.title : 'none'),
          'venue_url': (concert.venue_url ? concert.venue_url : 'none'),
          'venue_name': (concert.venue_name ? concert.venue_name : 'none'),
          'venue_address': (concert.venue_address ? concert.venue_address : 'none'),
          'start_time': (concert.start_time ? concert.start_time : 'none'),
          'url': (concert.url ? concert.url : 'none'),
          'image_url': (concert.image ? concert.image.thumb.url : 'none'),
          'performer': (concert.performers ? concert.performers.performer : 'none'),
        };
        dataToReturn.push(parsedConcert);
      });
    res.json( {'eventful_event': dataToReturn });
  }else if (data.total_items === '1') {
    let parsedConcert = {
      'id': (data.events.event.id ? data.events.event.id : 'none'),
      'city_name': (data.events.event.city_name ? data.events.event.city_name : 'none'),
      'country_name': (data.events.event.country_name ? data.events.event.country_name : 'none'),
      'region_name': (data.events.event.region_name ? data.events.event.region_name : 'none'),
      'description': (data.events.event.description ? data.events.event.description : 'none'),
      'title': (data.events.event.title ? data.events.event.title : 'none'),
      'venue_url': (data.events.event.venue_url ? data.events.event.venue_url : 'none'),
      'venue_name': (data.events.event.venue_name ? data.events.event.venue_name : 'none'),
      'venue_address': (data.events.event.venue_address ? data.events.event.venue_address : 'none'),
      'start_time': (data.events.event.start_time ? data.events.event.start_time : 'none'),
      'url': (data.events.event.url ? data.events.event.url : 'none'),
      'image_url': (data.events.event.image ? data.events.event.image.thumb.url : 'none'),
      'performer': (data.events.event.performers ? data.events.event.performers.performer : 'none'),
    };
    res.json( {'eventful_event': dataToReturn });
  }else {
    res.sendStatus(404);
  }
  });
};

```

Not sure what I'm doing wrong

**Comment by louarnos** [comment]
I did set the mongo URI and added the addon and I also set the key for my 3rd party API call and the my secret key. Havent dont the client URI because I'm waiting to deploy the front end.

**Comment by RDegnen** [comment]
did you save the request module to your package.json file?

**Comment by louarnos** [comment]
its built into express

**Comment by louarnos** [comment]
i think

**Comment by louarnos** [comment]
it looks like the package.json still has the express-api-template as the name. I thought I changed them all. Could this cause this issue? Everywhere else I changed the appname

**Comment by RDegnen** [comment]
just check if it's there and in your node_modules directory

**Comment by RDegnen** [comment]
wouldn't hurt to change the name

**Comment by louarnos** [comment]
its not there

**Comment by louarnos** [comment]
i did npm install --save

**Comment by RDegnen** [comment]
put it back in there

**Comment by louarnos** [comment]
yeah it still cant find the request module it seems

**Comment by RDegnen** [comment]
http://stackoverflow.com/questions/31214997/heroku-cannot-find-module 

try these

**Comment by gaand** [comment]
Did you run this command exactly?

``` sh
npm install --save request
```

then commit package.json and merge that into master?

**Comment by louarnos** [comment]
that did it. thank you guys
