### ISSUE TITLE
Error: Assertion Failed: You need to pass a model name to the store's modelFor method

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/capstone-project#218]
So I have information that I am rendering from a join table.  The information is now rendering correctly but only after I click on the link twice. The second time it renders the data, but I also get an error message each time as below:

```
ember.debug.js:32096 Error: Assertion Failed: You need to pass a model name to the store's modelFor method
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26707:21)
    at assert (http://localhost:4200/assets/vendor.js:16547:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:26471:34)
    at assert (http://localhost:4200/assets/vendor.js:71209:37)
    at Class.modelFor (http://localhost:4200/assets/vendor.js:80195:41)
    at Class._internalModelForId (http://localhost:4200/assets/vendor.js:79392:28)
    at deserializeRecordId (http://localhost:4200/assets/vendor.js:80697:18)
    at normalizeRelationship (http://localhost:4200/assets/vendor.js:80812:28)
    at http://localhost:4200/assets/vendor.js:80791:7onerrorDefault @ ember.debug.js:32096trigger @ ember.debug.js:54476(anonymous function) @ ember.debug.js:55727invoke @ ember.debug.js:333flush @ ember.debug.js:397flush @ ember.debug.js:205end @ ember.debug.js:560run @ ember.debug.js:682join @ ember.debug.js:702run.join @ ember.debug.js:21181hash.success @ rest.js:910fire @ jquery.js:3187fireWith @ jquery.js:3317done @ jquery.js:8757(anonymous function) @ jquery.js:9123
```

model hook:

```
model () {
    return this.get('store').findAll('library');
  }
```

libraries index returns all libraries for current_user.

library model:

```
export default DS.Model.extend({
  user_id: DS.attr('number'),
  game_id: DS.attr('number'),
  game: DS.belongsTo('game', {
    inverse: 'libraries'
  }),
  user: DS.belongsTo('user', {
    inverse: 'libraries'
  })
});
```

**Comment by jrhorn424** [comment]
What happens if you do this?

``` diff
export default DS.Model.extend({
-  user_id: DS.attr('number'),
-  game_id: DS.attr('number'),
  game: DS.belongsTo('game', {
    inverse: 'libraries'
  }),
  user: DS.belongsTo('user', {
    inverse: 'libraries'
  })
});
```

**Comment by lcurran** [comment]
same error:

```
ember.debug.js:32096 Error: Assertion Failed: You need to pass a model name to the store's modelFor method
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26707:21)
    at assert (http://localhost:4200/assets/vendor.js:16547:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:26471:34)
    at assert (http://localhost:4200/assets/vendor.js:71209:37)
    at Class.modelFor (http://localhost:4200/assets/vendor.js:80195:41)
    at Class._internalModelForId (http://localhost:4200/assets/vendor.js:79392:28)
    at deserializeRecordId (http://localhost:4200/assets/vendor.js:80697:18)
    at normalizeRelationship (http://localhost:4200/assets/vendor.js:80812:28)
    at http://localhost:4200/assets/vendor.js:80791:7
```

**Comment by lcurran** [comment]
Getting a different issue now after walking through setting up the relations for ember & API with Brian, so I'm closing this.

Solution was to go to the primary User table as the route instead of routing to the join table, and then retrieve data through the join table via custom methods in the API serializers.

**Comment by lcurran** [comment]
#219 Has the solution that I think was supposed to be here, reference @berziiii and @jrhorn424's comments on the bottom.
