### ISSUE TITLE
Error: Assertion Failed: The response to store.query is expected to be an array but it was a single record. Please wrap your response in an array or use `store.queryRecord` to query for a single record.

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/capstone-project#232]
I'm trying to query my api to get the results of a query to a third party api.  My api returns json but for some reason the query method is demanding an array.  I'm guessing its a serializer issue but don't know what about the serializer needs to be changed....

Full error:

```
ember.debug.js:32096 Error: Assertion Failed: The response to store.query is expected to be an array but it was a single record. Please wrap your response in an array or use `store.queryRecord` to query for a single record.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26707:21)
    at assert (http://localhost:4200/assets/vendor.js:16547:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:26471:34)
    at assert (http://localhost:4200/assets/vendor.js:71209:37)
    at http://localhost:4200/assets/vendor.js:81116:41
    at tryCatch (http://localhost:4200/assets/vendor.js:63932:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:63947:15)
    at publish (http://localhost:4200/assets/vendor.js:63915:9)
    at http://localhost:4200/assets/vendor.js:42180:7
```

**Comment by jrhorn424** [comment]
Are you using `findAll`? It expects an array with the adapters we have configured.

If you are using `findAll`, you can likely edit the controller action or serializer to get what you need.

**Comment by lcurran** [comment]
findAll rejects the query param though, so I am using query instead

```
this.get('store').query('catalog', { search: keyword })
```

**Comment by jrhorn424** [comment]
So do you understand `query` to be the plural of `queryRecord`? Are you trying to retrieve multiple records or a single record? If a single, I'd try doing `queryRecord`.

**Comment by lcurran** [comment]
Solution: 
Was passing an array of hashes like so: `[{},{}]`, needed to pass a hash with a key containing an array of hashes. Solution in code:

```
def result
    @result = {
      'catalogs' => []
    }
    @body.each_index do |i|
      hash = {}
      hash[:id] = @body[i]['id']
      hash[:name] = @body[i]['name']
      hash[:summary] = @body[i]['summary'] if @body[i]['summary']
      hash[:cover] = @body[i]['cover']['cloudinary_id'] if @body[i]['cover']
      hash[:video] = @body[i]['videos'][0]['video_id'] if @body[i]['videos']
      @result['catalogs'][i] = hash
    end
    return @result
  end
```
