### ISSUE TITLE
Having issue installing thredded Ruby Gem

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/capstone-project#251]
So I'm having the same issue we talked about recently.  I'm trying to install this Ruby Gem called thredded which is a forum engine.  I have gotten my rails-api-template served and working.  So that's when I start setting up the thredded Ruby Gem.  

I added the gem to my bundler as the thredded docs suggest and that works fine (https://github.com/thredded/thredded).  But when I get to the part where I have to add the thredded initializer to my "parent app" with this command: 

```
rails generate thredded:install
```

I've looked in my rails-api-template and nothing is being added to the initializers file.
It throws me this same error in my terminal talking about the bin/spring file:

```
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0", "/Users/joshuamitchell/.gem/ruby/2.3.0"]}) was passed in from bin/rails:3:in `load'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Engine::Configuration:0x007f83941fcc18> (NoMethodError)
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thredded-0.6.3/lib/thredded/engine.rb:27:in `block in <class:Engine>'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
    from /Users/joshuamitchell/wdi/tmp/rails-api-template-master/config/environment.rb:5:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:92:in `preload'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:143:in `serve'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

Here is what's in my bin/spring file:

``` rb
#!/usr/bin/env ruby

# This file loads spring without using Bundler, in order to be fast.
# It gets overwritten when you run the `spring binstub` command.

unless defined?(Spring)
  require 'rubygems'
  require 'bundler'

  if (match = Bundler.default_lockfile.read.match(/^GEM$.*?^    (?:  )*spring \((.*?)\)$.*?^$/m))
    Gem.paths = { 'GEM_PATH' => [Bundler.bundle_path.to_s, *Gem.path].uniq }
    gem 'spring', match[1]
    require 'spring/binstub'
  end
end
```

Now, I have updated my RubyGem to the current version 2.6.6.  We were using version 2.5.1  I'm not sure if that has anything to do with it or not. 

After googling I can across this issue on github: https://github.com/rubygems/rubygems/issues/1551#issuecomment-214263437
I've tried messing with the spring like suggested in this article but nothing has worked.  

I can't seem to figure out what is going on.  I would really like to get this to work.  If I can't figure it out by the end of the night I feel like I'm going to have scrap my idea because I don't want to spend too much time stuck on this and it's already been 2 days.  Any help would be much appreciated.

**Comment by jlmitch1989** [comment]
I tried this possible solution on http://stackoverflow.com/questions/37864054/rails-5-array-values-in-the-parameter-to-gem-paths-are-deprecated

```
bundle update spring
bundle exec spring binstub --remove --all
bundle exec spring binstub --all
```

Now I'm getting this error in terminal talking about a 'missing method':

```
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Engine::Configuration:0x007fc14cbc5a88> (NoMethodError)
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thredded-0.6.3/lib/thredded/engine.rb:27:in `block in <class:Engine>'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
    from /Users/joshuamitchell/wdi/tmp/rails-api-template-master/config/environment.rb:5:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:92:in `preload'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:143:in `serve'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

**Comment by gaand** [comment]
It's failing to configure `asseta`  This may be related to using rails as an api,  the `rails-api` gem, or other settings in the `rails-template`. 

Does threaded use rails views?

**Comment by jlmitch1989** [comment]
I think so.  I've decided that I am going to build a forum from scratch. This gem thing has been such an issue.  Plus, I think doing it from scratch will benefit me more. Thanks!
