### ISSUE TITLE
ember to rails user_id conversion issue

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/capstone-project#293]
I am attempting to create a new profile that belongs to the user upon sign up. It appears that when I pass the user id to the profile, it converts to a string somewhere along the way. I am calling the createProfile function in the sign-up/route.js as follows: 

```js
import Ember from 'ember';

export default Ember.Route.extend({
  auth: Ember.inject.service(),
  flashMessages: Ember.inject.service(),

  actions: {
    signUp (credentials) {
      this.get('auth').signUp(credentials)
      .then(() => this.get('auth').signIn(credentials))
      .then(() => this.transitionTo('application'))
      .then(() => this.get('auth').createProfile(credentials))
      .then(() => {
        this.get('flashMessages')
        .success('Successfully signed-up! You have also been signed-in.');
      })
      .catch(() => {
        this.get('flashMessages')
        .danger('There was a problem. Please try again.');
      });
    },
  },
});
```

the createProfile AJAX request lives in the auth/service.js file and looks like this:

```js
createProfile (credentials) {
    let new_id = parseInt(this.get('credentials.id'));
    let email = this.get('credentials.email');
    console.log(new_id);
    console.log(email);
    return this.get('ajax').post('/profiles', {
      data: {
        profile: {
          email: credentials.email,
          user_id: new_id
        },
      },
    })
    .then((result) => {
      this.get('profiles').set('id', result.profile.id);
      this.get('profiles').set('email', result.profile.email);
    });
  },
```
(I have tried both parsing as an integer and not, and get the same result)

My profile/model.js looks like this:

```js
import DS from 'ember-data';

export default DS.Model.extend({
  user_id: DS.attr('number'),
  email: DS.attr('string'),
  user: DS.belongsTo('user')
});
```

I am reaching the server and getting a 400 bad request with this error:
```
XMLHttpRequest cannot load http://localhost:3000/profiles. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:7165' is therefore not allowed access. The response had HTTP status code 400.
```

my rails server tells me that the user_id parameter is missing, even though I _think_ I am passing it. 

```
Started POST "/profiles" for ::1 at 2016-11-06 13:30:21 -0500
Processing by ProfilesController#create as HTML
  Parameters: {"profile"=>{"email"=>"ejigsg@nlsgm.com", "user_id"=>"31"}}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "f58772684edc97b849797942edb72191"]]
Completed 400 Bad Request in 6ms (ActiveRecord: 0.5ms)

ActionController::ParameterMissing (param is missing or the value is empty: user_id):
  app/controllers/profiles_controller.rb:60:in `profile_params'
  app/controllers/profiles_controller.rb:26:in `create'
```

My only thoughts are that I am not actually passing it at all like I think I am, or it is being passed but because it appears to be a string, it is not being inserted into the table. Thoughts?

**Comment by knoddin** [comment]
Nevermind, got it working. I was somehow making user_id required in my rails profiles controller and making profile optional, so it wasn't creating a new one. I switched them.

**Comment by jrhorn424** [comment]
Why are you doing this:

``` js
  user_id: DS.attr('number'),
```

instead of this?

``` js
  user: DS.belongsTo('user'),
```

**Comment by jrhorn424** [comment]
That's one of the big no-no's we covered in that list of no-no's during the `ember-resources` talk. I'm not saying you're wrong, but if you have a reason can you share it so I can learn from you?

**Comment by knoddin** [comment]
I do have it that way now :)
