### ISSUE TITLE
relation playlists already exists

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#308]
Migrated playlists table, and it wasn't what I wanted in terms of columns, etc. I thought that I'd taken the correct steps to remove it, but apparently not because when I try to add playlists again with the columns I do want, it tells me that the relation already exists. How do I give myself a clean slate, so to speak?

**Comment by berziiii** [comment]
What were the steps you took to remove the table? Please include everything you did from the first command to create the table to where you are now.

**Comment by julie1013** [comment]
```
rails g controller playlists --skip-template-engine
rake db:migrate
rails d controller playlist
rails g controller playlists --skip-template-engine
Running via Spring preloader in process 30581
    conflict  app/controllers/playlists_controller.rb
Overwrite /Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/app/controllers/playlists_controller.rb? (enter "h" for help) [Ynaqdh] 
force  app/controllers/playlists_controller.rb
```

`rails g model Playlist first_episode:string second_episode:string third_episode:string fourth_episode:string fifth_episode:string sixth_episode:string`

```
conflict    db/migrate/20161107232030_create_playlists.rb
Another migration is already named create_playlists: 
/Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/db/migrate/20161107230253_create_playlists.rb. Use --force to replace this migration or --skip to ignore conflicted file.
```

`````` --force```

-bash: --force: command not found

rails g model Playlist --force first_episode:string second_episode:string third_episode:string fourth_episode:string fifth_episode:string sixth_episode:string```

rake aborted!

```StandardError: An error has occurred, this and all later migrations canceled:
PG::DuplicateTable: ERROR:  relation "playlists" already exists
: CREATE TABLE "playlists" ("id" serial primary key, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL) 
/Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/db/migrate/20161107232115_create_playlists.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "playlists" already exists
: CREATE TABLE "playlists" ("id" serial primary key, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL) 
/Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/db/migrate/20161107232115_create_playlists.rb:3:in `change'
PG::DuplicateTable: ERROR:  relation "playlists" already exists
/Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/db/migrate/20161107232115_create_playlists.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
``````

```
rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
== 20161107232115 CreatePlaylists: migrating ==================================
-- create_table(:playlists)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
```

`rake db:migrate`

`rake aborted!`

```
StandardError: An error has occurred, this and all later migrations canceled:
PG::DuplicateTable: ERROR:  relation "playlists" already exists
```

`drop_table :playlists`

`-bash: drop_table: command not found`

`drop_table :playlists`

`rails destroy model playlists`

```
Running via Spring preloader in process 31663
[WARNING] The model name 'playlists' was recognized as a plural, using the singular 'playlist' instead. Override with --force-plural or setup custom inflection rules for this noun before running the generator.
```

```
rails d controller playlists
Running via Spring preloader in process 31720
remove  app/controllers/playlists_controller.rb
```

`rails g controller playlists --skip-template-engine`

```
rails g model Playlist --force first_episode:string second_episode:string third_episode:string fourth_episode:string fifth_episode:string sixth_episode:string
```

`rake db:migrate`

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
PG::DuplicateTable: ERROR:  relation "playlists" already exists
```

```
drop_table :playlists
-bash: drop_table: command not found
drop_table(playlists)
-bash: syntax error near unexpected token `playlists'
```

`rails c` 

(Yes, I was shooting in the dark here)

``````
drop_table :playlists
NoMethodError: undefined method `drop_table' for main:Object```
rails generate migration add_second_episode_to_playlists second_episode:string``
I was trying to just add columns instead at this point.

rake db:migrate

rake aborted!

StandardError: An error has occurred, this and all later migrations canceled:
PG::DuplicateTable: ERROR:  relation "playlists" already exists```

```rails d migration playlists
Illegal name for migration file: create_playlists.rb
(only lower case letters, numbers, and '_' allowed)```
``````

**Comment by berziiii** [comment]
I can't do anything with this. Please tell me what I'm looking at. I don't need the output, just the commands you ran and the error. Please clean this up.

**Comment by julie1013** [comment]
Sorry about that. I've just edited it.

**Comment by jrhorn424** [comment]
Please do the following in one line, and regardless of the output, post it here before trying anything else: `bin/rake db:drop db:create db:migrate db:seed db:examples`

**Comment by julie1013** [comment]
```
Running via Spring preloader in process 42838
PG::ObjectInUse: ERROR:  database "rails-api-template_development" is being accessed by other users
DETAIL:  There are 5 other sessions using the database.
: DROP DATABASE IF EXISTS "rails-api-template_development"
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:86:in `drop_database'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/postgresql_database_tasks.rb:28:in `drop'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:114:in `drop'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:128:in `block in drop_current'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:127:in `drop_current'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:28:in `block (2 levels) in <top (required)>'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/bin/rake:9:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Couldn't drop rails-api-template_development
rails-api-template_development already exists
== 20161107233025 CreatePlaylists: migrating ==================================
-- create_table(:playlists)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "playlists" already exists
: CREATE TABLE "playlists" ("id" serial primary key, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL) 
/Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/db/migrate/20161107233025_create_playlists.rb:3:in `change'
-e:1:in `<main>'
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "playlists" already exists
: CREATE TABLE "playlists" ("id" serial primary key, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL) 
/Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/db/migrate/20161107233025_create_playlists.rb:3:in `change'
-e:1:in `<main>'
PG::DuplicateTable: ERROR:  relation "playlists" already exists
/Users/julieesris/WDI_Fall_2016/projects/simpsons-and-chill/simpsons-and-chill-api/db/migrate/20161107233025_create_playlists.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jrhorn424** [comment]
Do this and post the output:
1. Quit all open connections to the database: rails servers, rails consoles, and rails db consoles, or psql clients.
2. `bin/spring stop`
3. `bin/rake db:drop db:create db:migrate db:seed db:examples`

**Comment by julie1013** [comment]
```
Running via Spring preloader in process 43091
== 20150724141255 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0461s
== 20150724141255 CreateUsers: migrated (0.0462s) =============================

== 20160327214720 CreateExamples: migrating ===================================
-- create_table(:examples)
   -> 0.0801s
== 20160327214720 CreateExamples: migrated (0.0804s) ==========================

== 20161107200340 CreateEpisodes: migrating ===================================
-- create_table(:episodes)
   -> 0.0204s
== 20161107200340 CreateEpisodes: migrated (0.0205s) ==========================

== 20161107233025 CreatePlaylists: migrating ==================================
-- create_table(:playlists)
   -> 0.0111s
== 20161107233025 CreatePlaylists: migrated (0.0112s) =========================

== 20161107233953 AddSecondEpisodeToPlaylists: migrating ======================
-- add_column(:playlists, :second_episode, :string)
   -> 0.0081s
== 20161107233953 AddSecondEpisodeToPlaylists: migrated (0.0082s) =============
```

**Comment by jrhorn424** [comment]
Looks like it worked.

**Comment by julie1013** [comment]
Awesome, thanks!
