### ISSUE TITLE
this.findAll(...) is not a function

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#320]
There seem to be relationship issues on my front end. For example, if I go to the localhost ```/episodes``` or ```/users```, I get this message:

```
ember.debug.js:30291 Error while processing route: episodes this.get(...).findAll is not a function TypeError: this.get(...).findAll is not a function
    at Class.model (http://localhost:7165/assets/ga-wdi-boston.ember-auth.js:1781:32)
    at Class.deserialize (http://localhost:7165/assets/vendor.js:39077:19)
    at Object.applyHook (http://localhost:7165/assets/vendor.js:61190:30)
    at C.runSharedModelHook (http://localhost:7165/assets/vendor.js:59175:33)
    at C.getModel (http://localhost:7165/assets/vendor.js:59406:19)
    at http://localhost:7165/assets/vendor.js:61043:17
    at tryCatch (http://localhost:7165/assets/vendor.js:61487:14)
    at invokeCallback (http://localhost:7165/assets/vendor.js:61502:15)
    at publish (http://localhost:7165/assets/vendor.js:61470:9)
    at http://localhost:7165/assets/vendor.js:50950:16
```

and

```
ember.debug.js:19160 TypeError: this.get(...).findAll is not a function
    at Class.model (route.js:4)
    at Class.deserialize (ember.debug.js:28544)
    at Object.applyHook (ember.debug.js:50657)
    at C.runSharedModelHook (ember.debug.js:48642)
    at C.getModel (ember.debug.js:48873)
    at ember.debug.js:50510
    at tryCatch (ember.debug.js:50954)
    at invokeCallback (ember.debug.js:50969)
    at publish (ember.debug.js:50937)
    at ember.debug.js:40417
```

For example, the code in the episodes route:

```js
export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('episode');
  }
});
```

Brian has tried to help me, but both of us are stumped as to why this is happening.

**Comment by jrhorn424** [comment]
> ```
> at Class.model (http://localhost:7165/assets/ga-wdi-boston.ember-auth.js:1781:32)
> ```

Replace all instances of `ga-wdi-boston.ember-auth` with an app name. @berziiii Can walk you through the instructions. You've missed something in Ember template installation.

After that:
1.  cancel your server
2. delete the `bower_components` and `node_modules` directory
3.  run `npm install`
4. run `bower install`
5. run `ember build` (it should succeed)
6. then restart your server with `ember server`

Are there any differences in your error messages?

**Comment by jrhorn424** [comment]
If that doesn't work, @berziiii ensure there are no filename spelling errors.

**Comment by julie1013** [comment]
Thanks, but it turns out the issue was the way it was structured.

I went through the Codeschool Ember tutorial over the weekend because I thought it would help me get a grasp on things. I guess what it ended up doing then was having me create things (namely `store` and `service`), which I shouldn't have.
