### ISSUE TITLE
[Heroku] PG::DuplicateTable: ERROR:

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/capstone-project#344]
I'm having issues when I try to seed my database. I get the following error when I `db:migrate` or `db:seed`

```
PG::DuplicateTable: ERROR:  relation "photos" already exists
: CREATE TABLE "photos" ("id" serial primary key, "spot_id" integer, "upload_id" integer, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL) 
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:222:in `create_table'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/app/db/migrate/20161108204541_create_photos.rb:3:in `change'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:608:in `exec_migration'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
.....
```

I tried following the steps in[ issue 308 ](https://github.com/ga-wdi-boston/capstone-project/issues/308) but then get the following errors 
```
rake aborted!
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on table "spots" violates foreign key constraint "fk_rails_f05e659f8c"
DETAIL:  Key (user_id)=(1) is not present in table "users".
: INSERT INTO "spots" ("name", "address", "city", "state", "zip", "description", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"
/Users/ktab/wdi/projects/photo-app-api/db/seeds.rb:10:in `<top (required)>'
-e:1:in `<main>'
PG::ForeignKeyViolation: ERROR:  insert or update on table "spots" violates foreign key constraint "fk_rails_f05e659f8c"
DETAIL:  Key (user_id)=(1) is not present in table "users".
/Users/ktab/wdi/projects/photo-app-api/db/seeds.rb:10:in `<top (required)>'
-e:1:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
~/wdi/projects/photo-app-api (master)$ bundle exec rails s
=> Booting WEBrick
=> Rails 4.2.7.1 application starting in development on http://localhost:4741
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2016-11-10 14:02:27] INFO  WEBrick 1.3.1
[2016-11-10 14:02:27] INFO  ruby 2.3.1 (2016-04-26) [x86_64-darwin15]
[2016-11-10 14:02:27] INFO  WEBrick::HTTPServer#start: pid=36504 port=4741
```

**Comment by jrhorn424** [comment]
@styletabtech Let's get this resolved ASAP.

**Comment by styletabtech** [comment]
Solution: 

Needed to reset my database by running `heroku pg:reset DATABASE` which will prompted me to put in the name of your database to proceed:

```
~/wdi/projects/photo-app-api (master)$ heroku pg:reset DATABASE

 !    WARNING: Destructive Action
 !    This command will affect the app: snapshot-app
 !    To proceed, type "snapshot-app" or re-run this command with --confirm snapshot-app

> snapshot-app
```

Then I needed to update my seed data to include user dataa along with my spots data (which has user_id in the schema) to remedy the `InvalidForeignKey` error. 

Then followed heroku deployment steps to migrate and seed database.
