### ISSUE TITLE
POST to server mysterious 500 error

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/capstone-project#369]
As far as I can tell, everything happens as it's supposed to, except I get this strange 500 error. I know that all the correct data is making it to the serve and that the server has no problem dealing with it thanks to console logs on the server, but I cannot deduce where it is failing.

**Comment by treep78** [comment]
That issue turned out to be that I was requiring data I was not sending, but it only worked once and now all subsequent posts get a 404.

**Comment by treep78** [comment]
Ok, so it turns out that if you stay on that same page and attempt to create another one, it attempts to edit the one you just created, the question is now, why can't you edit it. I will investigate further.

**Comment by treep78** [comment]
So the app tries to get to a page, but returns a 404, however I can go to that page in the browser so it clearly does exists.

**Comment by treep78** [comment]
So I did some poking and found that the 404 is somehow cause by authentication on update, if update has no authentication there is no problem. The odd part about this is that I am performing the update with the same user that created the record in the first place.

**Comment by raq929** [comment]
I would like you to post your controller code and your curl request so that we can help you debug.

**Comment by treep78** [comment]
Controller
```
'use strict';

const controller = require('lib/wiring/controller');
const models = require('app/models');
const Portfolio_images = models.portfolio_image;

const authenticate = require('./concerns/authenticate');
const setUser = require('./concerns/set-current-user');
const setModel = require('./concerns/set-mongoose-model');

const index = (req, res, next) => {
  Portfolio_images.find()
    .then(portfolio_images => res.json({
      portfolio_images: portfolio_images.map((e) =>
        e.toJSON({ virtuals: true, user: req.user })),
    }))
    .catch(next);
};

const show = (req, res) => {
  res.json({
    portfolio_image: req.portfolio_image.toJSON({ virtuals: true, user: req.user }),
  });
};

const create = (req, res, next) => {
  let portfolio_image = Object.assign(req.body.portfolio_image, {
    _owner: req.user._id,
  });
  Portfolio_images.create(portfolio_image)
    .then(portfolio_image =>
      res.status(201)
        .json({
          portfolio_image: portfolio_image.toJSON({ virtuals: true, user: req.user }),
        }))
    .catch(next);
    console.log("Making", req.body);
};

const update = (req, res, next) => {
  //delete req.body._owner;  // disallow owner reassignment.
  console.log('req: ',req.portfolio_image, 'req.body: ', req.body.portfolio_image);
  req.portfolio_image.update(req.body.portfolio_image)
    .then(() => res.sendStatus(204))
    .catch(next);
};

const destroy = (req, res, next) => {
  req.portfolio_image.remove()
    .then(() => res.sendStatus(204))
    .catch(next);
};

module.exports = controller({
  index,
  show,
  create,
  update,
  destroy,
}, { before: [
  { method: setUser, only: ['index', 'show'] },
  { method: authenticate, except: ['index', 'show', 'update'] },
  { method: setModel(Portfolio_images), only: ['show'] },
  { method: setModel(Portfolio_images, { forUser: true }), only: ['update', 'destroy'] },
], });

```

Here is the curl, though the results are the same when using the front-end ember:
```
API="http://localhost:4741"
URL_PATH="/portfolio_images"
TITLE="new title2"
ID="587921e9e6f07968e3174433"

curl "${API}${URL_PATH}/${ID}" \
  --include \
  --request PUT \
  --header "Content-Type: application/json" \
  --data '{
    "portfolio_image": {
      "title": "'"${TITLE}"'"
    }
  }'
```

**Comment by gaand** [comment]
You are not passing a token

**Comment by treep78** [comment]
No toke gave 401: correct, with valid token it gave the usual 404: incorrect

**Comment by treep78** [comment]
Full Error:
```
:4741/portfolio_images/58793bd9cb8bbe0b648b79f3:1 PUT http://localhost:4741/portfolio_images/58793bd9cb8bbe0b648b79f3 404 (Not Found)
2017-01-13 15:43:09.699 jquery.js:9536 XHR finished loading: PUT "http://localhost:4741/portfolio_images/58793bd9cb8bbe0b648b79f3".
send @ jquery.js:9536
ajax @ jquery.js:9143
_ajaxRequest @ rest.js:976
(anonymous) @ rest.js:966
initializePromise @ ember.debug.js:58213
Promise @ ember.debug.js:58698
ajax @ rest.js:949
updateRecord @ rest.js:723
_commit @ store.js:2335
(anonymous) @ store.js:1603
flushPendingSave @ store.js:1586
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
run @ ember.debug.js:21514
handler @ ember.debug.js:11103
(anonymous) @ ember.debug.js:41005
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-01-13 15:43:09.705 ember.debug.js:16905 Ember Data Request PUT http://localhost:4741/portfolio_images/58793bd9cb8bbe0b648b79f3 returned a 404
Payload (application/json; charset=utf-8)
[object Object]
Error
    at AdapterError (http://localhost:7165/assets/vendor.js:88320:16)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:89952:14)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:73484:28)
    at Class.superWrapper [as handleResponse] (http://localhost:7165/assets/vendor.js:50189:22)
    at ajaxError (http://localhost:7165/assets/vendor.js:90450:25)
    at Class.hash.error (http://localhost:7165/assets/vendor.js:90024:23)
    at fire (http://localhost:7165/assets/vendor.js:3637:31)
    at Object.fireWith [as rejectWith] (http://localhost:7165/assets/vendor.js:3767:7)
    at done (http://localhost:7165/assets/vendor.js:9576:14)
    at XMLHttpRequest.<anonymous> (http://localhost:7165/assets/vendor.js:9816:9)
defaultDispatch @ ember.debug.js:16905
dispatchError @ ember.debug.js:16888
onerrorDefault @ ember.debug.js:30389
trigger @ ember.debug.js:57833
(anonymous) @ ember.debug.js:58717
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
join @ ember.debug.js:746
run.join @ ember.debug.js:21556
hash.error @ rest.js:963
fire @ jquery.js:3305
fireWith @ jquery.js:3435
done @ jquery.js:9244
(anonymous) @ jquery.js:9484
```

**Comment by treep78** [comment]
Curl request and error:
```
~/wdi/trainings/ember-resources (training)$ curl "${API}${URL_PATH}/${ID}" \
>   --include \
>   --request PUT \
>   --header "Content-Type: application/json" \
>   --header "Authorization: Token token=${TOKEN}" \
>   --data '{
>     "portfolio_image": {
>       "title": "'"${TITLE}"'"
>     }
>   }'
HTTP/1.1 404 Not Found
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:7165
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 105
ETag: W/"69-CDsn6FBubDtxEgH4Qqf7dQ"
Date: Fri, 13 Jan 2017 20:38:13 GMT
Connection: keep-alive

{"error":{"message":"404 Not Found","error":{"name":"HttpError","status":404,"message":"404 Not Found"}}}~/wdi/trainings/ember-resources (training)$ 
```

**Comment by treep78** [comment]
url data from curl
```
API="http://localhost:4741"
URL_PATH="/portfolio_images"
ID="58793a6fcb8bbe0b648b79f2"

${API}${URL_PATH}/${ID}
```

routes from backend:
```
'use strict';

module.exports = require('lib/wiring/routes')

// create routes

// what to run for `GET /`
.root('root#root')

// standards RESTful routes
//.resources('examples')
.resources('portfolio_images')

// users of the app have special requirements
.post('/sign-up', 'users#signup')
.post('/sign-in', 'users#signin')
.delete('/sign-out/:id', 'users#signout')
.patch('/change-password/:id', 'users#changepw')
.resources('users', { only: ['index', 'show'] })

// all routes created
;
```

**Comment by treep78** [comment]
SOLUTION: Current version of express-api-template example controllers require objects to have an owner.
ALTERNATIVELY: Remove { forUser: true }) from controllers based on example controller.

**Comment by raq929** [comment]
Express-api-template does not require objects to have a user. The solution to the problem was:
```diff
-   { method: setModel(Portfolio_images, { forUser: true }), only: ['update', 'destroy'] }
+   { method: setModel(Portfolio_images,  only: ['update', 'destroy'] }
```

**Comment by treep78** [comment]
The Example Controller does require it. So any controller based on that example will.

**Comment by gaand** [comment]
You must have good reasons to allow updates to data that isn't owned.

**Comment by treep78** [comment]
True, that's why the solution chose to implement was to add ownership back into the model for Portfolio_images.

**Comment by raq929** [comment]
Please close the issue if it is resolved.
