### ISSUE TITLE
Curl Request for POST (Create) in Rails not Working

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/capstone-project#370]
I've been trying to debug this for a couple hours now. I cannot get the POST curl request to work to create a new product. I've looked at some closed issues (mainly, https://github.com/ga-wdi-boston/capstone-project/issues/353). 

The error from the server is:
```js
Started POST "/products" for ::1 at 2017-01-13 13:14:32 -0500
Processing by ProductsController#create as */*
  Parameters: {"product"=>{"description"=>"living room table sanded and painted", "price"=>250}}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `products' for nil:NilClass):
  app/controllers/products_controller.rb:16:in `create'
```

PRODUCTS CONTROLLER:
```js
class ProductsController < ApplicationController
  before_action :set_product, only: [:update, :destroy]

  def index
    @products = Product.all

    render json: @products
  end

  def show
    render json: Product.find(params[:id])
  end

  #  # POST /products
  def create
    @product = current_user.products.build(product_params)

    if @product.save
      render json: @product, status: :created
    else
      render json: @product.errors, status: :unprocessable_entity
    end
  end

  def update
    @product = current_user.products.find(params[:id])

    if @product.update(product_params)
      head :no_content
    else
      render json: @product.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    head :no_content
  end

  def set_product
    @product = current_user.products.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:before_photo_url, :description, :price,
                                    :after_photo_url)
  end

  private :set_product, :product_params
end
```

PRODUCT MODEL:
```js
# frozen_string_literal: true
class Product < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end
```

ROUTES FILE:
```js
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
  get '/products' => 'products#index'
  post '/products' => 'products#create'
  get '/products/:id' => 'products#show'
  patch '/products/:id' => 'products#update'
  delete '/products/:id', to: 'products#destroy'
end
```

PRODUCTS MIGRATION:
```js
class CreateProducts < ActiveRecord::Migration
  def change
    create_table :products do |t|
      t.string :before_photo_url
      t.string :description
      t.integer :price
      t.string :after_photo_url

      t.timestamps null: false
    end
  end
end
```

USER MODEL:
```js
# frozen_string_literal: true
class User < ActiveRecord::Base
  include Authentication
  has_many :products
end
```
CURL REQUEST SCRIPT:
```js
API="http://localhost:4741"
URL_PATH="/products"
TOKEN="BAhJIiU1NDBkMTdkZDBjNzVkZmRmMWM5ZTcyNTgwNzc1MjkwYgY6BkVG--c05432a1126d1d3f474a5d843117c221e653bd79"


curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "product": {
      "description": "living room table sanded and painted",
      "price": 250
    }
  }'

echo
```

I tried changing the Products Controller based on issue #353 . That returned basically the same error:
```js
NoMethodError (undefined method `Product' for nil:NilClass):
  app/controllers/products_controller.rb:16:in `create'
```
WHAT I TRIED CHANGING PRODUCTS CONTROLLER def create to:
```js
  def create
    @product = current_user.Product.new(product_params)

  if @product.save
      render json: @product, status: :created
    else
      render json: @product.errors, status: :unprocessable_entity
    end
  end
``` 

Any idea why the curl request is not working?

**Comment by jdaly04** [comment]
Fixed! In the error message,  "nil:NilClass", was referring to current_user. When I created my tables,  I did not add a foreign key to my 'products' table. I had to run the command:

```js
rails g migration AddUserToProducts user:references 
```

I then migrated that change, which added user_id as a foreign key on the products table. Now, my curl request is working!
