### ISSUE TITLE
500 internal error on sign up

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/capstone-project#372]
So, I've deployed both my backend and front end.  Rails/heroku for back and Ember Auth for the front.  Both are visible on deployed sites.  My sign up works correctly on my localhost, but not on deployed.  I am getting a 500 internal error on sign up.  Not sure where to go from here as the error doesn't exactly say too much.  I have gone over the guides again to double check the steps but I don't see anything that stands out.  I am assuming that it has something to do with the production environments settings, but again, not seeing what's wrong.  

``` 
if (environment === 'production') {
    ENV.rootURL = '/designmonster';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://vast-taiga-61428.herokuapp.com';
  }

  return ENV;
};
``` 
```
module.exports = function (environment) {
  'use strict';
  const ENV = {
    modulePrefix: 'designmonster',
    environment: environment,
    rootURL: '/',
    locationType: 'auto',
    apiHost: 'http://localhost:7165/',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false,
      },
    },
```
```

**Comment by RpRoderick** [comment]
Is this the problem, just noticed this:

Database url is set to aws.  I didn't set it this time.  Why is it set to this?  And what do I set it to this time around?

```
CLIENT_ORIGIN:            https://rproderick.github.io
DATABASE_URL:             numbers and letters
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          numbers and letters here
SECRET_TOKEN:      numbers and letters here
```

**Comment by RpRoderick** [comment]
Hmm.  I don't think that's it.  That's the database that heroku set on create.  I didn't realize heroku used aws, but it appears they do.

**Comment by raq929** [comment]
Your apihost is still localhost, not your backend server. Check the ember-deployment-guide for instructions on making the production ENV.

**Comment by RpRoderick** [comment]
Hmm, the only difference that I see is the line:   apiHost: 'http://localhost:3000/',   which I had replaced with :  apiHost: 'http://localhost:7165/',  because I thought that 3000 was just a placeholder? Generally when that's been in our class lessons we've replaced that with 7165 (or am I getting that mixed up with 4741?)  Either way, those would be for localHost.  Do you mean that I should have left it at 3000?  Wouldn't that all be local?

**Comment by RpRoderick** [comment]
Hmm, I'm still not entirely sure what you mean.  I replaced 3000, everything else looks like it does on the deploy guide, I believe.  I should have specified that my error does say:

POST https://vast-taiga-61428.herokuapp.com/sign-up 500 (Internal server error)

So...it's pointing at the right place?

**Comment by RpRoderick** [comment]
https://rproderick.github.io/designmonster/

if it's easier to see the error that comes up.

**Comment by gaand** [comment]
Please run `heroku logs` in you local api and post the result.

**Comment by gaand** [comment]
@RpRoderick Also, please edit your comment above and remove `DATABASE_URL`.  This info is also secret.

**Comment by RpRoderick** [comment]
```
2017-01-13T21:09:32.423264+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2017-01-13T21:09:32.423265+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"users"'::regclass
2017-01-13T21:09:32.423266+00:00 app[web.1]:                                           ^
2017-01-13T21:09:32.423267+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2017-01-13T21:09:32.423268+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2017-01-13T21:09:32.423268+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2017-01-13T21:09:32.423269+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2017-01-13T21:09:32.423270+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2017-01-13T21:09:32.423270+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2017-01-13T21:09:32.423271+00:00 app[web.1]:                ORDER BY a.attnum
2017-01-13T21:09:32.423272+00:00 app[web.1]: ):
2017-01-13T21:09:32.423272+00:00 app[web.1]:   app/controllers/users_controller.rb:7:in `signup'
2017-01-13T21:09:32.423273+00:00 app[web.1]: 
2017-01-13T21:09:32.423273+00:00 app[web.1]: 
2017-01-13T21:10:13.043970+00:00 heroku[router]: at=info method=POST path="/sign-up" host=vast-taiga-61428.herokuapp.com request_id=a820effd-136b-4e89-b0a9-95925ef6d1cb fwd="144.121.82.194" dyno=web.1 connect=1ms service=10ms status=500 bytes=579
2017-01-13T21:10:13.058730+00:00 app[web.1]: Started POST "/sign-up" for 144.121.82.194 at 2017-01-13 21:10:13 +0000
2017-01-13T21:10:13.061068+00:00 app[web.1]: Processing by UsersController#signup as HTML
2017-01-13T21:10:13.061119+00:00 app[web.1]:   Parameters: {"credentials"=>{"email"=>"ryantest@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
2017-01-13T21:10:13.063360+00:00 app[web.1]: Completed 500 Internal Server Error in 2ms (ActiveRecord: 1.6ms)
2017-01-13T21:10:13.064280+00:00 app[web.1]: 
2017-01-13T21:10:13.064281+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2017-01-13T21:10:13.064282+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"users"'::regclass
2017-01-13T21:10:13.064283+00:00 app[web.1]:                                           ^
2017-01-13T21:10:13.064283+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2017-01-13T21:10:13.064284+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2017-01-13T21:10:13.064284+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2017-01-13T21:10:13.064285+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2017-01-13T21:10:13.064285+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2017-01-13T21:10:13.064286+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2017-01-13T21:10:13.064286+00:00 app[web.1]:                ORDER BY a.attnum
2017-01-13T21:10:13.064287+00:00 app[web.1]: ):
2017-01-13T21:10:13.064287+00:00 app[web.1]:   app/controllers/users_controller.rb:7:in `signup'
2017-01-13T21:10:13.064287+00:00 app[web.1]: 
2017-01-13T21:10:13.064288+00:00 app[web.1]: 
2017-01-13T21:13:47.201909+00:00 heroku[router]: at=info method=GET path="/sign-up" host=vast-taiga-61428.herokuapp.com request_id=88502d63-e76c-4a24-b2bc-3289edeffb4b fwd="54.165.241.61" dyno=web.1 connect=0ms service=6ms status=404 bytes=1843
2017-01-13T21:13:47.219702+00:00 app[web.1]: Started GET "/sign-up" for 54.165.241.61 at 2017-01-13 21:13:47 +0000
2017-01-13T21:13:47.221550+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2017-01-13T21:13:47.221546+00:00 app[web.1]: 
2017-01-13T21:13:47.221548+00:00 app[web.1]: ActionController::RoutingError (No route matches [GET] "/sign-up"):
2017-01-13T21:13:47.221552+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
2017-01-13T21:13:47.221557+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2017-01-13T21:13:47.221549+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
2017-01-13T21:13:47.221553+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
2017-01-13T21:13:47.221554+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2017-01-13T21:13:47.221557+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2017-01-13T21:13:47.221556+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
2017-01-13T21:13:47.221558+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2017-01-13T21:13:47.221559+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
2017-01-13T21:13:47.221560+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
2017-01-13T21:13:47.221555+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-01-13T21:13:47.221556+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
2017-01-13T21:13:47.221560+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
2017-01-13T21:13:47.221561+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
2017-01-13T21:13:47.221561+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
2017-01-13T21:13:47.221563+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
2017-01-13T21:13:47.221562+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
2017-01-13T21:13:47.221563+00:00 app[web.1]:   vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
2017-01-13T21:13:47.221564+00:00 app[web.1]:   vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
2017-01-13T21:13:47.221565+00:00 app[web.1]:   vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
2017-01-13T21:13:47.221566+00:00 app[web.1]: 
2017-01-13T21:13:47.221566+00:00 app[web.1]: 
2017-01-13T21:15:39.564667+00:00 app[web.1]: Processing by UsersController#signup as HTML
2017-01-13T21:15:39.562057+00:00 app[web.1]: Started POST "/sign-up" for 144.121.82.194 at 2017-01-13 21:15:39 +0000
2017-01-13T21:15:39.568253+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2017-01-13T21:15:39.564719+00:00 app[web.1]:   Parameters: {"credentials"=>{"email"=>"abc@123.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
2017-01-13T21:15:39.568254+00:00 app[web.1]:                                           ^
2017-01-13T21:15:39.568249+00:00 app[web.1]: 
2017-01-13T21:15:39.567313+00:00 app[web.1]: Completed 500 Internal Server Error in 2ms (ActiveRecord: 1.8ms)
2017-01-13T21:15:39.568256+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2017-01-13T21:15:39.568255+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2017-01-13T21:15:39.568253+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"users"'::regclass
2017-01-13T21:15:39.568255+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2017-01-13T21:15:39.568256+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2017-01-13T21:15:39.568257+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2017-01-13T21:15:39.568256+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2017-01-13T21:15:39.568258+00:00 app[web.1]: ):
2017-01-13T21:15:39.568257+00:00 app[web.1]:                ORDER BY a.attnum
2017-01-13T21:15:39.568258+00:00 app[web.1]:   app/controllers/users_controller.rb:7:in `signup'
2017-01-13T21:15:39.568259+00:00 app[web.1]: 
2017-01-13T21:15:39.568259+00:00 app[web.1]: 
2017-01-13T21:15:39.552189+00:00 heroku[router]: at=info method=POST path="/sign-up" host=vast-taiga-61428.herokuapp.com request_id=8ebe5ece-ab5f-4cf4-9915-d50ca063abc5 fwd="144.121.82.194" dyno=web.1 connect=1ms service=12ms status=500 bytes=579
2017-01-13T21:16:13.385677+00:00 heroku[router]: at=info method=POST path="/sign-up" host=vast-taiga-61428.herokuapp.com request_id=f65ae130-e5e4-4128-aec5-1cf5661c5e6f fwd="144.121.82.194" dyno=web.1 connect=1ms service=8ms status=500 bytes=579
2017-01-13T21:16:13.401964+00:00 app[web.1]: Started POST "/sign-up" for 144.121.82.194 at 2017-01-13 21:16:13 +0000
2017-01-13T21:16:13.403894+00:00 app[web.1]: Processing by UsersController#signup as HTML
2017-01-13T21:16:13.403923+00:00 app[web.1]:   Parameters: {"credentials"=>{"email"=>"bob", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
2017-01-13T21:16:13.405844+00:00 app[web.1]: Completed 500 Internal Server Error in 2ms (ActiveRecord: 1.4ms)
2017-01-13T21:16:13.406456+00:00 app[web.1]: 
2017-01-13T21:16:13.406459+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2017-01-13T21:16:13.406460+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"users"'::regclass
2017-01-13T21:16:13.406460+00:00 app[web.1]:                                           ^
2017-01-13T21:16:13.406461+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2017-01-13T21:16:13.406462+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2017-01-13T21:16:13.406463+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2017-01-13T21:16:13.406463+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2017-01-13T21:16:13.406464+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2017-01-13T21:16:13.406464+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2017-01-13T21:16:13.406465+00:00 app[web.1]:                ORDER BY a.attnum
2017-01-13T21:16:13.406465+00:00 app[web.1]: ):
2017-01-13T21:16:13.406466+00:00 app[web.1]:   app/controllers/users_controller.rb:7:in `signup'
2017-01-13T21:16:13.406467+00:00 app[web.1]: 
2017-01-13T21:16:13.406467+00:00 app[web.1]: 
```

**Comment by RpRoderick** [comment]
Yup.  I see that it says relation 'users' does not exist. And I know exactly why.

**Comment by RpRoderick** [comment]
So, I never ran heroku run rake db:migrate.

**Comment by RpRoderick** [comment]
I simply forgot this step, which is kind of important.  It's been a little while since I used heroku and rails and I missed this key step.  In retrospect, I should have absolutely looked at heroku logs from the start.  But, problem solved.  Sign Up works just fine.  My front end was looking for a backend table that hadn't been created yet.  Thank you for pointing me in the right direction.

**Comment by raq929** [comment]
Please close!
