### ISSUE TITLE
Attempting to model relationships after lists/items and having issues...

### ISSUE THREAD

**Issue by ielole** [ga-wdi-boston/capstone-project#375]
Inside the listr-api item_serializer there is this code:
```rb

class ItemSerializer < ActiveModel::Serializer
  attributes :id, :content, :done, :list

  def list
    object.list.id
  end
end

```
Inside the list_serializer there is this code:
```rb

class ListSerializer < ActiveModel::Serializer
  attributes :id, :title, :hidden, :items

  def items
    object.items.pluck(:id)
  end
end

```

I think that these are methods inside the serializer, but I don't know what the methods are actually doing or where the object that they're referring to is coming from.

I've modeled my code the same way, but I'm getting this error when I attempt to navigate to:
http://localhost:4741/goals/daily_achievements
```sql

Started GET "/goals/daily_achievements" for ::1 at 2017-01-13 15:16:35 -0500
Processing by DailyAchievementsController#index as HTML
  DailyAchievement Load (1.1ms)  SELECT "daily_achievements".* FROM "daily_achievements"
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (35.18ms)
Completed 500 Internal Server Error in 109ms (ActiveRecord: 9.6ms)

NoMethodError (undefined method `id' for nil:NilClass):
  app/serializers/daily_achievement_serializer.rb:5:in `goal'
  app/controllers/daily_achievements_controller.rb:5:in `index'


  Rendered /Users/Peanut/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (65.2ms)
  Rendered /Users/Peanut/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (25.0ms)
  Rendered /Users/Peanut/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (5.4ms)
  Rendered /Users/Peanut/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (353.7ms)

```
And if I try to go to a specific daily_achievement: http://localhost:4741/goals/daily_achievements/1

null  is the only thing that is displayed.

Here are my controllers and serializers:
```rb

class DailyAchievementsController < ApplicationController
  def index
    @daily_achievements = DailyAchievement.all

    render json: @daily_achievements
  end

  def show
    render json: @daily_achievement
  end

  def create
    @daily_achievements = DailyAchievement.new(daily_achievement_params)

    if @daily_achievements.save
      render json: @daily_achievement, status: :created
    else
      render json: @daily_achievement.errors, status: :unprocessable_entity
    end
  end

  def update
    @daily_achievement = DailyAchievement.find(params[:id])

    if @daily_achievement.update(daily_achievement_params)
      head :no_content
    else
      render json: @daily_achievement.errors, status: :unprocessable_entity
    end
  end

  def set_daily_achievement
    @daily_achievement = DailyAchievement.find(params[:id])
  end

  def daily_achievement_params
    params.require(:daily_achievement).permit(:log, :image, :goal_id, :user_id)
  end

  private :set_daily_achievement, :daily_achievement_params
end

```

```rb

class DailyAchievementSerializer < ActiveModel::Serializer
  attributes :id, :log, :image, :goal

  def goal
    object.goal.id
  end
end

```

```rb

class GoalsController < ProtectedController
  before_action :set_goal, only: [:show, :update, :destroy]

  def index
    @goals = Goal.all

    render json: @goals
  end

  def show
    render json: Goal.find(params[:id])
  end

  def create
    @goal = current_user.goals.build(goal_params)

    if @goal.save
      render json: @goal, status: :created
    else
      render json: @goal.errors, status: :unprocessable_entity
    end
  end

  def update
    if @goal.update(goal_params)
      head :no_content
    else
      render json: @goal.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @goal.destroy

    head :no_content
  end

  def set_goal
    @goal = current_user.goals.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :start_date, :end_date, :user_id)
  end

  private :set_goal, :goal_params
end


```

```rb


class GoalSerializer < ActiveModel::Serializer
  attributes :id, :start_date, :end_date, :user, :title, :daily_achievements

  def daily_achievements
    object.daily_achievements.pluck(:id)
  end
end

```

**Comment by ielole** [comment]
I've cleaned up some dirty data, by giving all daily_achievements a goal_id and now http://localhost:4741/goals/daily_achievements is showing the correct data. However, I am still only getting null and this error:
```sql

Started GET "/goals/daily_achievements/2" for ::1 at 2017-01-13 15:47:24 -0500
Processing by DailyAchievementsController#show as HTML
  Parameters: {"id"=>"2"}
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Class (0.36ms)
Completed 200 OK in 8ms (Views: 7.3ms | ActiveRecord: 0.0ms)


```
when I attempt to show a specific daily achievement, ie  http://localhost:4741/goals/daily_achievements/1.

**Comment by ielole** [comment]
The error above is what you'll see if you don't include:
```rb
before_action :set_daily_achievement, only: [:show, :update, :destroy]
```

to your controller. Adding the above code fixed the issue.
