### ISSUE TITLE
Ember sending blank object to Express

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#384]
I'm trying to create a new "Shop" from my Ember Front-End. I have a shops controller that is working fine via curl requests on my express back-end. I tried adding a console.log but looks like the back-end is receiving empty shop objects from Ember (shop {}). Not sure why the data is not being sent, as I'm able to see the yelp_id on the shop object from console log prior to calling save.

**components/create-shop/component.js**
```js
import Ember from 'ember';

export default Ember.Component.extend({
  shop: {},
  actions: {
    save () {
      console.log("create/shop", this.get('shop'));
      this.sendAction('save', this.get('shop'));
    },
    cancel () {
      this.sendAction('cancel', this.get('shop'));
    },
  },
});
```
**components/create-shop/template.hbs**
```js
<form {{action 'save' on='submit'}}>
  {{input placeholder='Yelp ID' value=shop.yelp_id}}
  <button type='submit' class='btn btn-xs'>Save</button>
  <button {{action 'cancel'}} class='btn btn-xs btn-danger'>Cancel</button>
</form>
```
**shops/new/route.js**
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').createRecord('shop', {});
  },
  actions: {
    createShop (shop) {
      shop.save();
      console.log("create", shop);
    },
    cancelCreateShop (shop) {
      console.log("cancel");
      shop.rollbackAttributes();
    },
  },
});
```
**shops/new/template.hbs**
```js
hannaford-portland-3
{{create-shop
  shop=model
  save='createShop'
  cancel='cancelCreateShop'}}
```

**Comment by coffeeisamazing** [comment]
**console errors**
```bash
create/shop Class {store: Class, _internalModel: InternalModel, currentState: Object, isError: true, adapterError: AdapterError…}
2017-01-15 12:34:03.483 route.js:9 create Class {store: Class, _internalModel: InternalModel, currentState: Object, isError: true, adapterError: AdapterError…}
2017-01-15 12:34:04.026 :4741/shops:1 POST http://localhost:4741/shops 500 (Internal Server Error)
2017-01-15 12:34:04.026 jquery.js:9536 XHR finished loading: POST "http://localhost:4741/shops".
send @ jquery.js:9536
ajax @ jquery.js:9143
_ajaxRequest @ rest.js:976
(anonymous) @ rest.js:966
initializePromise @ ember.debug.js:58213
Promise @ ember.debug.js:58698
ajax @ rest.js:949
createRecord @ rest.js:689
_commit @ store.js:2335
(anonymous) @ store.js:1603
flushPendingSave @ store.js:1586
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
run @ ember.debug.js:21514
handler @ ember.debug.js:11103
(anonymous) @ ember.debug.js:41005
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-01-15 12:34:04.028 ember.debug.js:16905 Ember Data Request POST http://localhost:4741/shops returned a 500
Payload (application/json; charset=utf-8)
[object Object]
Error
    at AdapterError (http://localhost:7165/assets/vendor.js:88320:16)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:89952:14)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:73484:28)
    at Class.superWrapper [as handleResponse] (http://localhost:7165/assets/vendor.js:50189:22)
    at ajaxError (http://localhost:7165/assets/vendor.js:90450:25)
    at Class.hash.error (http://localhost:7165/assets/vendor.js:90024:23)
    at fire (http://localhost:7165/assets/vendor.js:3637:31)
    at Object.fireWith [as rejectWith] (http://localhost:7165/assets/vendor.js:3767:7)
    at done (http://localhost:7165/assets/vendor.js:9576:14)
    at XMLHttpRequest.<anonymous> (http://localhost:7165/assets/vendor.js:9816:9)
defaultDispatch @ ember.debug.js:16905
dispatchError @ ember.debug.js:16888
onerrorDefault @ ember.debug.js:30389
trigger @ ember.debug.js:57833
(anonymous) @ ember.debug.js:58717
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
join @ ember.debug.js:746
run.join @ ember.debug.js:21556
hash.error @ rest.js:963
fire @ jquery.js:3305
fireWith @ jquery.js:3435
done @ jquery.js:9244
(anonymous) @ jquery.js:9484
```

**Comment by gaand** [comment]
`2017-01-15 12:34:04.026 :4741/shops:1 POST http://localhost:4741/shops 500 (Internal Server Error)`

What does your server log?

You can get more output by prepending `DEBUG=*` to the server command (i.e. `DEBUG=* grunt server`)

**Comment by coffeeisamazing** [comment]
Is this the correct syntax? I'm not seeing any additional output in console nor terminal.
```bash
nodemon DEBUG=*
```

edit: wrong sequence... DEBUG=* nodemon

**Comment by coffeeisamazing** [comment]
```bash
express:router dispatching OPTIONS /shops +14s
  express:router query  : /shops +0ms
  express:router expressInit  : /shops +0ms
  express:router corsMiddleware  : /shops +0ms
  express:router dispatching POST /shops +3ms
  express:router query  : /shops +0ms
  express:router expressInit  : /shops +0ms
  express:router corsMiddleware  : /shops +0ms
  express:router favicon  : /shops +0ms
  express:router logger  : /shops +0ms
  express:router jsonParser  : /shops +1ms
  body-parser:json content-type "application/json; charset=UTF-8" +14s
  body-parser:json content-encoding "identity" +2ms
  body-parser:json read body +0ms
  body-parser:json parse body +16ms
  body-parser:json parse json +0ms
  express:router urlencodedParser  : /shops +18ms
  body-parser:urlencoded body already parsed +0ms
  express:router router  : /shops +0ms
  express:router dispatching POST /shops +0ms
  express:router serveStatic  : /shops +561ms
  express:router <anonymous>  : /shops +0ms
  express:router <anonymous>  : /shops +0ms
  lobster-bean:error-handler { error: 
  lobster-bean:error-handler    { message: 'Server returned status code 404',
  lobster-bean:error-handler      error: 
  lobster-bean:error-handler       { [RestCallResponseFiltersUnhandledStatusError: Server returned status code 404]
  lobster-bean:error-handler         type: 'rest-call.response-filters.unhandled-status',
  lobster-bean:error-handler         message: 'Server returned status code 404',
  lobster-bean:error-handler         statusCode: 404,
  lobster-bean:error-handler         response: [Object],
  lobster-bean:error-handler         name: 'RestCallResponseFiltersUnhandledStatusError',
  lobster-bean:error-handler         fullType: 'rest-call.response-filters.unhandled-status' } } } +47s
  morgan log request +14s
POST /shops 500 582.037 ms - 800
```

**Comment by coffeeisamazing** [comment]
I just figured it out. I had mistyped the yelp ID property in my shop model. I had used camel case instead of snake case. Thanks Antony.

**BEFORE**
```js
export default DS.Model.extend({
  name: DS.attr(),
  yelpId: DS.attr()
});
```

**AFTER**
```js
export default DS.Model.extend({
  name: DS.attr(),
  yelp_id: DS.attr()
});
```
