### ISSUE TITLE
ember observer breaks page

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#389]
So I'm trying to make an observer which sends a computed property to an outside component anytime the computed property changes. Here's my code:

```js
// A wrapper around the YouTube method to get current time.
  	currentTime: computed({
  		get() {
  			let player = this.get('player');
  			let value = player ? player.getCurrentTime() : 0;
  			return value;
  		},
  		set(key, value) {
  			return value;
  		}
  	}),

    timeChanged: observer('currentTime', function() {
      console.log('currentTime is ', this.get('currentTime'));
      this.send('timeChanged', currentTime);
    }),
```

It looks like the observer fires when currentTime changes, but causes the page to break. Here's the error I'm getting:

TypeError: t[m] is not a function at Object.applyStr (http://localhost:7165/assets/vendor.js:49483:20) at Object.sendEvent (http://localhost:7165/assets/vendor.js:27709:23) at ObserverSet.flush (http://localhost:7165/assets/vendor.js:31083:25) at endPropertyChanges (http://localhost:7165/assets/vendor.js:31621:19) at Object.changeProperties (http://localhost:7165/assets/vendor.js:31646:26) at Object.setProperties (http://localhost:7165/assets/vendor.js:32712:32) at Class.setProperties (http://localhost:7165/assets/vendor.js:44499:26) at Class.startTimer (http://localhost:7165/assets/ga-wdi-boston.you-riff.js:479:12) at Class.playing (http://localhost:7165/assets/ga-wdi-boston.you-riff.js:622:14) at Class.send (http://localhost:7165/assets/vendor.js:50429:35)

I think I must be calling observer incorrectly?

**Comment by ioncrash** [comment]
Got it! Deleted the observer entirely and moved the sendAction into the function called by the computed method. 

```js
currentTime: computed({
  		get() {
  			let player = this.get('player');
  			let value = player ? player.getCurrentTime() : 0;
  			return value;
  		},
  		set(key, value) {
        this.sendAction('timeChanged', value)
  			return value;
  		}
  	}),
```

the time is now being received by the outside component correctly!
