### ISSUE TITLE
Express API - unexpected token ILLEGAL

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#394]
I was updating my controllers and models when my server crashed with the following error message. After failing to find any problematic code, I reverted back to my last known working branch - however, now the error still persists.

```bash
~/wdi/projects/lobster-bean/lobster-bean-back-end (dev)$ nodemon
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./bin/express server`
/Users/n0172147/wdi/projects/lobster-bean/lobster-bean-back-end/app/models/.DS_Store:1
(function (exports, require, module, __filename, __dirname) { 
                                                              

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/n0172147/wdi/projects/lobster-bean/lobster-bean-back-end/lib/wiring/loader.js:13:39
    at Array.forEach (native)
    at fs.readdirSync.filter.entry.forEach (/Users/n0172147/wdi/projects/lobster-bean/lobster-bean-back-end/lib/wiring/loader.js:12:5)
    at Object.<anonymous> (/Users/n0172147/wdi/projects/lobster-bean/lobster-bean-back-end/app/models/index.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by coffeeisamazing** [comment]
Antony Donovan [2:13 PM] 
@caleb  Why is there a `.DS_Store` in your models directory?

Caleb Searles [2:14 PM] 
Hm... I copied in an old model file I had using finder.
Keeps recreating when I delete it.

Antony Donovan [2:19 PM] 
That's the problem.  I'd google for how to delete it. You probably have to tell finder to stop doing something.  I'm not on a Mac right now so I can't really experiment.

Caleb Searles [2:26 PM] 
Resolved. rm -f .DS_Store did the trick.
