### ISSUE TITLE
can't deploy to heroku

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/capstone-project#40]
I got the following error message:  I'm just feeling paranoid because last time I did not have to reinstall npm or node

2015-12-16T17:15:47.651803+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-16T17:15:50.318634+00:00 app[web.1]: 
2015-12-16T17:15:50.318631+00:00 app[web.1]: > node-express-session@0.0.0 start /app
2015-12-16T17:15:50.318622+00:00 app[web.1]: 
2015-12-16T17:15:50.318633+00:00 app[web.1]: > node ./bin/www
2015-12-16T17:15:51.393229+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-12-16T17:15:51.393219+00:00 app[web.1]: 
2015-12-16T17:15:51.413035+00:00 app[web.1]: npm ERR! Linux 3.13.0-71-generic
2015-12-16T17:15:51.393224+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-16T17:15:51.393230+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2015-12-16T17:15:51.393231+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2015-12-16T17:15:51.393232+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete](net.js:1063:14)
2015-12-16T17:15:51.406209+00:00 app[web.1]: 
2015-12-16T17:15:51.413665+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-16T17:15:51.414074+00:00 app[web.1]: npm ERR! node v5.1.1
2015-12-16T17:15:51.393223+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mongodb/lib/server.js:235
2015-12-16T17:15:51.415469+00:00 app[web.1]: npm ERR! npm  v3.3.12
2015-12-16T17:15:51.415829+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-16T17:15:51.416139+00:00 app[web.1]: npm ERR! node-express-session@0.0.0 start: `node ./bin/www`
2015-12-16T17:15:51.416423+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-16T17:15:51.416697+00:00 app[web.1]: npm ERR! 
2015-12-16T17:15:51.416980+00:00 app[web.1]: npm ERR! Failed at the node-express-session@0.0.0 start script 'node ./bin/www'.
2015-12-16T17:15:51.417278+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2015-12-16T17:15:51.417528+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the node-express-session package,
2015-12-16T17:15:51.393225+00:00 app[web.1]:                                       ^
2015-12-16T17:15:51.417785+00:00 app[web.1]: npm ERR! not with npm itself.
2015-12-16T17:15:51.417977+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-12-16T17:15:51.418170+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-12-16T17:15:51.418362+00:00 app[web.1]: npm ERR! You can get their info via:
2015-12-16T17:15:51.418565+00:00 app[web.1]: npm ERR!     npm owner ls node-express-session
2015-12-16T17:15:51.418757+00:00 app[web.1]: npm ERR! There is likely additional logging output above.

**Comment by mkutter72** [comment]
oh I'm also using web sockets so I don't know if that is an issue

**Comment by jrhorn424** [comment]
I'm guessing this was due to pointing express to a localhost mongo instance instead of one on heroku. Is that correct?

**Comment by srhoulam** [comment]
It was actually running multiple http servers within the same application. Mongo connections were fine.
