### ISSUE TITLE
Model not clearing when using Nav Bar

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#419]
I have a create form with submit and cancel. If you select cancel, you are returned to the list screen as expected. If you navigate back to list using the navbar links, there is an "empty" object in the listing. If you refresh the page, the empty object disappears. I assume this is an extra object living on in the front-end model.

route
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    // this.get('store').unloadAll('shop'); I tried unloading but broke creating new objects too.
    return this.get('store').findAll('shop');
  },
  actions: {
    delete(shop) {
      console.log("Shops/route", shop);
      shop.destroyRecord();
    },
    edit(shop) {
      console.log("shops/route", shop);
      this.transitionTo('shop/edit', shop);
    },
    show(shop) {
      console.log("shops/route", shop);
      this.transitionTo('shop/show', shop);
    },
  }
});
```

component
```js
import Ember from 'ember';

export default Ember.Component.extend({
  shop: {},
  actions: {
    save () {
      console.log("create/shop", this.get('shop'));
      this.sendAction('save', this.get('shop'));
    },
    cancel () {
      console.log("Component/Cancel");
      this.sendAction('cancel', this.get('shop'));
    },
  },
});
```

**Comment by raq929** [comment]
Can I see your template for the route?

**Comment by coffeeisamazing** [comment]
```js
{{shop-create
  shop=model
  save='createShop'
  cancel='cancelCreateShop'}}
```

**Comment by coffeeisamazing** [comment]
I was thinking I could hide the nav bar on that screen but I'd assume there's a cleaner way...

**Comment by raq929** [comment]
Check out `willTransition` here: http://emberjs.com/api/classes/Ember.Route.html. You can probably tell it to clear any unsaved shops if it's going to transition. 
(I'm assuming the empty shop is being created for when you make a new one, and it's not being cleared.)

**Comment by coffeeisamazing** [comment]
I tried the following which fixed my bug but then broke my create method. Any thoughts?

**router**
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').createRecord('shop', {});
  },

  actions: {
    willTransition: function() {
      this.get('store').unloadAll('shop');
    },
    createShop (shop) {
      shop.save()
      .then(this.transitionTo('shops'));
      console.log("create", shop);
    },
    cancelCreateShop (shop) {
      console.log("cancel");
      this.set('shop', {});
      shop.rollbackAttributes();
      this.transitionTo('application');
    },
  },
});

```
**error**
```bash
Assertion Failed: You can only unload a record which is not inFlight. `<shop:null>`
Error
    at assert (http://localhost:7165/assets/vendor.js:16268:13)
    at Object.assert (http://localhost:7165/assets/vendor.js:27196:34)
    at assert (http://localhost:7165/assets/vendor.js:82598:37)
    at Object.assertAgainstUnloadRecord [as unloadRecord] (http://localhost:7165/assets/vendor.js:86573:39)
    at InternalModel.send (http://localhost:7165/assets/vendor.js:84544:34)
    at InternalModel.unloadRecord (http://localhost:7165/assets/vendor.js:84344:14)
    at Class.unloadAll (http://localhost:7165/assets/vendor.js:92224:18)
    at Class.willTransition (http://localhost:7165/assets/lobster-bean-ember.js:1543:27)
    at Router.triggerEvent (http://localhost:7165/assets/vendor.js:38415:35)
    at trigger (http://localhost:7165/assets/vendor.js:66125:12)
defaultDispatch @ ember.debug.js:16905
dispatchError @ ember.debug.js:16888
onerrorDefault @ ember.debug.js:30389
trigger @ ember.debug.js:57833
(anonymous) @ ember.debug.js:58717
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
run @ ember.debug.js:21514
handler @ ember.debug.js:11103
(anonymous) @ ember.debug.js:41005
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-01-17 16:12:35.971 jquery.js:9536 XHR finished loading: GET "http://localhost:4741/shops".
send @ jquery.js:9536
ajax @ jquery.js:9143
_ajaxRequest @ rest.js:976
(anonymous) @ rest.js:966
initializePromise @ ember.debug.js:58213
Promise @ ember.debug.js:58698
ajax @ rest.js:949
findAll @ rest.js:462
_findAll @ finders.js:132
_fetchAll @ store.js:1348
findAll @ store.js:1309
model @ route.js:5
deserialize @ ember.debug.js:25943
applyHook @ ember.debug.js:55703
runSharedModelHook @ ember.debug.js:56301
getModel @ ember.debug.js:56500
(anonymous) @ ember.debug.js:55557
tryCatch @ ember.debug.js:58165
invokeCallback @ ember.debug.js:58177
publish @ ember.debug.js:58148
(anonymous) @ ember.debug.js:37633
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
run @ ember.debug.js:21514
handler @ ember.debug.js:11103
(anonymous) @ ember.debug.js:41005
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-01-17 16:12:36.347 :4741/shops:1 POST http://localhost:4741/shops 500 (Internal Server Error)
2017-01-17 16:12:36.347 jquery.js:9536 XHR finished loading: POST "http://localhost:4741/shops".
send @ jquery.js:9536
ajax @ jquery.js:9143
_ajaxRequest @ rest.js:976
(anonymous) @ rest.js:966
initializePromise @ ember.debug.js:58213
Promise @ ember.debug.js:58698
ajax @ rest.js:949
createRecord @ rest.js:689
_commit @ store.js:2335
(anonymous) @ store.js:1603
flushPendingSave @ store.js:1586
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
run @ ember.debug.js:21514
handler @ ember.debug.js:11103
(anonymous) @ ember.debug.js:41005
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-01-17 16:12:36.350 ember.debug.js:16905 Ember Data Request POST http://localhost:4741/shops returned a 500
Payload (application/json; charset=utf-8)
[object Object]
Error
    at AdapterError (http://localhost:7165/assets/vendor.js:94638:16)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:96270:14)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:78039:28)
    at Class.superWrapper [as handleResponse] (http://localhost:7165/assets/vendor.js:50189:22)
    at ajaxError (http://localhost:7165/assets/vendor.js:96768:25)
    at Class.hash.error (http://localhost:7165/assets/vendor.js:96342:23)
    at fire (http://localhost:7165/assets/vendor.js:3637:31)
    at Object.fireWith [as rejectWith] (http://localhost:7165/assets/vendor.js:3767:7)
    at done (http://localhost:7165/assets/vendor.js:9576:14)
    at XMLHttpRequest.<anonymous> (http://localhost:7165/assets/vendor.js:9816:9)
```

**Comment by coffeeisamazing** [comment]
Still stuck on this one. I've continued to experiment with transition and beforemodel functions without luck.

**Comment by gaand** [comment]
This seems to work:

```js
    willTransition (transition) {
      let store = this.get('store');
      store.peekAll('list').forEach(function (list) {
        if (list.get('isNew') && list.get('hasDirtyAttributes')) {
          list.rollbackAttributes();
        }
      });
      return true;
    },
```

**Comment by coffeeisamazing** [comment]
Great, works for me. Appears to have fixed navigating off the create page by both browser buttons and nav bar buttons. I added the following function to my shops/new/route.js actions. Only changes from Antony's above is updating list to my shop object and removing the unused transition parameter. Thanks everybody!

```js
    willTransition() {
      let store = this.get('store');
      store.peekAll('shop').forEach(function(shop) {
        if (shop.get('isNew') && shop.get('hasDirtyAttributes')) {
          shop.rollbackAttributes();
        }
      });
      return true;
    },
```
