### ISSUE TITLE
Error handling for failed third party API call

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/capstone-project#441]
I'm calling the Yelp Business API as part of my shop#update method in Express. If the user enters an invalid yelp ID, it will inevitably error out. What approach can I use to more gracefully capture the error and display using flash messages?

shop#update
```js
const update = (req, res, next) => {
  let search = {
    _id: req.params.id
  };
  Shop.findOne(search)
    .then(shop => {
      if (!shop) {
        return next();
      }
      let yelpId = req.body.shop.yelp_id;
      yelp.accessToken(process.env.YELP_CLIENT_ID, process.env.YELP_CLIENT_SECRET)
        .then(response => {
          const client = yelp.client(response.jsonBody.access_token);
          client.business(yelpId)
            .then(response => {
              console.log("GOT YELP!");
              req.body.shop.name = response.jsonBody.name;
              req.body.shop.url = response.jsonBody.url;
              req.body.shop.image_url = response.jsonBody.image_url;
              req.body.shop.location_address = response.jsonBody.location.address1;
              req.body.shop.location_longitude = response.jsonBody.coordinates.longitude;
              req.body.shop.location_latitude = response.jsonBody.coordinates.latitude;
              console.log(req.body.shop);

              delete req.body._owner; // disallow owner reassignment.
              return shop.update(req.body.shop)
                .then(() => res.sendStatus(204));

            })
            .catch(function(err) {
              console.log("error#", err);
              next();
            });
          });
    })
    .catch(next);
};
```
console
```bash
jquery.js:9536 XHR finished loading: PUT "http://localhost:4741/shops/587fc8074e161dd9f3c58863".
send @ jquery.js:9536
ajax @ jquery.js:9143
_ajaxRequest @ rest.js:976
(anonymous) @ rest.js:966
initializePromise @ ember.debug.js:58213
Promise @ ember.debug.js:58698
ajax @ rest.js:949
updateRecord @ rest.js:723
_commit @ store.js:2335
(anonymous) @ store.js:1603
flushPendingSave @ store.js:1586
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
run @ ember.debug.js:21514
handler @ ember.debug.js:11103
(anonymous) @ ember.debug.js:41005
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-01-18 14:54:55.403 ember.debug.js:16905 Ember Data Request PUT http://localhost:4741/shops/587fc8074e161dd9f3c58863 returned a 404
Payload (application/json; charset=utf-8)
[object Object]
Error
    at AdapterError (http://localhost:7165/assets/vendor.js:94638:16)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:96270:14)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:78039:28)
    at Class.superWrapper [as handleResponse] (http://localhost:7165/assets/vendor.js:50189:22)
    at ajaxError (http://localhost:7165/assets/vendor.js:96768:25)
    at Class.hash.error (http://localhost:7165/assets/vendor.js:96342:23)
    at fire (http://localhost:7165/assets/vendor.js:3637:31)
    at Object.fireWith [as rejectWith] (http://localhost:7165/assets/vendor.js:3767:7)
    at done (http://localhost:7165/assets/vendor.js:9576:14)
    at XMLHttpRequest.<anonymous> (http://localhost:7165/assets/vendor.js:9816:9)
```

express server output
```bash
POST /shops 201 25.145 ms - 233
error#1 { [RestCallResponseFiltersUnhandledStatusError: Server returned status code 404]
  type: 'rest-call.response-filters.unhandled-status',
  message: 'Server returned status code 404',
  statusCode: 404,
  response: 
   { statusCode: 404,
     headers: 
      { server: 'nginx',
        'content-type': 'application/json; charset=UTF-8',
        'x-proxied': 'extlb7-r10-sfo2',
        'content-length': '96',
        'accept-ranges': 'bytes',
        date: 'Wed, 18 Jan 2017 19:54:55 GMT',
        via: '1.1 varnish',
        age: '0',
        connection: 'close',
        'x-served-by': 'cache-bos8227-BOS',
        'x-cache': 'MISS',
        'x-cache-hits': '0',
        'x-timer': 'S1484769295.232830,VS0,VE135' },
     body: '{"error": {"code": "BUSINESS_NOT_FOUND", "description": "The requested business was not found"}}' },
  name: 'RestCallResponseFiltersUnhandledStatusError',
  fullType: 'rest-call.response-filters.unhandled-status' }
PUT /shops/587fc8074e161dd9f3c58863 404 440.514 ms - 105
```

**Comment by raq929** [comment]
I would put this in your `catch`. If `err.name === RestCallResponseFiltersUnhandledStatusError` do the thing. 
(Is that what you're asking?)

**Comment by coffeeisamazing** [comment]
Added a catch but I still get the big red adapter error in console. I thought this would remove it?

```js
    save (shop) {
      shop.save()
        .then(this.transitionTo('application'))
        .catch((console.log("ERROR!"))
        );
    },
```

**Comment by coffeeisamazing** [comment]
Perhaps I can rephrase the last question... is it expected behavior to still see the error in console even with catching and handling? Not sure if this is unavoidable or counts as a user-facing-bug when working with a third party API.

**Comment by coffeeisamazing** [comment]
Here is the current iteration. I'm still getting the red errors in console and the flash messages aren't displaying.

```js
import Ember from 'ember';

export default Ember.Route.extend({
  flashMessages: Ember.inject.service(),

  model (params) {
    return this.get('store').findRecord('shop', params.id);
  },
  actions: {
    save (shop) {
      shop.save()
        .then(function() {
          this.transitionTo('application');
          this.get('flashMessages')
          .success('Successfully updated!');
        })
        .catch(function(err) {
          console.log("ERROR CAUGHT");
          this.get('flashMessages')
          .danger('There was a problem. Please try again.');
        });
    },
    cancel (shop) {
      shop.rollbackAttributes();
      this.transitionTo('shops');
    },
  },
});
```

**Comment by coffeeisamazing** [comment]
Fixed the flash messages - there was a problem with the context of "this".
I'm still getting this message in console though.

```bash
PUT http://localhost:4741/shops/587fd126255497dc0d149865 404 (Not Found)
```

**Comment by raq929** [comment]
Yeah, you'll keep getting the console error; that's OK. The users don't see that.

**Comment by coffeeisamazing** [comment]
Thanks Rachel.

Solution
```js
    save (shop) {
      let self = this;
      shop.save()
        .then(function() {
          self.transitionTo('application');
          self.get('flashMessages')
          .success('Successfully updated!');
        })
        .catch(function(err) {
          self.get('flashMessages')
          .danger('There was a problem. Please try again.');
        });
    },
```
