### ISSUE TITLE
Rails Server Not Working

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/capstone-project#479]
Running across the following issue when trying to use my local rails sever 

```sh
tarted POST "/sign-in" for ::1 at 2017-01-25 12:56:05 -0500

PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
):
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.7.1) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.7.1) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.7.1) lib/active_record/migration.rb:383:in `connection'
  activerecord (4.2.7.1) lib/active_record/migration.rb:370:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.6ms)
  Rendered /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendered /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (60.2ms)
```

Went ahead and followed troubleshooting steps listed in #325 but the issue occurs at the last step:
`rm /usr/local/var/postgres/postmaster.pid`

I get file/directory doesn't exist, so I went ahead and went into that folder and found I have `postmaster.opts`. Did a google search to see what was different but pretty much came up empty there. Then I went ahead and checked the server logs:
`tail /usr/local/var/log/postgres.log`

and got 
```sh
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.1.
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.1.
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.1.
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.1.
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.1.
```

So I am thinking I should update PostgreSQL somewhere but not sure where.

**Comment by akradin** [comment]
[Probably some clues here ](https://www.postgresql.org/docs/9.3/static/pgupgrade.html)

**Comment by gaand** [comment]
Have you tried following this https://www.postgresql.org/docs/current/static/upgrading.html ❓

**Comment by akradin** [comment]
Yes...coming up with nothing, not entirely sure how to navigate through these commands. For example, `pg_ctl stop` is a command that takes in options but when I do `pg_ctl --help` to get an idea of what those options are, I am not sure how to read something like 
`  pg_ctl stop    [-W] [-t SECS] [-D DATADIR] [-s] [-m SHUTDOWN-MODE]`

The docs then supply information on how to restart it using `/etc/rc.d/init.d/postgresql stop` but that is for Linux machines. So [I referenced this article](https://coderwall.com/p/ncxdlw/start-and-stop-postgresql-manually-on-mac-os-x) but ran into the original issue of `postmaster.pid` not working

**Comment by gaand** [comment]
Substitute `brew services <stop|start> postgresql` for `pg_ctl <stop|start>`.

You also need to substitute the paths to match where brew installs things.

**Comment by akradin** [comment]
Okay, we have a solution.
- First step which may be unnecessary but I think it makes life easier is to navigate to `/usr/local/var`
- From there, make a copy of the old `postgresql` file with `mv postgres postgres.old`
- Then run `initdb -D postgres` followed by `brew services list postgresql` to see if PostgreSql is running or not
- If it isn't running, `brew services list postgresql` to start it and double check with `brew services list postgresql` again
- run `psql`, this shouldn't work. Run `createdb <your_username>` and you should be able to run psql
- Just to double check, I went into the directory this project is in and ran
`bundle exec rake db:create` and `bundle exec rake db:nuke_pave`.

Issue resolved!

**Comment by YannFroment** [comment]
Thanks a lot, your solution worked for me !
