### ISSUE TITLE
Ember deploy error

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/capstone-project#496]
In the 6th step is says to run:
```md
ember build --environment=production
```

However, I am getting the following error:
```md
⠋ BuildingCannot find module '/Users/MD/wdi/projects/gear/ember/bower_components/ember/my-gear-compiler'
Error: Cannot find module '/Users/MD/wdi/projects/gear/ember/bower_components/ember/my-gear-compiler'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.included (/Users/MD/wdi/projects/gear/ember/node_modules/ember-cli-htmlbars-inline-precompile/index.js:48:20)
    at Class.superWrapper [as included] (/Users/MD/wdi/projects/gear/ember/node_modules/core-object/lib/assign-properties.js:34:20)
    at EmberApp.<anonymous> (/Users/MD/wdi/projects/gear/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:495:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/Users/MD/wdi/projects/gear/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:490:45)
    at new EmberApp (/Users/MD/wdi/projects/gear/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:140:8)
```

my-gear is the name of the app.
I am not sure as to what code is relevant... Please let me know as I am not too familiar with Ember.

**Comment by dsweetser** [comment]
@doremaxime have you followed that filepath to see if the file exists? It might still be called something like "ember-template-complier" instead, and if so you can change the name and try again.

**Comment by doremaxime** [comment]
Thanks for checking Dan! it was indeed called my-gear-compiler so I am not sure what is going on. Even stranger is that the command worked today and not yesterday.... I do not have an explanation for this.
