### ISSUE TITLE
ActionController::ParameterMissing

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/capstone-project#519]
I am trying to run a curl script to create a blog and I am getting this error

Error

```
Started POST "/blogs" for 127.0.0.1 at 2017-03-27 16:57:58 -0400
Processing by BlogsController#create as */*
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "18b6b63d19d4b6f231eb0e168150c921"], ["LIMIT", 1]]
Completed 400 Bad Request in 15ms (ActiveRecord: 0.3ms)


  
ActionController::ParameterMissing (param is missing or the value is empty: blog):
  
app/controllers/blogs_controller.rb:51:in `blog_params'
app/controllers/blogs_controller.rb:19:in `create'

```
Curl command from terminal
```
$ TOKEN="****" TITLE='test' SUBJECT='does it work' BLOG='testing the blog create script' AUTHOR='bill' sh scripts/blogs/create.sh 
```

Blog Controller
```
# frozen_string_literal: true
class BlogsController < OpenReadController
  before_action :set_blog, only: [:show, :update, :destroy]

  # GET /blogs
  def index
    @blogs = Blog.all

    render json: @blogs
  end

  # GET /blogs/1
  def show
    render json: @blog
  end

  # POST /blogs
  def create
    @blog = current_user.blogs.build(blog_params)

    if @blog.save
      render json: @blog, status: :created, location: @blog
    else
      render json: @blog.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      render json: @blog
    else
      render json: @blog.errors, status: :unprocessable_entity
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def blog_params
    params.require(:blog).permit(:title, :subject, :body, :author)
  end
end
```

Serializer
```
# frozen_string_literal: true
class BlogSerializer < ActiveModel::Serializer
  attributes :id, :title, :subject, :body, :author, :editable

  def editable
    scope == object.user
  end
end
```
create blog migration

```
# frozen_string_literal: true
class CreateBlogs < ActiveRecord::Migration[5.0]
  def change
    create_table :blogs do |t|
      t.string :title
      t.string :subject
      t.string :body
      t.string :author

      t.timestamps
    end
  end
end
```

curl script 
```
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/blogs"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Authorization: Token token=$TOKEN"
  --header "Content-Type: application/json" \
  --data '{
    "blog": {
      "title": "'"${TITLE}"'",
      "subject": "'"${SUBJECT}"'",
      "body": "'"${BODY}"'",
      "author": "'"${AUTHOR}"'"
    }
  }'

echo
```

So if there are any suggestions, that would be amazing. I am really concerned about running into what I ran into on project 2 because I never resolved a similar issue.

**Comment by novakw267** [comment]
I don't know if trying to regenerate the model just doesn't work, but I tried making another branch out my development so in theory to start at a new point before I made the scaffold. I attempted to regenerate the scaffold for blogs again, it generated as a open read controller instead of application controller.  I am not sure if that makes sense..

**Comment by doremaxime** [comment]
I see that in your script the params are: **title**, **subject**, **body**, and **author**.
However, in your CLI command you give the params: **title**, **subject**, **blog**, and **author**. 
```sh
$ TOKEN="****" TITLE='test' SUBJECT='does it work' BLOG='testing the blog create script' AUTHOR='bill' sh scripts/blogs/create.sh 
```

Have you tried switching the **blog** with **body**?

It could that it is not seeing the **body** param and ignoring the **blog** one.

**Comment by novakw267** [comment]
Yeah I did, I caught that after I filed the issue and forgot to update it. However it didn't fix it. I think I messed up the migration and capitalized the parameters in the migration and so if I run a migration it resets it to caps. However if I manually put them to lowercase letters I get a different error
```
Started POST "/blogs" for 127.0.0.1 at 2017-03-28 09:44:30 -0400
Processing by BlogsController#create as */*
  Parameters: {"blog"=>{"Title"=>"test", "Subject"=>"does it work", "Body"=>"testing the blog create script", "Author"=>"bill"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "18b6b63d19d4b6f231eb0e168150c921"], ["LIMIT", 1]]
Unpermitted parameters: Title, Subject, Body, Author
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.6ms)


  
NoMethodError (undefined method `title' for #<Blog:0x007f9c7eaaa268>
Did you mean?  Title
               Title?
               Title=):
  
```
And if I leave my curl script and the schema with capitals I get 
```
Started POST "/blogs" for 127.0.0.1 at 2017-03-28 09:46:53 -0400
Processing by BlogsController#create as */*
  Parameters: {"blog"=>{"title"=>"test", "subject"=>"does it work", "body"=>"testing the blog create script", "author"=>"bill"}}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "18b6b63d19d4b6f231eb0e168150c921"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 21ms (ActiveRecord: 4.0ms)


  
ActiveModel::UnknownAttributeError (unknown attribute 'title' for Blog.):
  
app/controllers/blogs_controller.rb:19:in `create'

```

What is the best way to reset a migration??

**Comment by novakw267** [comment]
I got passed this issue by editing the migrations and running 
```
bin/rake db:nuke_pave
```
, it allowed me to reset my migration for blogs. That is literally all it took to fix this issue. I hope this helps others in the future.
