### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/capstone-project#547]
not loading calls from api

```
POST https://salty-ravine-27099.herokuapp.com/search/neo/today 500 (Internal Server Error)
```
But then says 
```
XHR finished loading: POST "https://salty-ravine-27099.herokuapp.com/search/neo/today".
```

my api calls look like this

```
const searchPatentsApi = function () {
  const searchText = $('#search-box').val()
  const data = {
    search: {
      query: searchText
    }
  }
  $.ajax({
    headers: {
      Authorization: `Token token=${store.user.token}`
    },
    url: config.apiOrigin + '/search/patents',
    method: 'POST',
    data: data
  }).done(function (results) {
    $('.search-results').empty()
    console.log('patent data', results)
    for (let i = 0; i < results.results.length; i++) {
      const singleSearchResult = patentsTemplate(results.results[i])
      $('.search-results').append(singleSearchResult)
    }
  })
}
```

where the url goes through the config file

config looks like this

```
'use strict'

const config = {
  apiOrigins: {
    production: 'https://salty-ravine-27099.herokuapp.com',
    development: 'http://localhost:4741/'
  }
}

module.exports = config
```
Why is this not working?

**Comment by ggabrakadabra** [comment]
when I go to 

https://salty-ravine-27099.herokuapp.com/search/stats

it says the page I am looking for does not exist. 

Sign up and sign in still work and all everything works on local host. But not on the deployed version.

**Comment by raq929** [comment]
What's in the network tab? Are you making the request to the right api?

**Comment by raq929** [comment]
Click on the request in the network tab and look at the url.

**Comment by bernardlee** [comment]
Run `heroku logs` in the back end's repository after making a request.  It should give you a server log similar to the one shown in your terminal when it's running locally.  That might give you a clue about what the problem is.

**Comment by ggabrakadabra** [comment]
response in network tab 
```
{"status":500,"error":"Internal Server Error"}
```

heroku logs
```
2017-03-29T14:37:22.905918+00:00 heroku[router]: at=info method=POST path="/search/neo/today" host=salty-ravine-27099.herokuapp.com request_id=46703554-14b6-42b1-b4ce-c8b3d746341c fwd="144.121.82.194" dyno=web.1 connect=1ms service=137ms status=500 bytes=465 protocol=https
2017-03-29T14:37:22.925231+00:00 heroku[router]: at=info method=POST path="/search/stats" host=salty-ravine-27099.herokuapp.com request_id=cca1e6be-f84a-4bba-a46f-4a59e510ae9e fwd="144.121.82.194" dyno=web.1 connect=0ms service=78ms status=500 bytes=465 protocol=https
2017-03-29T14:37:22.906165+00:00 app[web.1]: [46703554-14b6-42b1-b4ce-c8b3d746341c] Completed 500 Internal Server Error in 132ms (ActiveRecord: 0.9ms)
2017-03-29T14:37:22.907039+00:00 app[web.1]: [46703554-14b6-42b1-b4ce-c8b3d746341c]   
2017-03-29T14:37:22.907131+00:00 app[web.1]: [46703554-14b6-42b1-b4ce-c8b3d746341c] OpenURI::HTTPError (403 Forbidden):
2017-03-29T14:37:22.907231+00:00 app[web.1]: [46703554-14b6-42b1-b4ce-c8b3d746341c] app/controllers/searches_controller.rb:69:in `neo_today'
2017-03-29T14:37:22.910199+00:00 app[web.1]: [cca1e6be-f84a-4bba-a46f-4a59e510ae9e]   
2017-03-29T14:37:22.907197+00:00 app[web.1]: [46703554-14b6-42b1-b4ce-c8b3d746341c]   
2017-03-29T14:37:22.910432+00:00 app[web.1]: [cca1e6be-f84a-4bba-a46f-4a59e510ae9e] OpenURI::HTTPError (403 Forbidden):
2017-03-29T14:37:22.909686+00:00 app[web.1]: [cca1e6be-f84a-4bba-a46f-4a59e510ae9e] Completed 500 Internal Server Error in 75ms (ActiveRecord: 0.8ms)
2017-03-29T14:37:22.910433+00:00 app[web.1]: [cca1e6be-f84a-4bba-a46f-4a59e510ae9e]   
2017-03-29T14:37:22.910434+00:00 app[web.1]: [cca1e6be-f84a-4bba-a46f-4a59e510ae9e] app/controllers/searches_controller.rb:78:in `neo_stats'
```

It's saying forbidden. So does that mean I'm not making the request correctly?

**Comment by bernardlee** [comment]
```
2017-03-29T14:37:22.907231+00:00 app[web.1]: [46703554-14b6-42b1-b4ce-c8b3d746341c] app/controllers/searches_controller.rb:69:in `neo_today'`

2017-03-29T14:37:22.910434+00:00 app[web.1]: [cca1e6be-f84a-4bba-a46f-4a59e510ae9e] app/controllers/searches_controller.rb:78:in `neo_stats'
```

These two lines seem to be of particular interest.  Check those lines to see what they do and what might be the cause of the issue.

**Comment by ggabrakadabra** [comment]
So since all of my api calls are giving the same error, it means that they aren't actually set up correctly in the back end?

Does this mean I need to change it back to having the requests in the front end?

**Comment by ggabrakadabra** [comment]
each one is having issues with 
```
 response = open(url)
```

**Comment by bernardlee** [comment]
Are the requests being sent to the API correctly?  i.e., are the correct parameters, API key, etc. being sent with the request?

**Comment by ggabrakadabra** [comment]
Yes there is an api key being sent with each request. They are tailored to either take params or not. 
If they weren't being sent correctly, how would they all be working on local host?

**Comment by bernardlee** [comment]
How are you storing and retrieving the API key?

**Comment by ggabrakadabra** [comment]
secrets.yml

```
# Do not modify this file

# Add non-production secrets to `.env` to be loaded by the `dotenv-rails` gem,
# e.g. `SECRET=terces`

development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE_DEVELOPMENT'] %>
  nasa_api_key: <%= ENV['NASA_API_KEY'] %>

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE_TEST'] %>
  nasa_api_key: <%= ENV['NASA_API_KEY'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  nasa_api_key: <%= ENV['NASA_API_KEY'] %>
```

```
  def neo_today
    api_key = Rails.application.secrets.nasa_api_key
    url = "https://api.nasa.gov/neo/rest/v1/feed/today?detailed=true&api_key=#{api_key}"
    response = open(url)
    data_string = response.read
    json_string = JSON.parse(data_string)
    render json: json_string
  end
```

.env
```
NASA_API_KEY=***
```

what am I missing?

**Comment by bernardlee** [comment]
The `.env` file is ignored by git (it should be an entry in the `.gitignore` file).  It should never be uploaded anywhere.  Assuming that this is the case, no API key is being stored or retrieved on your deployed back end.  Since you're storing your API key as an environment variable, it needs to be set on the Heroku server.  Check the instructions in the [Rails Heroku Setup Guide](https://github.com/ga-wdi-boston/rails-heroku-setup-guide) to find out how to set environment variables.

**Comment by ggabrakadabra** [comment]
I ran 
```
heroku config:set NASA_API_KEY=$(rake secret)
```

```
Setting NASA_API_KEY and restarting ⬢ salty-ravine-27099... done, v11
```

then redeployed and same issue

**Comment by bernardlee** [comment]
`NASA_API_KEY` should be set to your API key.  What are you setting it to?

**Comment by ggabrakadabra** [comment]
For some reason I thought it automatically grabbed it from the .env file. So I set it using 
```
heroku config:set NASA_API_KEY=(api key)
```

then redeployed and it works 👍

**Comment by bernardlee** [comment]
It does when you're working locally because `.env` exists.  Since we don't (and shouldn't) push `.env` files to remotes, there's no file containing the API key to read so the back end was making requests without it.
