### ISSUE TITLE
   ActionController::RoutingError (No route matches [POST] "/repos"):

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#587]
I am trying to get my curl script working, for repos/create.sh
I do not have a route for repos according to this error, in my terminal but I don't understand why I am getting this error. Here is my routes.rb:
```
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :searches, only: [:show, :index]
  resources :bookmarked_repos, except: [:new, :edit]
  resources :repos, except: [:new, :edit]
  resources :examples, except: [:new, :edit]

  post '/search' => 'practices#search_github'
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```
Here is the curl script I am trying to run:
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/repos"
TOKEN="BAhJIiUyNWI1MzYwYTM5ZTk1MzE1NzJlNjJlNzE3YzM3ZjJiNQY6BkVG--7d5824e14b6bd930dc73a77cc73ed12f83fae824"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "repo": {
      "title": "ugjgjmgj",
      "language": "Ruby",
      "score": "5",
      "forks": "5",
      "description": "foobarbuzzbizz"
    }
  }'

  echo
```

**Comment by raq929** [comment]
Can you post the error please?

**Comment by alexkarasik** [comment]
Sorry, here is the terminal error:
```
Completed 500 Internal Server Error in 17ms (ActiveRecord: 0.5ms)


  
NoMethodError (undefined method `repos' for #<User:0x007fd48210b2c0>):
  
app/controllers/repos_controller.rb:19:in `create'
Started POST "/repos" for 127.0.0.1 at 2017-03-30 11:28:02 -0400
Processing by ReposController#create as */*
  Parameters: {"repo"=>{"title"=>"ugjgjmgj", "language"=>"Ruby", "score"=>"5", "forks"=>"5", "description"=>"foobarbuzzbizz"}}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "25b5360a39e9531572e62e717c37f2b5"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.5ms)


  
NoMethodError (undefined method `repos' for #<User:0x007fd4809036a0>):
  
app/controllers/repos_controller.rb:19:in `create'
```
Here is that section of repos_controller:
```
  # POST /repos
  def create
    @repo = current_user.repos.build(repo_params)

    if @repo.save
      render json: @repo, status: :created, location: @repo
    else
      render json: @repo.errors, status: :unprocessable_entity
    end
  end
```

**Comment by bernardlee** [comment]
What do your `User` and `Repos` models look like?

**Comment by alexkarasik** [comment]
```
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :bookmarked_repos
end
```
I think I need to add has_many:repos through :bookmarked_repos

**Comment by bernardlee** [comment]
What do your `BookmarkedRepos` and `Repos` models look like?

**Comment by alexkarasik** [comment]
bookmarked_repo model:
```
# frozen_string_literal: true
class BookmarkedRepo < ApplicationRecord
  belongs_to :repo
  belongs_to :user
end
```
repo model:
```
# frozen_string_literal: true
class Repo < ApplicationRecord
  has_many :bookmarked_repos

  validates :title, presence: true
  validates :language, presence: true
  validates :score, presence: true
  validates :forks, presence: true
  validates :description, presence: true

end
```

**Comment by alexkarasik** [comment]
I added
```
has_many:repos through :bookmarked_repos
```
to the user model and i think I need to add
```
has_many:users through :bookmarked_repos
```
the the repo model

but when I do I am getting the expecting keyword_end linter error 

Am I doing this wrong?

**Comment by alexkarasik** [comment]
The error was saying the problem is with this line in the controller, but I don't see anything wrong with it:
```
    @repo = current_user.repos.build(repo_params)
```

**Comment by bernardlee** [comment]
Check your syntax for using `through` associations.  Read through Detailed Association Reference section in [Active Record Associations](http://guides.rubyonrails.org/association_basics.html) to see which methods are available to models when an association is used.

**Comment by alexkarasik** [comment]
yeah, I just got it to work a few seconds ago. My syntax was off. I changed my repo model to:
  has_many :users, through: :bookmarked_repos
and my user model to:
  has_many :repos, through: :bookmarked_repos
with Sam's help. 
Thanks
