### ISSUE TITLE
Progress / touch-base 1:1 for assistance with adding feature

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/capstone-project#626]
I am attempting to add a feature and subsequently a new resource. I may be complicating the matter in this alone as I am just creating a single table called pictures on the back end wit a foreign key of the recipeID(this may be more easily achieved via a column on the recipe table but I need a new resource/relationship to meet min requirements). I have been studying the relationship between items and list in the ember-resource training and think I can get that to work in a manner i expect to work for my use case, i.e. I am wanting to allow the user to input a url on the recipe creation form, and have that replicate to the back end in the new pictures table, and have that record pul in to my receipe-details component. 

Here is my code so far- starting with ember:

models/recipe:
``` 
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  ingredient_list: DS.attr('string'),
  directions: DS.attr('string'),
  prep_time: DS.attr('string'),
  editable: DS.attr('boolean'),
  picture: DS.belongsTo('pictures', {async: true})
});
```
models/pictures: 
```
 import DS from 'ember-data';

export default DS.Model.extend({
  url: DS.attr('string'),
  picture: DS.belongsTo('recipe', {async: true})
});
```

2 new migrations on the backend:
 create pictures: 
```
class CreatePictures < ActiveRecord::Migration[5.0]
  def change
    create_table :pictures do |t|
      t.string :url

      t.timestamps
    end
  end
end
```

add_picture_to_recipe:
```
class AddPictureToRecipe < ActiveRecord::Migration[5.0]
  def change
    add_reference :pictures, :recipes, foreign_key: true
  end
end
```
schema:
```
  create_table "examples", force: :cascade do |t|
    t.text     "text",       null: false
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_examples_on_user_id", using: :btree
  end

  create_table "pictures", force: :cascade do |t|
    t.string   "url"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "recipe_id"
    t.index ["recipes_id"], name: "index_pictures_on_recipes_id", using: :btree
  end

  create_table "recipes", force: :cascade do |t|
    t.string   "title"
    t.string   "ingredient_list"
    t.string   "directions"
    t.string   "prep_time"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.integer  "user_id"
    t.index ["user_id"], name: "index_recipes_on_user_id", using: :btree
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.index ["email"], name: "index_users_on_email", unique: true, using: :btree
    t.index ["token"], name: "index_users_on_token", unique: true, using: :btree
  end

  add_foreign_key "examples", "users"
  add_foreign_key "pictures", "recipes", column: "recipe_id"
  add_foreign_key "recipes", "users"
end
```

  picture model - api:
```
class Picture < ApplicationRecord
  belongs_to :recipe
  validates :url, presence: true
end
```

recipe model - api: 
```
 # frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :recipes
end
```

In reviewing things, I think I need to create an adapter for pictures like items has in the ember-resource repo. Had some questions and was hoping I could get a sit down with someone for a bit and make sure I am not heading in the wrong direction. 

As it stands here is the error i get when trying a record creation:

output from a new create request:
```
Started POST "/recipes" for 127.0.0.1 at 2017-06-06 19:28:33 -0400
Processing by RecipesController#create as HTML
  Parameters: {"recipe"=>{"title"=>"test", "ingredient_list"=>"test", "directions"=>"test", "prep_time"=>nil, "editable"=>false, "picture_id"=>nil}}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "dd0514690a288d2348d9d8b9c6be2b89"], ["LIMIT", 1]]
Unpermitted parameters: editable, picture_id
   (0.2ms)  BEGIN
  SQL (1.0ms)  INSERT INTO "recipes" ("title", "ingredient_list", "directions", "created_at", "updated_at", "user_id") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["title", "test"], ["ingredient_list", "test"], ["directions", "test"], ["created_at", 2017-06-06 23:28:33 UTC], ["updated_at", 2017-06-06 23:28:33 UTC], ["user_id", 13]]
   (12.9ms)  COMMIT
[active_model_serializers] Rendered RecipeSerializer with ActiveModelSerializers::Adapter::Json (0.28ms)
Completed 201 Created in 37ms (Views: 1.2ms | ActiveRecord: 14.4ms)
```

**Comment by jordanallain** [comment]
that doesn't appear to be an error, it says 201 Created...were you able to look at the table afterward to see if it was stored correctly?

**Comment by antleo1995** [comment]
It's creating the recipe but not the entry on the picture table, and no, that is where I am stuck. I cannot even manually create a record. Attempting to do so now to even see if I can get the picture to associate with the recipe on the front end. I spent all night studying the ember-resources training and have a ton of questions. Hoping I can sit down with someone this morning. Not gaining any traction thus far.

**Comment by jordanallain** [comment]
Wanna come sit with me in the kitchen and we can try to figure it out?

**Comment by antleo1995** [comment]
Hell yeah, be right there.

**Comment by jordanallain** [comment]
Tony's gonna finish writing the back-end logic for the Pictures resource and then update this issue to see if that helped solve it.

**Comment by antleo1995** [comment]
Just noticed this on the back-end - seems crucial, and likely how it is getting the items for the list on the front end:

List serializer listr api:
```
class ListSerializer < ActiveModel::Serializer
  attributes :id, :title, :hidden, :items

  def items
    object.items.pluck(:id)
  end
end
```

Adding that code for sure. hehe

**Comment by jordanallain** [comment]
Aha! That was the `pluck` i was referencing earlier.

**Comment by antleo1995** [comment]
looks that way

**Comment by antleo1995** [comment]
Ok, getting an error now when I try to load any of my recipes. Clearly trying to make this association but something is borked:
```
Started GET "/recipes" for 127.0.0.1 at 2017-06-07 11:11:16 -0400
Processing by RecipesController#index as HTML
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "ac8466a132916fc997b29ae22e008c52"], ["LIMIT", 1]]
  Recipe Load (0.2ms)  SELECT "recipes".* FROM "recipes"
[active_model_serializers]   Picture Load (0.2ms)  SELECT  "pictures".* FROM "pictures" WHERE "pictures"."recipe_id" = $1 LIMIT $2  [["recipe_id", 1], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (2.99ms)
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.6ms)


  
NoMethodError (undefined method `pluck' for nil:NilClass):
  
app/serializers/recipe_serializer.rb:6:in `picture'
app/controllers/recipes_controller.rb:8:in `index'
```
api - routes
```
# frozen_string_literal: true
Rails.application.routes.draw do
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  get '/allrecipes' => 'recipes#showall'
  resources :users, only: [:index, :show]
  resources :examples, except: [:new, :edit]
  resources :recipes, except: [:new, :edit] do
    resources :pictures, only: [:index, :create]
  end
  resources :pcitures, only: [:show, :update, :destroy]
end
```
My 2 migration files (had to redo them):
```
class Pictures < ActiveRecord::Migration[5.0]
  def change
    create_table :pictures do |t|
      t.string :url

      t.timestamps
    end
  end
end
```
and references migration:
```
class AddRecipetoPicture < ActiveRecord::Migration[5.0]
  def change
    add_reference :pictures, :recipe, foreign_key: true
  end
end
```
Pictures controller
```
# frozen_string_literal: true

class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :update, :destroy]

# GET /pictures
# GET /pictures.json
def index
  @pictures = Picture.all

  render json: @pictures
end

# GET /pictures/1
# GET /pictures/1.json
def show
  render json: @picture
end

# POST /pictures
# POST /pictures.json
def create
  @picture = Picture.new(picture_params)

  if @picture.save
    render json: @picture, status: :created, location: @picture
  else
    render json: @picture.errors, status: :unprocessable_entity
  end
end

# PATCH/PUT /pictures/1
# PATCH/PUT /pictures/1.json
def update
  @picture = Picture.find(params[:id])

  if @picture.update(picture_params)
    head :no_content
  else
    render json: @picture.errors, status: :unprocessable_entity
  end
end

# DELETE /pictures/1
# DELETE /pictures/1.json
def destroy
  @picture.destroy

  head :no_content
end

  private

def set_picture
  @picture = Picture.find(params[:id])
end

def picture_params
  params.require(:picture).permit(:content, :done, :recipe_id)
end
end
```

**Comment by antleo1995** [comment]
Tony has assisted me in getting this to work. 

Needed to change
```
class ListSerializer < ActiveModel::Serializer
  attributes :id, :title, :hidden, :items

  def items
    object.items.pluck(:id)
  end
end
```
to...
```
class ListSerializer < ActiveModel::Serializer
  attributes :id, :title, :hidden, :items

  def items
    object.items.id
  end
end
```

**Comment by antleo1995** [comment]
Ok, progress has been made but I am still stuck again. At this point I am attempting to get a form setup to create the URL on the backend. I have gotten all code to fire, but when I try to populate the recipe_id via the component I am not passing anything. I see where the break down is but I am at a loss as to how to get the recipe info to my code. 

I know this code has access to recipe but when I try to run the addPic method it gets nothing for recipe. That code is as follows:

```
<label for="recipe">Title</label>
{{recipe-title title=recipe.title}}
<label for="recipe">Ingredients</label>
{{recipe-ingredients ingredients=recipe.ingredient_list}}
<label for="recipe">Directions</label>
{{recipe-directions directions=recipe.directions}}
<label for="recipe">Prep time</label>
{{preptime-input preptime=recipe.prep_time}}
<label for='recipe'>Image</label>
{{picture-input picture=picture.url}}
{{#link-to 'recipes.new' recipe=recipe}}<button type='submit' class='btn btn-md btn-primary'{{action 'addRecipe'}}>Create</button>{{/link-to}}
{{#link-to 'recipes'}}<button type='submit' class='btn btn-md btn-default'>Cancel</button>{{/link-to}}
```
here is the js for that component:
```
import Ember from 'ember';

export default Ember.Component.extend({

  recipe: {},
  picture: {
    url: null
  },
  actions: {
    create () {
      this.sendAction('create', this.get('recipe'));
      console.log("recipe form recipe is: ", this.get('recipe'));
    },
    addPic() {
      console.log('testing addPic');
      let data = this.get('picture');
      data.recipe = this.get('recipe');
      console.log('Data.recipe is: ', data.recipe)
      this.sendAction('addPic', data);
      this.set('picture.url', null);
    }
  },
});
```
and the route layer:
```
import Ember from 'ember';

export default Ember.Route.extend({
  recipe: Ember.inject.service(),
  flashMessages: Ember.inject.service(),
  classNames: ['recipe'],
  classNameBindings: ['listDetailHidden'],
  listDetailHidden: false,
  model () {
    return this.get('store').findAll('recipe');
  },
  actions: {
    create (recipe) {
      console.log('testing create inside recipes model');
      this.get('store').createRecord('recipe', recipe).save()
          .then(() => {
            this.transitionTo('recipes');
          })
       },
    toggleListDetail () {
        console.log('testing toggleListDetail');
      return this.toggleProperty('listDetailHidden');
    },
    createPic (picture) {
      console.log('testing createPic');
      let pictureRecord = this.get('store').createRecord('picture', picture);
      pictureRecord.save();
    },
    deleteRecipe(recipe) {
      console.log('Testing deleteRecipe in recipe.js route and recipe', recipe);
      recipe.destroyRecord();
    },
    clear(recipe) {
      console.log('testing clear');
      recipe = {};
    }
 }
});
```
here is my adapter:
```
import ApplicationAdapter from './application';

export default ApplicationAdapter.extend({
  createRecord (store, type, record) {
    console.log('Record is: ', record)
    const api = this.get('host')
    const serialized =  this.serialize(record, {includeId: true});
    console.log('Serialized is,', serialized);
    const recipeId = serialized.recipe_id;
    const url = `${api}/recipes/${recipeId}/pictures`;
    const data = { picture: serialized }

    return this.ajax(url, 'POST', {data})
  }
});
```

Getting the following console log - the pertinent part:
```
Serialized is, Object {url: "sdfsafad", recipe_id: null}
```

So if I can figure out why I am not passing in the recipe ID I will be nearly finished. It will then be a matter of pulling the picture based on the recipe, but I have the URL passing. 

Could use some help again. Still thrashing. Sorry to be so needy on this one, but i am finding ember to be quite a beast.

**Comment by payne-chris-r** [comment]
```diff
-data.recipe = this.get('recipe');
+data.set('recipe', this.get('recipe');
```

**Comment by antleo1995** [comment]
ah... dangit!! lol

**Comment by antleo1995** [comment]
Still giving me an undefined object
Thinking maybe this component should be a nested component to work like this.

**Comment by antleo1995** [comment]
Upon further inspection that doesn't make sense. The ember-resources component is not nested and appears to have access to the model. The component for for recipe creation has access to the recipe model. Not sure why that code doesn't.

**Comment by antleo1995** [comment]
Ok, added 
```
{{recipe-new-recipe-form recipe=model create='create' addPic='createPic'}}
```
now i get something - its not null but also not what i want
```
Class {store: Class, isLoaded: true, manager: RecordArrayManager…}content: (...)isLoaded: trueisUpdating: falsemanager: RecordArrayManagermodelName: (...)store: ClasswillDestroy: function superWrapper()_oldWillDestroy: function superWrapper()_super: function ROOT()_updatingPromise: nullisDestroyed: (...)isDestroying: (...)__ember1496865077374: "ember373"get content: function GETTER_FUNCTION()set content: function SETTER_FUNCTION(value)get modelName: function GETTER_FUNCTION()set modelName: function SETTER_FUNCTION(value)__proto__: Class
15:52:41.113 
```

**Comment by antleo1995** [comment]
I am more than elated to report I have, more or less, completed this feature now. I have a working relationship that allows me to pull a picture based on the ID of the recipe, and can create the record from the front end on a form for a particular recipe. I need to fix some bugs and tie some forms functionality together, but by and large the logic is there and working. 

My problem before was resolved by a) adding the recipe=model to the correct spot in my code - namely the spot i called the component b) i needed to do this on the recipE route not recipeS - this was the kicker - i added the model but was getting all the recipes instead of just the one my code needed for an id. 

Officially closing issue - thanks again!

**Comment by jordanallain** [comment]
Tony you are a boss, gonna miss working with ya!

**Comment by jordanallain** [comment]
@antleo1995 !!

**Comment by antleo1995** [comment]
Gonna miss you as well man. Certainly saved me many a major thrash sessions!

**Comment by jordanallain** [comment]
close me @antleo1995 !!
