### ISSUE TITLE
500 error on deployed site

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/capstone-project#628]
On my deployed site I can:
sign-up
login
change password
logout
I cannot do any crud on my other resource though. I get a 500 error. I would think if my server was not responding at all that I couldn't do any auth actions either. This works locally. My latest code is deployed to Heroku.

**Comment by BenGitsCode** [comment]
What's the output of `heroku config`?

**Comment by awoodrum87** [comment]
```
=== quiet-island-36585 Config Vars
CLIENT_ORIGIN:            https://awoodrum87.github.io
DATABASE_URL:             postgres://kftcddzvhduzpy:21010301273f4f2d2a7d020b97bd1db1e7609a3fbcd3b5302b2283a76cc7f5c6@ec2-54-225-68-71.compute-1.amazonaws.com:5432/d7v7h5oga5pr6d
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE: <removed by Angie>
SECRET_TOKEN: <removed by Angie>
```

**Comment by awoodrum87** [comment]
here is the text of a CRUD action in prod:
```
quiet-island-36585.herokuapp.com/quotes/:1 GET https://quiet-island-36585.herokuapp.com/quotes/ 500 (Internal Server Error)
```

**Comment by jordanallain** [comment]
have you checked the `heroku logs`?

**Comment by BenGitsCode** [comment]
Ha was just about to ask for that output.

**Comment by awoodrum87** [comment]
yeah the output is cray, but here it is. I'm going to do curl requests against the deployed URL and see what I get. Will report back
```
$ heroku logs
2017-06-07T18:45:33.000023+00:00 heroku[router]: at=info method=GET path="/quotes/" host=quiet-island-36585.herokuapp.com request_id=9df4d6b9-a869-490f-b979-f291aeacb463 fwd="144.121.82.194" dyno=web.1 connect=0ms service=10ms status=500 bytes=465 protocol=https
2017-06-07T18:45:32.990255+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463] Started GET "/quotes/" for 144.121.82.194 at 2017-06-07 18:45:32 +0000
2017-06-07T18:45:32.990942+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463] Processing by QuotesController#index as */*
2017-06-07T18:45:32.994680+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463]   User Load (2.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "ece0023d10393a7e92eb4759dfbb6ccd"], ["LIMIT", 1]]
2017-06-07T18:45:32.997872+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463]   Quote Load (1.0ms)  SELECT "quotes".* FROM "quotes"
2017-06-07T18:45:32.998085+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463] Completed 500 Internal Server Error in 7ms (ActiveRecord: 3.4ms)
2017-06-07T18:45:32.998826+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463]   
2017-06-07T18:45:32.998884+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "quotes" does not exist
2017-06-07T18:45:32.998886+00:00 app[web.1]: LINE 1: SELECT "quotes".* FROM "quotes"
2017-06-07T18:45:32.998886+00:00 app[web.1]:                                ^
2017-06-07T18:45:32.998890+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463]   
2017-06-07T18:45:32.998924+00:00 app[web.1]: [9df4d6b9-a869-490f-b979-f291aeacb463] app/controllers/quotes_controller.rb:9:in `index'
2017-06-07T18:45:32.998887+00:00 app[web.1]: : SELECT "quotes".* FROM "quotes"):
2017-06-07T18:47:18.299213+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814] Started PATCH "/change-password/1" for 144.121.82.194 at 2017-06-07 18:47:18 +0000
2017-06-07T18:47:18.300853+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814] Processing by UsersController#changepw as */*
2017-06-07T18:47:18.300917+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814]   Parameters: {"passwords"=>"[FILTERED]", "submit"=>"Change Password", "id"=>"1"}
2017-06-07T18:47:18.303785+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814]   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "ece0023d10393a7e92eb4759dfbb6ccd"], ["LIMIT", 1]]
2017-06-07T18:47:18.459495+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814]    (1.4ms)  BEGIN
2017-06-07T18:47:18.462749+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814]   User Exists (1.8ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND ("users"."id" != $2) LIMIT $3  [["email", "angie@email.com"], ["id", 1], ["LIMIT", 1]]
2017-06-07T18:47:18.467066+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814]   SQL (0.9ms)  UPDATE "users" SET "updated_at" = $1, "password_digest" = $2 WHERE "users"."id" = $3  [["updated_at", 2017-06-07 18:47:18 UTC], ["password_digest", "$2a$10$9opbY/2V06LbqEKtjoBGfOHqoYRgqysDY9vrny863Hy9r6ik/h1xq"], ["id", 1]]
2017-06-07T18:47:18.278968+00:00 heroku[router]: at=info method=OPTIONS path="/change-password/1" host=quiet-island-36585.herokuapp.com request_id=7960a689-f7b7-4bae-8965-25c2830520c7 fwd="144.121.82.194" dyno=web.1 connect=1ms service=2ms status=200 bytes=350 protocol=https
2017-06-07T18:47:18.470956+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814]    (3.6ms)  COMMIT
2017-06-07T18:47:18.471188+00:00 app[web.1]: [aabe731f-f32c-462f-99ad-6ba76ccc2814] Completed 204 No Content in 170ms (ActiveRecord: 8.3ms)
2017-06-07T18:47:18.471908+00:00 heroku[router]: at=info method=PATCH path="/change-password/1" host=quiet-island-36585.herokuapp.com request_id=aabe731f-f32c-462f-99ad-6ba76ccc2814 fwd="144.121.82.194" dyno=web.1 connect=0ms service=175ms status=204 bytes=461 protocol=https
2017-06-07T18:47:27.832420+00:00 heroku[router]: at=info method=OPTIONS path="/sign-out/1" host=quiet-island-36585.herokuapp.com request_id=186f1561-ac75-4cf3-ba6a-0900f8b8ade5 fwd="144.121.82.194" dyno=web.1 connect=0ms service=1ms status=200 bytes=350 protocol=https
2017-06-07T18:47:27.861863+00:00 heroku[router]: at=info method=DELETE path="/sign-out/1" host=quiet-island-36585.herokuapp.com request_id=ca8dee57-ecce-40d5-a191-c3ed1ceaa380 fwd="144.121.82.194" dyno=web.1 connect=1ms service=9ms status=204 bytes=461 protocol=https
2017-06-07T18:47:27.853811+00:00 app[web.1]: [ca8dee57-ecce-40d5-a191-c3ed1ceaa380] Started DELETE "/sign-out/1" for 144.121.82.194 at 2017-06-07 18:47:27 +0000
2017-06-07T18:47:27.854471+00:00 app[web.1]: [ca8dee57-ecce-40d5-a191-c3ed1ceaa380] Processing by UsersController#signout as */*
2017-06-07T18:47:27.854554+00:00 app[web.1]: [ca8dee57-ecce-40d5-a191-c3ed1ceaa380]   Parameters: {"id"=>"1"}
2017-06-07T18:47:27.856672+00:00 app[web.1]: [ca8dee57-ecce-40d5-a191-c3ed1ceaa380]   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "ece0023d10393a7e92eb4759dfbb6ccd"], ["LIMIT", 1]]
2017-06-07T18:47:27.858095+00:00 app[web.1]: [ca8dee57-ecce-40d5-a191-c3ed1ceaa380]   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
2017-06-07T18:47:27.860775+00:00 app[web.1]: [ca8dee57-ecce-40d5-a191-c3ed1ceaa380]   SQL (1.5ms)  UPDATE "users" SET "token" = '13eda9dc10ae10d7d8d18871048cfebd', "updated_at" = '2017-06-07 18:47:27.858677' WHERE "users"."id" = $1  [["id", 1]]
2017-06-07T18:47:27.861052+00:00 app[web.1]: [ca8dee57-ecce-40d5-a191-c3ed1ceaa380] Completed 204 No Content in 6ms (ActiveRecord: 2.6ms)
2017-06-07T18:47:43.073459+00:00 app[web.1]: [bf12f03a-e321-453a-bf3b-5e8fed179477] Started POST "/sign-in/" for 144.121.82.194 at 2017-06-07 18:47:43 +0000
2017-06-07T18:47:43.074493+00:00 app[web.1]: [bf12f03a-e321-453a-bf3b-5e8fed179477] Processing by UsersController#signin as */*
2017-06-07T18:47:43.074582+00:00 app[web.1]: [bf12f03a-e321-453a-bf3b-5e8fed179477]   Parameters: {"credentials"=>{"email"=>"angie@email.com", "password"=>"[FILTERED]"}, "submit"=>"Sign-In"}
2017-06-07T18:47:43.076959+00:00 app[web.1]: [bf12f03a-e321-453a-bf3b-5e8fed179477]   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "angie@email.com"], ["LIMIT", 1]]
2017-06-07T18:47:43.079763+00:00 app[web.1]: [bf12f03a-e321-453a-bf3b-5e8fed179477]   SQL (1.4ms)  UPDATE "users" SET "token" = 'a3593067868be240ab08f435395929ec', "updated_at" = '2017-06-07 18:47:43.077677' WHERE "users"."id" = $1  [["id", 1]]
2017-06-07T18:47:43.156468+00:00 app[web.1]: [bf12f03a-e321-453a-bf3b-5e8fed179477] [active_model_serializers] Rendered UserLoginSerializer with ActiveModelSerializers::Adapter::Json (0.27ms)
2017-06-07T18:47:43.156888+00:00 app[web.1]: [bf12f03a-e321-453a-bf3b-5e8fed179477] Completed 200 OK in 82ms (Views: 0.9ms | ActiveRecord: 2.1ms)
2017-06-07T18:47:43.158151+00:00 heroku[router]: at=info method=POST path="/sign-in/" host=quiet-island-36585.herokuapp.com request_id=bf12f03a-e321-453a-bf3b-5e8fed179477 fwd="144.121.82.194" dyno=web.1 connect=0ms service=86ms status=200 bytes=762 protocol=https
2017-06-07T18:47:44.535146+00:00 heroku[router]: at=info method=OPTIONS path="/quotes/" host=quiet-island-36585.herokuapp.com request_id=b5d1a037-91ff-41d3-af2a-6b99ff198c45 fwd="144.121.82.194" dyno=web.1 connect=1ms service=2ms status=200 bytes=350 protocol=https
2017-06-07T18:47:44.564342+00:00 heroku[router]: at=info method=GET path="/quotes/" host=quiet-island-36585.herokuapp.com request_id=86302fd9-6b4e-4289-a8d7-8bde9a638475 fwd="144.121.82.194" dyno=web.1 connect=0ms service=9ms status=500 bytes=465 protocol=https
2017-06-07T18:47:44.555953+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475] Started GET "/quotes/" for 144.121.82.194 at 2017-06-07 18:47:44 +0000
2017-06-07T18:47:44.556796+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475] Processing by QuotesController#index as */*
2017-06-07T18:47:44.559303+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475]   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "a3593067868be240ab08f435395929ec"], ["LIMIT", 1]]
2017-06-07T18:47:44.561873+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475]   Quote Load (0.9ms)  SELECT "quotes".* FROM "quotes"
2017-06-07T18:47:44.562102+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475] Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.7ms)
2017-06-07T18:47:44.563258+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475]   
2017-06-07T18:47:44.563307+00:00 app[web.1]: LINE 1: SELECT "quotes".* FROM "quotes"
2017-06-07T18:47:44.563308+00:00 app[web.1]:                                ^
2017-06-07T18:47:44.563308+00:00 app[web.1]: : SELECT "quotes".* FROM "quotes"):
2017-06-07T18:47:44.563348+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475]   
2017-06-07T18:47:44.563389+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475] app/controllers/quotes_controller.rb:9:in `index'
2017-06-07T18:47:44.563305+00:00 app[web.1]: [86302fd9-6b4e-4289-a8d7-8bde9a638475] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "quotes" does not exist
2017-06-07T18:54:35.694046+00:00 heroku[router]: at=info method=POST path="/sign-in/" host=quiet-island-36585.herokuapp.com request_id=e1363b28-7594-4cff-9ae7-20ce517af046 fwd="144.121.82.194" dyno=web.1 connect=0ms service=117ms status=200 bytes=762 protocol=https
2017-06-07T18:54:35.577630+00:00 app[web.1]: [e1363b28-7594-4cff-9ae7-20ce517af046] Started POST "/sign-in/" for 144.121.82.194 at 2017-06-07 18:54:35 +0000
2017-06-07T18:54:35.578525+00:00 app[web.1]: [e1363b28-7594-4cff-9ae7-20ce517af046] Processing by UsersController#signin as */*
2017-06-07T18:54:35.580721+00:00 app[web.1]: [e1363b28-7594-4cff-9ae7-20ce517af046]   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "angie@email.com"], ["LIMIT", 1]]
2017-06-07T18:54:35.578573+00:00 app[web.1]: [e1363b28-7594-4cff-9ae7-20ce517af046]   Parameters: {"credentials"=>{"email"=>"angie@email.com", "password"=>"[FILTERED]"}, "submit"=>"Sign-In"}
2017-06-07T18:54:35.590777+00:00 app[web.1]: [e1363b28-7594-4cff-9ae7-20ce517af046]   SQL (8.7ms)  UPDATE "users" SET "token" = 'bef720472be3a82dc9f4280f5d9f1546', "updated_at" = '2017-06-07 18:54:35.581250' WHERE "users"."id" = $1  [["id", 1]]
2017-06-07T18:54:35.692534+00:00 app[web.1]: [e1363b28-7594-4cff-9ae7-20ce517af046] [active_model_serializers] Rendered UserLoginSerializer with ActiveModelSerializers::Adapter::Json (0.43ms)
2017-06-07T18:54:35.692838+00:00 app[web.1]: [e1363b28-7594-4cff-9ae7-20ce517af046] Completed 200 OK in 114ms (Views: 1.1ms | ActiveRecord: 9.4ms)
2017-06-07T18:54:37.026411+00:00 heroku[router]: at=info method=GET path="/quotes/" host=quiet-island-36585.herokuapp.com request_id=c6f82109-8dd9-47bf-b40a-6f831dc2adcf fwd="144.121.82.194" dyno=web.1 connect=1ms service=7ms status=500 bytes=465 protocol=https
2017-06-07T18:54:37.000155+00:00 heroku[router]: at=info method=OPTIONS path="/quotes/" host=quiet-island-36585.herokuapp.com request_id=02454743-10dc-4295-af5c-60c686a998a4 fwd="144.121.82.194" dyno=web.1 connect=0ms service=1ms status=200 bytes=350 protocol=https
2017-06-07T18:54:37.020451+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf] Started GET "/quotes/" for 144.121.82.194 at 2017-06-07 18:54:37 +0000
2017-06-07T18:54:37.021267+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf] Processing by QuotesController#index as */*
2017-06-07T18:54:37.023150+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf]   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "bef720472be3a82dc9f4280f5d9f1546"], ["LIMIT", 1]]
2017-06-07T18:54:37.024865+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf]   Quote Load (0.7ms)  SELECT "quotes".* FROM "quotes"
2017-06-07T18:54:37.025028+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf] Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.3ms)
2017-06-07T18:54:37.025639+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf]   
2017-06-07T18:54:37.025664+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "quotes" does not exist
2017-06-07T18:54:37.025665+00:00 app[web.1]: LINE 1: SELECT "quotes".* FROM "quotes"
2017-06-07T18:54:37.025665+00:00 app[web.1]:                                ^
2017-06-07T18:54:37.025666+00:00 app[web.1]: : SELECT "quotes".* FROM "quotes"):
2017-06-07T18:54:37.025681+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf]   
2017-06-07T18:54:37.025701+00:00 app[web.1]: [c6f82109-8dd9-47bf-b40a-6f831dc2adcf] app/controllers/quotes_controller.rb:9:in `index'
2017-06-07T18:55:46.529074+00:00 heroku[router]: at=info method=OPTIONS path="/quotes/" host=quiet-island-36585.herokuapp.com request_id=3fa170f0-93a5-4080-a95d-86fafc23d003 fwd="144.121.82.194" dyno=web.1 connect=1ms service=1ms status=200 bytes=350 protocol=https
2017-06-07T18:55:46.561596+00:00 heroku[router]: at=info method=POST path="/quotes/" host=quiet-island-36585.herokuapp.com request_id=aa5713a6-48b8-4cf6-a961-003da0cceb35 fwd="144.121.82.194" dyno=web.1 connect=1ms service=10ms status=500 bytes=465 protocol=https
2017-06-07T18:55:46.550463+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35] Started POST "/quotes/" for 144.121.82.194 at 2017-06-07 18:55:46 +0000
2017-06-07T18:55:46.551521+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35]   Parameters: {"quote"=>{"quote_text"=>" Something hysterical", "date"=>"2017-06-07"}, "submit"=>"Publish Quote"}
2017-06-07T18:55:46.553904+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35]   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "bef720472be3a82dc9f4280f5d9f1546"], ["LIMIT", 1]]
2017-06-07T18:55:46.551464+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35] Processing by QuotesController#create as */*
2017-06-07T18:55:46.556545+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35] Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.5ms)
2017-06-07T18:55:46.557294+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "quotes" does not exist
2017-06-07T18:55:46.557233+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35]   
2017-06-07T18:55:46.557294+00:00 app[web.1]: LINE 8:                WHERE a.attrelid = '"quotes"'::regclass
2017-06-07T18:55:46.557296+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2017-06-07T18:55:46.557295+00:00 app[web.1]:                                           ^
2017-06-07T18:55:46.557296+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
2017-06-07T18:55:46.557297+00:00 app[web.1]:                WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation),
2017-06-07T18:55:46.557298+00:00 app[web.1]:                      col_description(a.attrelid, a.attnum) AS comment
2017-06-07T18:55:46.557297+00:00 app[web.1]:              (SELECT c.collname FROM pg_collation c, pg_type t
2017-06-07T18:55:46.557298+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2017-06-07T18:55:46.557299+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2017-06-07T18:55:46.557299+00:00 app[web.1]:                WHERE a.attrelid = '"quotes"'::regclass
2017-06-07T18:55:46.557299+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2017-06-07T18:55:46.557301+00:00 app[web.1]: ):
2017-06-07T18:55:46.557330+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35]   
2017-06-07T18:55:46.557300+00:00 app[web.1]:                ORDER BY a.attnum
2017-06-07T18:55:46.557370+00:00 app[web.1]: [aa5713a6-48b8-4cf6-a961-003da0cceb35] app/controllers/quotes_controller.rb:23:in `create'
```

**Comment by BenGitsCode** [comment]
Did you run migrate in the heroku app? it looks like the quotes table doesn't exist in heroku yet.

**Comment by awoodrum87** [comment]
I thought about that right as your comment appeared. doing it now will report back

**Comment by awoodrum87** [comment]
that was it. :)
thanks!

**Comment by BenGitsCode** [comment]
🎉
