### ISSUE TITLE
NoDatabaseError in server

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/capstone-project#661]
Nothing is hitting my server and Im getting this error?
```
ActiveRecord::NoDatabaseError (FATAL:  database "capstone-server_development" does not exist
):
```

**Comment by benjimelito** [comment]
Have you confirmed that the database does indeed exist by using the `psql` console?

**Comment by tvcrawley** [comment]
@eliottenos update?

**Comment by eliottenos** [comment]
@tvlangley Trying to locate in psql console but --list isnt showing anything?

**Comment by benjimelito** [comment]
I would try creating it in psql using the CREATE DATABASE command. I have a feeling it won't like that you use a '-' in the name of your database - if this is the case you may need to rename it in your config file and call it something else. Let me know if you're having trouble with this and I can swing by.

**Comment by eliottenos** [comment]
@benjimelito yeah may need a quick push in right direction...

**Comment by eliottenos** [comment]
created new database with
```
create database capstone_developement
```

working fine now

**Comment by eliottenos** [comment]
reopened as Im still getting thissweet error
```
Started POST "/sign-up" for 127.0.0.1 at 2017-06-13 14:07:08 -0400
  
ActiveRecord::NoDatabaseError (FATAL:  database "capstone_development" does not exist
):
  
activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `rescue in connect'
activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
activerecord (5.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.1) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.1) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.1) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.1) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Im getting a 500 in the console and the above in server when trying to sign up

**Comment by benjimelito** [comment]
Did you check to see if it does exist in `psql`? If not, can you simply create it again?

**Comment by eliottenos** [comment]
ah, looks like I created
```capstone_developement ``` instead of ```capstone_development```
