### ISSUE TITLE
this.get('store').find('userCoin', 1), returning 404. 

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/capstone-project#673]
I'm trying to use ember data to build a local store of user objects and for somer reason i'm getting a 404 whenever I try to console log the store to see if it's working. 

```
ember.debug.js:16905 Ember Data Request GET http://localhost:4741/user_coins/1 returned a 404
Payload (application/json; charset=utf-8)
[object Object]
Error
    at ErrorClass.AdapterError (http://localhost:7165/assets/vendor.js:88496:16)
    at ErrorClass (http://localhost:7165/assets/vendor.js:88521:24)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:89799:20)
    at Class.handleResponse (http://localhost:7165/assets/vendor.js:73690:28)
    at Class.superWrapper [as handleResponse] (http://localhost:7165/assets/vendor.js:50205:22)
    at ajaxError (http://localhost:7165/assets/vendor.js:90169:25)
    at Class.hash.error (http://localhost:7165/assets/vendor.js:89838:23)
    at fire (http://localhost:7165/assets/vendor.js:3632:31)
    at Object.fireWith [as rejectWith] (http://localhost:7165/assets/vendor.js:3762:7)
    at done (http://localhost:7165/assets/vendor.js:9589:14)

```
Above  tried to console log a specific item, but this is also happening when I try with a findAll request. I think it's because the url is saying /user_coins, but my chrome Ember console says the route should be /userCoins. I don't know where to change this.

**Comment by cpearce31** [comment]
Can we see the code where you call the console.log?

**Comment by jordanallain** [comment]
okay this sounds like multiple problems you are talking about. your 404 error wouldn't come from console.logging anything, it comes from a request to your API. looks like [object Object] is your console log.

as for the route being snake case, why don't you search in your project to find anywhere it might exist.

**Comment by MicFin** [comment]
Also sharing your `router.js` might be useful.

**Comment by Anddrew914** [comment]
I think it's because my console log was trying to access the server incorrectly. Using peek resolved it, I'm not totally out of the weeds right now but this issue as it stands is no longer useful. I'll probably be back soon with a new problem!

**Comment by BenGitsCode** [comment]
New problems mean progress 🎉
