### ISSUE TITLE
Delete Request by name attribute

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/capstone-project#694]
I'm trying to delete a location by it's attribute name rather than id.
I've attached got a button in an each handlebar attached to each location.
When clicked Im not hitting the function or event listener by the looks of it and have console logged all over the place but not getting any data back.  Any idea why its not hitting it?
```html
{{#each locations as |location|}}
<p>
 {{ location.country }}
<p>
<p>
  {{ location.note }}
</p>
<button id="delete-{{ location.id }}" type="button" class="btn btn-secondary btn-lg btn-block delete-location">Delete Location</button>
<button id="update-{{ location.country }}" type="button" class="btn btn-secondary btn-lg btn-block">Update Location</button>
{{/each}}
```
```js
const addHandlers = () => {
  $('.content-div2').on('submit', '#location-create', onCreateLocation)
  $('.getBlank1').on('click', '.delete-location', onDeleteLocation)
  $('.content-div2').on('click', '#location-get', onGetAllLocations)
}

const onDeleteLocation = function (event) {
  // event.preventDefault()
  // const place = event.target
  const index = event.target.id.indexOf('-')
  const deleteLocation = event.target.id.slice(index + 1)
  console.log('id here', deleteLocation)
    api.deleteLocation(deleteLocation)
    .then(ui.deleteLocationSuccess)
    .catch(ui.deleteLocationFailure)
  // } else {
  //   console.log('Please provide a location id!')
}
```
```js
const deleteLocation = (data) => {
  console.log('delete is here', data)
  return $.ajax({
    url: config.apiOrigin + '/destroy-place/' + data,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: data
  })
}
```

**Comment by eliottenos** [comment]
I've changed the div to .getBlank1 which is now hitting the function and the object is getting the correct id but Im getting a 500 error on the server
```
Started DELETE "/destroy-place/1" for 127.0.0.1 at 2017-06-15 17:59:07 -0400
Processing by PlacesController#destroy as */*
  Parameters: {"1"=>nil, "id"=>"1"}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "e4ea584eacbdcecce3cb49b36c86979a"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 1254ms (ActiveRecord: 0.6ms)


  
NoMethodError (undefined method `place' for #<User:0x007f87ab7cd5f0>
Did you mean?  places
               places=):
  
app/controllers/places_controller.rb:51:in `set_place'
```

**Comment by eliottenos** [comment]
its pointing to this in my places controller which seems right?
```rb
def set_place
      validate_user
      @place = current_user.place.find(params[:id])
    end
```

**Comment by cpearce31** [comment]
If you're selecting a place by ID, you shouldn't need any reference to the current user to find it right? Did you try just Place.find(params[:id])?

**Comment by eliottenos** [comment]
hmmm...different error which is good when thats changed
```rb
Started DELETE "/destroy-place/1" for 127.0.0.1 at 2017-06-15 18:55:12 -0400
Processing by PlacesController#destroy as */*
  Parameters: {"1"=>nil, "id"=>"1"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "dd824afbd09ec3bcc17fd83309aa6054"], ["LIMIT", 1]]
  Place Load (0.4ms)  SELECT  "places".* FROM "places" WHERE "places"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "dd824afbd09ec3bcc17fd83309aa6054"], ["LIMIT", 1]]
   (0.2ms)  BEGIN
  SQL (0.6ms)  DELETE FROM "places" WHERE "places"."id" = $1  [["id", 1]]
   (27.4ms)  COMMIT
Completed 500 Internal Server Error in 154ms (ActiveRecord: 29.2ms)


  
NoMethodError (undefined method `destroy' for nil:NilClass):
  
app/controllers/places_controller.rb:39:in `destroy'
```

**Comment by eliottenos** [comment]
success!

**Comment by eliottenos** [comment]
changed as you said to
```rb
def set_place
      validate_user
      @place = Place.find(params[:id])
    end
```
and error in destroy method as was looking for location rather than place

**Comment by MicFin** [comment]
@elliottcarlson 
But now you are no longer ensuring a User owns the Place in order to delete it.  Your application is vulnerable to curl scripts that will delete other Users' Places.

I believe the issue here is that your relationship is User `has_many` Places and you were trying to do `current_user.place.find` instead of `current_user.places.find`. 
```rb
def set_place
      validate_user
      @place = current_user.place.find(params[:id]) 
      # singular place is not correct for has_many
end
```

**Comment by MicFin** [comment]
Additionally, what controller is your `PlacesController` inheriting from?  Protected, OpenRead or Application?

**Comment by eliottenos** [comment]
this is places controller
```rb
class PlacesController < ApplicationController
```
@MicFin

**Comment by eliottenos** [comment]
Sorted, works with current_set.place.find(params[:id])
