### ISSUE TITLE
Pending Migration, running a migration aborts

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/capstone-project#737]
Maybe not the best idea, but I can a ```bin/rake db:drop db:create db:migrate``` to try and reset the index number on a table.  Localhost:4741 shows a 500 error pending migration.  Suggests to run ```bin/rails db:migrate RAILS_ENV=development```, but this results in an abort.  
```
$ bin/rails db:migrate RAILS_ENV=development
== 1 CreateUsers: migrating ===================================================
-- create_table(:users, {})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "hikes" does not exist
: CREATE TABLE "users" ("id" serial primary key, "email" character varying NOT NULL, "token" character varying NOT NULL, "password_digest" character varying NOT NULL, "hike_id" integer, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_c8e738d291"
FOREIGN KEY ("hike_id")
  REFERENCES "hikes" ("id")
)
/home/rory/wdi/capstone/back-end/db/migrate/001_create_users.rb:4:in `change'
/home/rory/wdi/capstone/back-end/bin/rails:9:in `require'
/home/rory/wdi/capstone/back-end/bin/rails:9:in `<top (required)>'
/home/rory/wdi/capstone/back-end/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "hikes" does not exist
: CREATE TABLE "users" ("id" serial primary key, "email" character varying NOT NULL, "token" character varying NOT NULL, "password_digest" character varying NOT NULL, "hike_id" integer, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_c8e738d291"
FOREIGN KEY ("hike_id")
  REFERENCES "hikes" ("id")
)
/home/rory/wdi/capstone/back-end/db/migrate/001_create_users.rb:4:in `change'
/home/rory/wdi/capstone/back-end/bin/rails:9:in `require'
/home/rory/wdi/capstone/back-end/bin/rails:9:in `<top (required)>'
/home/rory/wdi/capstone/back-end/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
PG::UndefinedTable: ERROR:  relation "hikes" does not exist
/home/rory/wdi/capstone/back-end/db/migrate/001_create_users.rb:4:in `change'
/home/rory/wdi/capstone/back-end/bin/rails:9:in `require'
/home/rory/wdi/capstone/back-end/bin/rails:9:in `<top (required)>'
/home/rory/wdi/capstone/back-end/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
~/wdi/capstone/back-end (scaffold)
$ 
```

**Comment by tvcrawley** [comment]
How are users and hikes associated?

**Comment by RoryEnright** [comment]
Models:
```
class User < ApplicationRecord
  include Authentication
  has_many :mountains, through: :hikes
  has_many :hikes
end

class Mountain < ApplicationRecord
  has_many :users, through: :hikes
  has_many :hikes
end

class Hike < ApplicationRecord
  belongs_to :user, inverse_of: :hikes
  belongs_to :mountain, inverse_of: :hikes
end
```

**Comment by RoryEnright** [comment]
Schema:
```
ActiveRecord::Schema.define(version: 20170718140918) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "examples", force: :cascade do |t|
    t.text     "text",       null: false
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_examples_on_user_id", using: :btree
  end

  create_table "hikes", force: :cascade do |t|
    t.date     "when"
    t.string   "trail"
    t.integer  "duration"
    t.text     "note"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
    t.integer  "user_id"
    t.integer  "mountain_id"
    t.index ["mountain_id"], name: "index_hikes_on_mountain_id", using: :btree
    t.index ["user_id"], name: "index_hikes_on_user_id", using: :btree
  end

  create_table "mountains", force: :cascade do |t|
    t.text     "name"
    t.integer  "height"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.index ["email"], name: "index_users_on_email", unique: true, using: :btree
    t.index ["token"], name: "index_users_on_token", unique: true, using: :btree
  end

  add_foreign_key "examples", "users"
  add_foreign_key "hikes", "mountains"
  add_foreign_key "hikes", "users"
end
```

**Comment by tvcrawley** [comment]
Can you post the create users migration file?

**Comment by RoryEnright** [comment]
```
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :email, null: false, index: { unique: true }
      t.string :token, null: false, index: { unique: true }
      t.string :password_digest, null: false
      t.references :hike, foreign_key: true

      t.timestamps null: false
    end
  end
end
```

**Comment by RoryEnright** [comment]
Maybe I should remove ```t.references :hike, foreign_key: true```, run the migration and then make a new migration to add user to hike?

**Comment by tvcrawley** [comment]
Sounds like a good plan. Currently, users is creating a relation to a table that doesn't currently exist.

**Comment by RoryEnright** [comment]
Worked!  Schema looks the same as before, also fixed the original problem of IDs being far out from the seeding process.  Thanks!
