### ISSUE TITLE
POST action via curl script on Rails backend throws errors

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/capstone-project#738]
Hi, friends -- 

I have set up a resource, `shows` and linked it to `users` (with a foreign key relationship; the `shows` table has a `user_id` column). Once I had these set up, I wrote a curl script to test if I could create a new show record.  First, I will show you the curl script, then the error messages, then the code from my models and controller. 

Curl script: 

```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/shows"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=0025a0f21fe89136c9da97f7793d9976" \
  --data '{
    "show": {
      "show_name": "'Bark and Byte: Digital Tree Bark Art'"
      "show_date": "'2017-11-22'"
      "show_time": "'19:30'"
      "notes": "'This was a great show. Fabulous tree bark textures.'"
    }
  }'

```
Error message at command line: 
```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
X-Request-Id: 887b949d-1d60-477e-891e-2ed09a6d4847
X-Runtime: 0.234414
Vary: Origin
Content-Length: 9644

{"status":400,"error":"Bad Request","exception":"#\u003cActionDispatch::ParamsParser::ParseError: 822: unexpected token at '{\n    \"show\": {\n      \"show_name\": \"First'\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_dispatch/http/parameters.rb:78:in `rescue in parse_formatted_parameters'"},{"id":1,"trace":"actionpack (5.0.1) lib/action_dispatch/http/parameters.rb:72:in `parse_formatted_parameters'"},
```
This error message is extremely long, but I've kept it at the command line. 

Rails server also shows errors: 
```
Started POST "/shows" for 127.0.0.1 at 2017-07-18 15:13:28 -0400
Error occurred while parsing request parameters.
Contents:

{
    "show": {
      "show_name": "Bark
  
ActionDispatch::ParamsParser::ParseError (822: unexpected token at '{
    "show": {
      "show_name": "Bark'):
  
actionpack (5.0.1) lib/action_dispatch/http/parameters.rb:78:in `rescue in parse_formatted_parameters'
actionpack (5.0.1) lib/action_dispatch/http/parameters.rb:72:in `parse_formatted_parameters'
actionpack (5.0.1) lib/action_dispatch/http/request.rb:354:in `block in POST'
rack (2.0.1) lib/rack/request.rb:57:in `fetch'
rack (2.0.1) lib/rack/request.rb:57:in `fetch_header'
actionpack (5.0.1) lib/action_dispatch/http/request.rb:353:in `POST'
```
This error message is also very long, but I've kept both error messages open in tabs in Terminal if you'd like to see more. 

Here are my models: 

models/user.rb: 

```
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :shows
end
```
models/show.rb: 

```
class Show < ApplicationRecord
  belongs_to :user
end

```
And for good measure, the schema: 

```
  create_table "shows", force: :cascade do |t|
    t.string   "show_name"
    t.date     "show_date"
    t.time     "show_time"
    t.text     "notes"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
    t.index ["user_id"], name: "index_shows_on_user_id", using: :btree
  end
```
and config/routes.rb: 

```
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :shows
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

**Comment by lisawilliams** [comment]
Here's the relevant feature branch for browsing purposes: https://github.com/lisawilliams/gesso-api/tree/issue%234b

**Comment by jordanallain** [comment]
looks like you're missing some commas maybe?

**Comment by tvcrawley** [comment]
☝️ 
Looks like the curl script is failing. _Bad request usually means the data isn't structured in a way the api expects._

**Comment by lisawilliams** [comment]
Thanks, friends! I will get ☕️ and investigate further and report back.

**Comment by lisawilliams** [comment]
**BREAKING NEWS**

I edited the curl script as follows and got EXCITING AND NEW ERROR MESSAGES: 

```
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/shows"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=0025a0f21fe89136c9da97f7793d9976" \
  --data '{
    "show": {
      "show_name": "Bark and Byte: Digital Tree Bark Art",
      "show_date": "2017-11-22",
      "show_time": "19:30",
      "notes": "This was a great show. Fabulous tree bark textures."
    }
  }'

echo

```
And the error from Rails server: 

``` 
Started POST "/shows" for 127.0.0.1 at 2017-07-18 15:42:31 -0400
Processing by ShowsController#create as */*
  Parameters: {"show"=>{"show_name"=>"Bark and Byte: Digital Tree Bark Art", "show_date"=>"2017-11-22", "show_time"=>"19:30", "notes"=>"This was a great show. Fabulous tree bark textures."}}
Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.0ms)


  
NoMethodError (undefined method `shows' for nil:NilClass):
  
app/controllers/shows_controller.rb:19:in `create'
```
I am now gazing contemplatively at /controllers/shows_controller.rb, which has the following: 

``` 
  # POST /shows
  def create
    @show = current_user.shows.build(show_params)

    if @show.save
      render json: @show, status: :created, location: @show
    else
      render json: @show.errors, status: :unprocessable_entity
    end
  end
```

**Comment by tvcrawley** [comment]
What controller are you inheriting from?

**Comment by lisawilliams** [comment]
HMMMMM I suspect we are on to something, Toni...

``` 
class ShowsController < ApplicationController
  # before_action :set_show, only: [:show, :update, :destroy]
```
My full stack project, which, you know, kind of works and everything, reads as follows....hmmm.....

```
class ChoresController < OpenReadController
```

**Comment by tvcrawley** [comment]
Reference Mike's response at the end of [this issue](https://github.com/ga-wdi-boston/full-stack-project/issues/814)

**Comment by lisawilliams** [comment]
@tvlangley That makes it look as if OpenReadController is definitely the right thing to be using as it inherits other controllers that do things that we need. However! That alone did not fix it, but did get us to a new state with new and intriguing errors: 

From the command line, where I ran the curl script: 

``` 
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Request-Id: aa6a6947-bdd1-4163-8745-eb6ef49da45b
X-Runtime: 0.040426
Vary: Origin
Content-Length: 8985

{"status":500,"error":"Internal Server Error","exception":"#\u003cLoadError: Unable to autoload constant ShowsController, expected /Users/lisawilliams/wdi/projects/gesso-project/gesso-api/app/controllers/shows_controller.rb to define it\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"activesupport (5.0.1) lib/active_support/dependencies.rb:512:in `load_missing_constant'"},

```

From rails server: 

```
Started POST "/shows" for 127.0.0.1 at 2017-07-18 15:59:22 -0400
  
LoadError (Unable to autoload constant ShowsController, expected /Users/lisawilliams/wdi/projects/gesso-project/gesso-api/app/controllers/shows_controller.rb to define it):
  
activesupport (5.0.1) lib/active_support/dependencies.rb:512:in `load_missing_constant'
activesupport (5.0.1) lib/active_support/dependencies.rb:203:in `const_missing'
activesupport (5.0.1) lib/active_support/inflector/methods.rb:268:in `const_get'
activesupport (5.0.1) lib/active_support/inflector/methods.rb:268:in `block in constantize'
activesupport (5.0.1) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.1) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.1) lib/active_support/inflector/methods.rb:266:in `constantize'
activesupport (5.0.1) lib/active_support/dependencies.rb:583:in `get'
activesupport (5.0.1) lib/active_support/dependencies.rb:614:in `constantize'
actionpack (5.0.1) lib/action_dispatch/http/request.rb:81:in `controller_class'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:44:in `controller'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:30:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'

```
Both of these error messages are quite long, and are abbreviated here.  Just to be sure rails server was picking up changes, I rebooted it and tried again, using a fresh token from a freshly signed in user -- but no luck there, same response.

**Comment by tvcrawley** [comment]
Can you post the entire `ShowsController`?

**Comment by lisawilliams** [comment]
Hang on I think I found something!!

**Comment by lisawilliams** [comment]
I realized it still said 'Chores' where it should say 'Shows' in one critical location...hang on I am going to test a few things...

**Comment by lisawilliams** [comment]
Gawd, this is like one of those mysteries with 8 million twists *chuckle*.  Okay, first I signed in a user, which returned the following from the server: 

``` 
Started POST "/sign-in" for 127.0.0.1 at 2017-07-18 16:12:45 -0400
Processing by UsersController#signin as */*
  Parameters: {"credentials"=>{"email"=>"squirrel@tree.com", "password"=>"[FILTERED]"}, "submit"=>"Log In"}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "squirrel@tree.com"], ["LIMIT", 1]]
  SQL (2.3ms)  UPDATE "users" SET "token" = 'f75f6f073d8a9c482ae6c2dfd5da9081', "updated_at" = '2017-07-18 20:12:46.023205' WHERE "users"."id" = $1  [["id", 2]]
[active_model_serializers] Rendered UserLoginSerializer with ActiveModelSerializers::Adapter::Json (1.91ms)
Completed 200 OK in 131ms (Views: 11.8ms | ActiveRecord: 3.3ms)
```
So, looks good.  I take the token above and put it in the curl script, like so: 

``` 
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/shows"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=f75f6f073d8a9c482ae6c2dfd5da9081" \
  --data '{
    "show": {
      "show_name": "Bark and Byte: Digital Tree Bark Art",
      "show_date": "2017-11-22",
      "show_time": "19:30",
      "notes": "This was a great show. Fabulous tree bark textures."
    }
  }'

```
And I get the following error messages: 

At the command line: 

``` 
HTTP/1.1 401 Unauthorized
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
X-Request-Id: e7611480-ccf0-4574-8cd7-7a63c82207f6
X-Runtime: 0.011146
Vary: Origin
Transfer-Encoding: chunked

HTTP Token: Access denied.
```
And from the server: 

``` 
Started POST "/shows" for 127.0.0.1 at 2017-07-18 16:13:27 -0400
Processing by ShowsController#create as */*
  Parameters: {"show"=>{"show_name"=>"Bark and Byte: Digital Tree Bark Art", "show_date"=>"2017-11-22", "show_time"=>"19:30", "notes"=>"This was a great show. Fabulous tree bark textures."}}
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "f"], ["LIMIT", 1]]
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 4ms (Views: 0.2ms | ActiveRecord: 0.9ms)

``` 

And for reference, here's controllers/shows_controller.rb: 

``` 
# class ShowsController < ApplicationController
  # before_action :set_show, only: [:show, :update, :destroy]
class ShowsController < OpenReadController
  before_action :set_show, only: [:update, :destroy]

  # GET /shows
  def index
    @shows = current_user.shows
    render json: @shows
  end

  # GET /shows/1
  def show
    render json: @show
  end

  # POST /shows
  def create
    @show = current_user.shows.build(show_params)

    if @show.save
      render json: @show, status: :created, location: @show
    else
      render json: @show.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /shows/1
  def update
    if @show.update(show_params)
      render json: @show
    else
      render json: @show.errors, status: :unprocessable_entity
    end
  end

  # DELETE /shows/1
  def destroy
    @show.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = current_user.shows.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def show_params
      params.require(:show).permit(:show_name, :show_date, :show_time, :notes)
    end
end
```

I feel like we're so close!

**Comment by lisawilliams** [comment]
Hm. I am just stumped about this one. There's clearly something going on around the token, but I'm not sure what.

**Comment by lisawilliams** [comment]
*developer rushes to the shoreline, where she sees a usb stick in a bottle with a cork in it*

Dear future developer: if you are writing curl scripts that depend on tokens generated when a user signs in to authorize CRUD actions, *don't use what you see from Rails Server.* Here's why: Rails Server shows you a truncated/shortened version of the token: 

```
Started POST "/sign-in" for 127.0.0.1 at 2017-07-18 16:35:39 -0400
Processing by UsersController#signin as */*
  Parameters: {"credentials"=>{"email"=>"cup@saucer.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "cup@saucer.com"], ["LIMIT", 1]]
  SQL (5.4ms)  UPDATE "users" SET "token" = '5706c902edc7cf1562eb1a94ec672668', "updated_at" = '2017-07-18 20:35:39.545677' WHERE "users"."id" = $1  [["id", 4]]
[active_model_serializers] Rendered UserLoginSerializer with ActiveModelSerializers::Adapter::Json (0.37ms)
Completed 200 OK in 113ms (Views: 0.9ms | ActiveRecord: 6.0ms)
```
But! if you run the curl script at the command line, or console log it so you can see it in your browser console, you will see that it is actually much longer: 

```
~/wdi/projects/gesso-project/gesso-api/scripts (issue#4b)
$ EMAIL=cup@saucer.com PASSWORD=333 sh sign-in.sh
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"46b7ea41e135a6459c73f21708f1c5bd"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 6cc6b74d-3db7-4881-976c-6242347a2221
X-Runtime: 0.115973
Vary: Origin
Transfer-Encoding: chunked

{"user":{"id":4,"email":"cup@saucer.com","token":"BAhJIiU1NzA2YzkwMmVkYzdjZjE1NjJlYjFhOTRlYzY3MjY2OAY6BkVG--3d6cc8ddd358efddeea673805508e116e7c7dd65"}}
```
See how much longer the token really is? In fact, it actually leaves the screen of this comment box; it's longer than you can see here. The API won't authenticate your action without the full token. 

My advice? Console log the @$#! out of everything :D Just remember to take it out before you submit your project for evaluation. Grab the tokens from browser console. 

Thank you to @tvlangley for this insight.
