### ISSUE TITLE
heroku - attempt to seed heroku db aborted

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/capstone-project#773]
I am attempting to seed heroku with data that is properly seeded locally.

Ran this command:
heroku run rake db:seed

Received this response:
```
Running rake db:seed on ⬢ splice-api... up, run.3710 (Free)
  ActiveRecord::SchemaMigration Load (1.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
rake aborted!
CSV::MalformedCSVError: Unquoted fields do not allow \r or \n (line 82).
/app/db/seeds.rb:14:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:549:in `load_seed'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:268:in `load_seed'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```
Seeds file:
```rb
# frozen_string_literal: true
# This file should contain all the record creation needed to seed the database
# with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the
# db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
require 'csv'

csv_text = File.read(Rails.root.join('db', 'cards.csv'))
csv = CSV.parse(csv_text, :headers => true)
csv.each do |row|
  Card.create!(row.to_hash)
end

```

**Comment by artpylon** [comment]
I cannot update the csv here, but it can be downloaded (as a csv)here:
https://docs.google.com/spreadsheets/d/1e9FEer-k-9zQy5ozUzHObaozEdF9c5QZqdHV-CF070Y/edit?usp=sharing

**Comment by artpylon** [comment]
So I updated the seeds code and pushed that to heroku

```
require 'csv'

csv_text = File.read(Rails.root.join('public', 'cards.csv')).squish

csv = CSV.parse(csv_text, :headers => true)
csv.each do |row|
  Card.create!(row.to_hash)
end
```
then ran, 
 heroku run rake db:seed

and received this response
```
Running rake db:seed on ⬢ splice-api... up, run.7035 (Free)
  ActiveRecord::SchemaMigration Load (1.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
```

However, when i visit that route at my deployed api, there is nothing there:
https://splice-api.herokuapp.com/cards

**Comment by artpylon** [comment]
Confirmed through heroku console that there are 0 cards:
irb(main):002:0> Card.count
   (1.0ms)  SELECT COUNT(*) FROM "cards"
=> 0

**Comment by Jcornmanhomonoff** [comment]
Check your Heroku logs to see if you're getting any error messages in there that we can refer to for further help.

**Comment by artpylon** [comment]
logs:
```
2017-07-20T18:33:18.908095+00:00 heroku[web.1]: State changed from starting to up
2017-07-20T18:33:32.096908+00:00 heroku[run.3808]: Awaiting client
2017-07-20T18:33:32.121126+00:00 heroku[run.3808]: Starting process with command `bin/rake db:seed`
2017-07-20T18:33:32.367181+00:00 heroku[run.3808]: State changed from starting to up
2017-07-20T18:33:38.252978+00:00 heroku[run.3808]: Process exited with status 0
2017-07-20T18:33:38.265162+00:00 heroku[run.3808]: State changed from up to complete
2017-07-20T18:34:44.832528+00:00 app[web.1]: [32bbe14a-b122-4e81-9e37-72244e70600c] Started GET "/cards" for 144.121.82.194 at 2017-07-20 18:34:44 +0000
2017-07-20T18:34:44.835346+00:00 app[web.1]: [32bbe14a-b122-4e81-9e37-72244e70600c] Processing by CardsController#index as HTML
2017-07-20T18:34:44.869529+00:00 app[web.1]: [32bbe14a-b122-4e81-9e37-72244e70600c]   Card Load (1.5ms)  SELECT "cards".* FROM "cards"
2017-07-20T18:34:44.878863+00:00 app[web.1]: [32bbe14a-b122-4e81-9e37-72244e70600c] [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (1.07ms)
2017-07-20T18:34:44.879189+00:00 app[web.1]: [32bbe14a-b122-4e81-9e37-72244e70600c] Completed 200 OK in 44ms (Views: 42.8ms | ActiveRecord: 15.4ms)
2017-07-20T18:34:44.879729+00:00 heroku[router]: at=info method=GET path="/cards" host=splice-api.herokuapp.com request_id=32bbe14a-b122-4e81-9e37-72244e70600c fwd="144.121.82.194" dyno=web.1 connect=0ms service=51ms status=304 bytes=326 protocol=https
2017-07-20T18:34:46.313303+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=splice-api.herokuapp.com request_id=4622dde8-456a-42a6-be9b-7806330f0483 fwd="144.121.82.194" dyno=web.1 connect=3ms service=2ms status=200 bytes=157 protocol=https
```

**Comment by artpylon** [comment]
redownloaded the file from gdocs, returned the script to its original state, and it worked!
```
require 'csv'

csv_text = File.read(Rails.root.join('public', 'cards_csv.csv'))
# csv_text = csv_text.squish
csv = CSV.parse(csv_text, :headers => true)

csv.each do |row|
  Card.create!(row.to_hash)
end
```
