### ISSUE TITLE
Read routines

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#820]
I'm having trouble reading a routine via curl scripts in the terminal.

terminal:
```rb
app/controllers/routines_controller.rb:52:in `set_routine'
Started GET "/routines" for 127.0.0.1 at 2017-08-28 15:11:01 -0400
Processing by RoutinesController#index as */*
  User Load (1.1ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "a7ad323a2ca9761b367fce29e6d90955"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.1ms)

  
NoMethodError (undefined method `routines' for nil:NilClass):
```

```
~/wdi/projects/strongerBackEnd (routine)
$ TOKEN=BAhJIiVhN2FkMzIzYTJjYTk3NjFiMzY3ZmNlMjllNmQ5MDk1NQY6BkVG--e6579137a6acfc1c90a82d42ab40ada3d531c10d sh scripts/get-routine.sh 
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Request-Id: 8f66b64e-7de9-4738-8a2c-967cafa62fdf
X-Runtime: 0.031400
Vary: Origin
Content-Length: 11595

{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `routines' for nil:NilClass\u003e","traces":{"Application Trace":[{"id":0,"trace":"app/controllers/routines_controller.rb:52:in `set_routine'"}],"Framework Trace":[{"id":1,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'"},{"id":2,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'"},{"id":3,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in \u003cmodule:Callbacks\u003e'"},
```

controller
```rb
class RoutinesController < OpenReadController
  before_action :set_routine, only: [:index, :show, :update, :destroy]

  # GET /routines
  def index
    binding.pry
    @routines = Routine.all

    render json: @routines

  end

  # GET /routines/1
  def show
    render json: Routine.find(params[:id])

  end

  # POST /routines
  def create
    @routine = current_user.routines.build(routine_params)


    if @routine.save
      render json: @routine, status: :created, location: @routine
    else
      render json: @routine.errors, status: :unprocessable_entity

    end
  end

  # PATCH/PUT /routines/1
  def update
    if @routine.update(routine_params)

      render json: @routine
    else
      render json: @routine.errors, status: :unprocessable_entity
    end
  end

  # DELETE /routines/1
  def destroy
    @routine.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_routine
      @routine = current_user.routines
    end

    # Only allow a trusted parameter "white list" through.
    def routine_params
      params.require(:routine).permit(:name, :exercise_id)
    end
end

```
I'm not sure how to define the undefined method `routines' for nil:NilClass
I'm not sure why the error eludes to something wrong with this:
```rb
    def set_routine
      @routine = current_user.routines
    end
```

I've used binding.pry on the index method (line 6) and have been struggling to figure out what is wrong. 
I can view all of the routines with this method using pry ``` @routines = Routine.all``` However, it fails when I try to run the curl script.

**Comment by scottyscripts** [comment]
take a look at how examples controller is using set_example. Are you sure you want to be setting a routine when you are trying to get an index???

**Comment by ryanwk** [comment]
I thought Routines.all was how you perform an index? 

I changed set_routine from lines (50 to 52), modeling after the examples controller:
```rb
    def set_routine
      @routine = current_user.routines.find(params[:id])
    end
```
still getting 500 error

**Comment by ryanwk** [comment]
tried removing :index from ```class RoutinesController < OpenReadController
  before_action :set_routine, only: [ :show, :update, :destroy]``` and got this error after running the index curl script:

```
app/controllers/routines_controller.rb:8:in `index'
Started GET "/routines" for 127.0.0.1 at 2017-08-28 15:52:29 -0400
Processing by RoutinesController#index as */*
  Routine Load (0.3ms)  SELECT "routines".* FROM "routines"
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (4.45ms)
Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.3ms)

  
NoMethodError (undefined method `date' for #<Routine:0x007fef77f952e0>
Did you mean?  update):
  
app/controllers/routines_controller.rb:8:in `index'
```
Earlier I had removed the date from the routine table as it was redundant. Properly migrated and the schema reflects the changes. Do you think this set_before thing and date are related?

I am able to index my routines in pry but when I try to run the curl script I get that strange error stemming from app/controllers/routines_controller.rb:8:in `index'

**Comment by payne-chris-r** [comment]
Is it still in your serializer?

**Comment by ryanwk** [comment]
Yes, just deleted it. Thanks Chris, let's see what happens.

**Comment by ryanwk** [comment]
that did the trick, thank you!

solution:
removed 'date' from routine serializer
