### ISSUE TITLE
save a created exercise (ember)

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#826]
I think I might be having trouble persisting data to my backend. I added a form to create an exercise in view that displays all exercises. The form seems to work properly (the new exercise gets added to the list), however, when I refresh the page I don't see the new exercise. 

Here's the component:
```
<form class=“form-container” {{action 'createExercise' on='submit' }}>
  <div class=“form-title”>Name</div>
    {{input placeholder='New Exercise Name'
      value=newExercise.name
    }}
    <div class=“form-title”>Weight</div>
    {{input placeholder='New Exercise Weight'
      value=newExercise.weight
    }}
    <div class=“submit-container”>
<button class=“submit-button” type=“submit” value=“Submit” >Save</button>
</div>
  </form>
```
exercises.hbs
```js
{{exercise-create-form exercise=exercise createExercise='createExercise'}}
```
routes:
```js
Router.map(function () {
  this.route('sign-up');
  this.route('sign-in');
  this.route('change-password');
  this.route('users');
  this.route('exercises');
  // this.route('exercise', { path: '/exercises/:exercise_id'});
});
```
exercises.js route
```js
import Ember from 'ember';

export default Ember.Route.extend({
  model () {
    return this.get('store').findAll('exercise');
  },
  actions: {
    createExercise (exercise) {
      let newExercise = this.get('store').createRecord('exercise', exercise);
        newExercise.save()
        .then(() => {
          this.get('flashMessages').warning('Exercise Added')
        })
    }
    // update () { ... },
    // destroy () { ... },
  }
});
```

am I missing anything? Why don't newly created exercises remain on the exercise list after refresh, sign in/out, etc? 

The larger issue here stems from my inability understand the layers of Ember or how everything comes together. I've thoroughly reviewed all of our lessons on Ember and have read through the documentation here:
https://guides.emberjs.com/v2.4.0/models/creating-updating-and-deleting-records/
https://git.generalassemb.ly/ga-wdi-boston/ember-routing
https://git.generalassemb.ly/ga-wdi-boston/ember-components
https://git.generalassemb.ly/ga-wdi-boston/ember-resources

**Comment by scottyscripts** [comment]
Is your .then function after saving a new exercise getting fired off?

**Comment by ryanwk** [comment]
Yeah, I can see the flash message informing me that the exercise was created. I also get a successful POST request in the console.

**Comment by scottyscripts** [comment]
what does it look like is happening on your rails server after the request? Is the item in your database if you go in and check? (check in rails db or rails console)

**Comment by ryanwk** [comment]
yep, it's in there. So this is probably a problem with the front end displaying the data?

**Comment by ryanwk** [comment]
this is the error I've been getting consistently: 
server:
```
Started PATCH "/routines/" for 127.0.0.1 at 2017-08-29 09:55:44 -0400
  
ActionController::RoutingError (No route matches [PATCH] "/routines"):
  
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
curl request from terminal
```
~/wdi/projects/strongerBackEnd (routine)
$ TOKEN=BAhJIiVlZDBkYmZhYmVhOTFkMWJjOTEwMzEwOWE2Mjg4MTM2ZgY6BkVG--f81f1ca5ebf76f15c1ccf2164e3ce56c3fd2d307 sh scripts/update-routine.sh 
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
X-Request-Id: f00245ef-bd56-474d-87d8-c8f9d78a73bc
X-Runtime: 0.025921
Vary: Origin
Content-Length: 3771

{"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [PATCH] \"/routines\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'"},{"id":1,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":2,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":3,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":4,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"}
```

**Comment by ryanwk** [comment]
stumped

**Comment by ryanwk** [comment]
We know that the POST request works, but it doesn't reflect this on the front-end. After reading through the ember documentation I found this snippet "The API uses a nested route for creating new list items. This doesn't fit directly with ember-data's modeling of APIs, so we have to do some extra work. We'll extend the default application adapter, included in ember-template to handle this case." So I went ahead and mimicked the adapter from ember-resources. Don't know if that's even something I should worry about but I'm all out of ideas. So I tried this:
```js
import ApplicationAdapter from './application';

export default ApplicationAdapter.extend({
  createRecord(store, type, record) {

    const api = this.get('host')
    const serialized = this.serialize(record, {includeID: true})
    const exerciseId = serialized.exerciseId
    const url = `${api}/exercises/${exerciseId}`
    const data = {item: serialized}
    return this.ajax(url, 'POST', {data})
  }
});

```
but I get this error:

```
POST http://localhost:4741/exercises/undefined 404 (Not Found)
12:50:19.992 ember.debug.js:16905 Ember Data Request POST http://localhost:4741/exercises/undefined returned a 404
Payload (Empty Content-Type)
[object Object]
Error
```


Please let me know if I am off base here. I don't know what this adapter does or what it is used for. I'm just taking shots in the dark at this point.

**Comment by ryanwk** [comment]
I'm thrashing here please help

**Comment by ryanwk** [comment]
I have read through these docs 100 times: 
https://git.generalassemb.ly/ga-wdi-boston/ember-resources
https://guides.emberjs.com/v2.4.0/models/creating-updating-and-deleting-records/
https://git.generalassemb.ly/ga-wdi-boston/ember

**Comment by ryanwk** [comment]
I need to rework my ERD and change the relationships between my entities
