### ISSUE TITLE
deploy command not found

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/capstone-project#830]
Hey guys,
I am currently trying to deploy my front end in order to make sure that all my eggs are in the basket so to speak, but when I try to run a grunt deploy I am getting the following terminal error:
```
grunt deploy
Warning: Task "deploy" not found. Use --force to continue.

**Comment by Azinck94** [comment]
Am guessing that there is a different deployment technique for good old ember? Am reading their tutorial on it and it appears that the process is different and perhaps does not use grunt....BUT I don't want to do anything until I get confirmation on what you guys are expecting us to use.

**Comment by Azinck94** [comment]
this seems to be the terminal command they want me to use:
```
ember build
scp -r dist/* myserver.com:/var/www/public/

**Comment by Azinck94** [comment]
your thoughts?

**Comment by MicFin** [comment]
Yes `grunt deploy` is only for `browser-template` not ember.  Have you done `npm install` and `bower install`?  What did running `ember build` do?
https://git.generalassemb.ly/ga-wdi-boston/ember-deployment-guide

**Comment by Azinck94** [comment]
I have done both, yes!

**Comment by payne-chris-r** [comment]
https://git.generalassemb.ly/ga-wdi-boston/ember-deployment-guide

**Comment by Azinck94** [comment]
So I made it to step 6.... and then received the following error when trying to ember build environment production:
```
The Broccoli Plugin: [Fingerprint] failed with:
SyntaxError: Unexpected token: name (Action)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:86:23)
    at new BroccoliBuildError (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-builder/lib/broccoli-build-error.js:18:29)
    at /Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:508:7)
    at publishRejection (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:443:3)
    at flush (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at: 
    at Fingerprint.Plugin (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
    at Fingerprint (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
    at new AssetRev (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
    at AssetRev (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)

**Comment by payne-chris-r** [comment]
What'd you put here? 
```js
import ActiveModelAdapter from 'active-model-adapter';
import ENV from '<% ember-deployment-example name %>/config/environment';

export default ActiveModelAdapter.extend({
  host: ENV.apiHost,
  ...
  ...
  ...
});
```

**Comment by Azinck94** [comment]
in adaptors/application.js:
```
import ENV from '/The-Vector-Front-End/config/environment';
import ActiveModelAdapter from 'active-model-adapter';

import Ember from 'ember';

export default ActiveModelAdapter.extend({
  host: ENV.apiHost,

  auth: Ember.inject.service(),

  headers: Ember.computed('auth.credentials.token', {
    get () {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers.Authorization = `Token token=${token}`;
      }

      return headers;
    },

**Comment by Azinck94** [comment]
Im going to try deleting the '/ 'in front my route name

**Comment by Azinck94** [comment]
same thing: 
```
$ ember build --environment=production
DEPRECATION: Addon files were detected in `/Users/firstuser/Desktop/Capstone Project-Front/node_modules/liquid-fire/addon`, but no JavaScript preprocessors were found for `liquid-fire`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `liquid-fire`'s `package.json`.
cleaning up...
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
SyntaxError: Unexpected token: name (Action)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at new BroccoliBuildError (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-builder/lib/broccoli-build-error.js:18:29)
    at /Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:508:7)
    at publishRejection (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:443:3)
    at flush (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at: 
    at Fingerprint.Plugin (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
    at Fingerprint (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
    at new AssetRev (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
    at AssetRev (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/firstuser/Desktop/Capstone Project-Front/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)

**Comment by Azinck94** [comment]
gonna keep googling for a bit, will update if I stumble upon anything

**Comment by Azinck94** [comment]
My config/environment.js looks like this:
```
/* jshint node: true */

module.exports = function (environment) {
  'use strict';
  const ENV = {
    modulePrefix: 'The-Vector-Front-End',
    environment: environment,
    rootURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false,
      },
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
    let port = +('GA'.split('').reduce((p, c) =>
      p + c.charCodeAt().toString(16), '')
    );
    ENV.apiHost = `http://localhost:${port}`;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.rootUrl = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {
    ENV.rootURL = '/The-Vector-Front-End';
    ENV.locationType = 'hash';
    ENV.apiHost = 'https://git.heroku.com/afternoon-beyond-92082.git';
  }

  return ENV;
};

**Comment by Azinck94** [comment]
services/ajax.js:
```
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';

import ENV from '/The-Vector-Front-End/config/environment';

export default AjaxService.extend({
  host: ENV.apiHost,

  auth: Ember.inject.service(),
  headers: Ember.computed('auth.credentials.token', {
    get () {
      let headers = {};
      const token = this.get('auth.credentials.token');
      if (token) {
        headers.Authorization = `Token token=${token}`;
      }

      return headers;
    },
  }),
});

**Comment by Azinck94** [comment]
Went through entire project and changed all instances of "ga-wdi-boston.ember-auth" to "The-Vector-Front-End" and am now running "ember build --environment=production" which results in:
```
$ ember build --environment=production
⠼ Building[WARN] (broccoli-uglify-sourcemap) Minifying: `assets/vendor.js` took: 25250ms (more than 20,000ms)
cleaning up...
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/The-Vector-Front-End-dd5ccb11f9ffb1f350797f856d770672.css: 130.63 KB (21.86 KB gzipped)
 - dist/assets/The-Vector-Front-End-ee7b804b4f463d623631f180fbeb1ddd.js: 53.9 KB (7.11 KB gzipped)
 - dist/assets/vendor-2d7c197b10aeff726e808cdb9e40e99f.js: 934.72 KB (241.35 KB gzipped)
 - dist/assets/vendor-7fdaa44820dedb9b006e3528e94e81c7.css: 138 B (114 B gzipped)

**Comment by Azinck94** [comment]
Will follow the rest of the steps and make sure that everything is in order, then close this issue if that is the case!

**Comment by payne-chris-r** [comment]
There we go 😜

**Comment by Azinck94** [comment]
So it is deployed but now upon trying to sign up or sign in I am receiving the following error:
```
XMLHttpRequest cannot load https://git.heroku.com/afternoon-beyond-92082.git/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://azinck94.github.io' is therefore not allowed access. The response had HTTP status code 401.

**Comment by Azinck94** [comment]
Tried to find any instances of that "access-control-header In either my back or front end to no avail

**Comment by Azinck94** [comment]
hold the phone, think I forgot to heroku login when I ran heroku create, back to square 1 to fix this all for a minute, will update if that doesnt work

**Comment by Azinck94** [comment]
still getting this error:
```
Uncaught Error: Could not find module `/The-Vector-Front-End/config/environment` imported from `The-Vector-Front-End/services/ajax`

**Comment by Azinck94** [comment]
As well as:
```
Uncaught Error: Failed to create an instance of 'service:ajax'. Most likely an improperly defined class or an invalid module export.

**Comment by Azinck94** [comment]
im going to start from Ember build, which when I ran resulted in:
```
ember build
⠴ Building'instrument' is imported from external module 'ember-data/-debug' but never used
cleaning up...
Built project successfully. Stored in "dist/".

**Comment by Azinck94** [comment]
I have my config/environment.js looking like this:
```
/* jshint node: true */

module.exports = function (environment) {
  'use strict';
  const ENV = {
    modulePrefix: 'The-Vector-Front-End',
    environment: environment,
    rootURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false,
      },
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
    let port = +('GA'.split('').reduce((p, c) =>
      p + c.charCodeAt().toString(16), '')
    );
    ENV.apiHost = `http://localhost:${port}`;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.rootUrl = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {
    ENV.rootURL = '/The-Vector-Front-End';
    ENV.locationType = 'hash';
    ENV.apiHost = ' https://afternoon-beyond-92082.herokuapp.com';
  }

  return ENV;
};

**Comment by Azinck94** [comment]
services/ajax.js:
```
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';

import ENV from 'The-Vector-Front-End/config/environment';

**Comment by Azinck94** [comment]
adaptors/application.js:
```
import ENV from 'The-Vector-Front-End/config/environment';
import ActiveModelAdapter from 'active-model-adapter';

**Comment by Azinck94** [comment]
i deleted gh-pages and am up date date, just checked out to new gh-pages

**Comment by Azinck94** [comment]
removed /dist from gitignore

**Comment by Azinck94** [comment]
running 'ember build --environment=production' results in:
```
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/The-Vector-Front-End-386510ad0059753823f6fff37b8a9303.js: 53.9 KB (7.1 KB gzipped)
 - dist/assets/The-Vector-Front-End-dd5ccb11f9ffb1f350797f856d770672.css: 130.63 KB (21.86 KB gzipped)
 - dist/assets/vendor-2d7c197b10aeff726e808cdb9e40e99f.js: 934.72 KB (241.35 KB gzipped)
 - dist/assets/vendor-7fdaa44820dedb9b006e3528e94e81c7.css: 138 B (114 B gzipped)

**Comment by Azinck94** [comment]
Successful push, will check in a few minutes to see if anything changes.

**Comment by Azinck94** [comment]
aaaand I get this:
```
XMLHttpRequest cannot load https://afternoon-beyond-92082.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://azinck94.github.io' is therefore not allowed access.

**Comment by Azinck94** [comment]
I'd like to request a sit down with someone to go over this please: I am now running in circles a little bit and am worried about meddling with my code and deploying it over and over because each time requires numerous commits

**Comment by payne-chris-r** [comment]
Can you show me a screen shot of your full page? Also where are you?

**Comment by Azinck94** [comment]
just slacked you a screenshot

**Comment by Azinck94** [comment]
looks pretty similar to what I have been dealing with: https://github.com/ga-wdi-boston/capstone-project/issues/782

**Comment by Azinck94** [comment]
going to run through this entire process for the fifth time: will log exact steps ........

blowup gh-pages local branch with: git branch -D gh-pages
blowup gh-pages remote branch with: git push origin --delete gh-pages
checked for ember-auth with global search
npm and bower installed
added and committed package files

Ensured i was using var
Ensured I have apiHost line
Checked environment===production block equals:

    ENV.locationType = 'hash';
    ENV.apiHost = 'https://afternoon-beyond-92082.herokuapp.com/'
Ensured this line in application.js:
import ENV from 'The-Vector-Front-End/config/environment';
Added and committed files
checked out to new gh-pages branch
remove dist from gitignore
No dist file -> run ember serve to create one
git add /dist and commit
run ember build --environment=production
git add -A && git commit -m ‘Ember built
git subtree push --prefix dist origin gh-pages’

And now I get a404

There isn't a GitHub Pages site here.

**Comment by Azinck94** [comment]
So me and scott eventually found what seems to be a solid fix, we checked out the specific config/environment.js file from ember-auth template and carefully retraced steps from there(we also renamed 'The-Vector-Front-End' to 'vector-front' in case capital letters was an issue). This seemed to do the trick!
