### ISSUE TITLE
C on lifts

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/capstone-project#838]
attempting C of CRUD on lift entity after setting up backend according to new ERD

I've signed in, w/ a token, and currently attempting to Create a lift.

Here's my error:
```
$ TOKEN=BAhJIiVmMDMwOWJmYTljYzIwMDcxYmQ3M2UwYWQ3ZjZmY2RkMQY6BkVG--1cb0c84752367fd249a3821eb19186b24d7fcf16 sh scripts/create-lift.sh 
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Request-Id: b59c9669-441f-4dab-ac3b-41f5955210ac
X-Runtime: 0.123103
Vary: Origin
Content-Length: 16632

{"status":500,"error":"Internal Server Error","exception":"#\u003cNameError: uninitialized constant Lift::Routines\u003e","traces":{"Application Trace":[{"id":24,"trace":"app/controllers/lifts_controller.rb:18:in `create'"}],"Framework Trace":[{"id":0,"trace":"activerecord (5.0.1) lib/active_record/inheritance.rb:152:in `compute_type'"},{"id":1,"trace":"activerecord (5.0.1) lib/active_record/reflection.rb:354:in `compute_class'"},{"id":2,"trace":"activerecord (5.0.1) lib/active_record/reflection.rb:350:in

Started POST "/lifts" for 127.0.0.1 at 2017-08-29 17:23:34 -0400
Processing by LiftsController#create as */*
  Parameters: {"lift"=>{"routine_id"=>"2", "exercise_id"=>"254", "weight"=>"69"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "f0309bfa9cc20071bd73e0ad7f6fcdd1"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 36ms (ActiveRecord: 0.3ms)


  
NameError (uninitialized constant Lift::Routines):
  
app/controllers/lifts_controller.rb:18:in `create'
```
curl script:
```rb
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/lifts"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "lift": {
      "routine_id": "2",
      "exercise_id": "254",
      "weight": "69"
   }
  }'

echo
```

```rb
class LiftsController < ProtectedController
  before_action :set_lift, only: [:show, :update, :destroy]

  # GET /lifts
  def index
    @lifts = Lift.all

    render json: @lifts
  end

  # GET /lifts/1
  def show
    render json: @lift
  end

  # POST /lifts
  def create
    binding.pry
    @lift = current_user.lifts.build(lift_params)

    if @lift.save
      render json: @lift, status: :created, location: @lift
    else
      render json: @lift.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lifts/1
  def update
    if @lift.current_user.routines.lifts.find(:id).update(lift_params)
      render json: @lift
    else
      render json: @lift.errors, status: :unprocessable_entity
    end
  end

  # DELETE /lifts/1
  def destroy
    @lift.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lift
      @lift = Lift.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lift_params
      params.require(:lift).permit(:routine_id, :exercise_id, :weight)
    end
end
```
model
```rb
class Lift < ApplicationRecord
  has_many :users, through: :routines
  belongs_to :routines
  belongs_to :exercise
end
```
serializer:
```rb
class LiftSerializer < ActiveModel::Serializer
  attributes :id, :weight
  has_one :routine
  has_one :exercise
end

```

serializer has been updated and models all reflect what I think are the appropriate relationships.
The error is coming from the create method. 

```rb
    @lift = current_user.lifts.build(lift_params)
```
to me that makes sense. A current user can create a lift according to the lift_params of :routine_id, :exercise_id, :weight.

**Comment by ryanwk** [comment]
serializer
```rb
class LiftSerializer < ActiveModel::Serializer
  attributes :id, :weight
  has_one :routine
  has_one :exercise
end

class RoutineSerializer < ActiveModel::Serializer
  attributes :id, :name, :user
end

# frozen_string_literal: true
class UserSerializer < ActiveModel::Serializer
  attributes :id, :email
end

class ExerciseSerializer < ActiveModel::Serializer
  attributes :id, :name, :updated_at

  def updated_at
    object.updated_at.to_date
  end
end

```

I can't move on to the other crud actions without tackling this one first. The error seems to be comming from the create method. So I tried this: ```  def create
    binding.pry
    @lift = current_user.routines.lifts.build(lift_params)``` no luck. I've tried all sorts of combinations for this method. The relationships surrounding the lifts table are strange. It's very confusing trying to find a method that will achieve the outcome I am looking for. 
this issue is kind of relative to my issue:
https://stackoverflow.com/questions/9346261/using-has-many-through-and-build

I tried manually creating a lift in pry, couldn't seem to get it to save. 
```js
[7] pry(#<LiftsController>)> newLift = Lift.new( routine_id: "2", exercise_id: "254", weight: "60")
=> #<Lift:0x007f7f7fbaa9b8
 id: nil,
 routine_id: 2,
 exercise_id: 254,
 weight: 60,
 created_at: nil,
 updated_at: nil>
[8] pry(#<LiftsController>)> newLift.save
   (0.2ms)  BEGIN
  Exercise Load (0.4ms)  SELECT  "exercises".* FROM "exercises" WHERE "exercises"."id" = $1 LIMIT $2  [["id", 254], ["LIMIT", 1]]
   (0.2ms)  ROLLBACK
=> false
[9] pry(#<LiftsController>)> Lift.last
  Lift Load (0.5ms)  SELECT  "lifts".* FROM "lifts" ORDER BY "lifts"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> nil
[10] pry(#<LiftsController>)> Lift.all
  Lift Load (0.3ms)  SELECT "lifts".* FROM "lifts"
=> []
[11] pry(#<LiftsController>)> 

```

**Comment by scottyscripts** [comment]
currently you are trying to say current_user.lifts.build, which you could only do if a User has_many lifts. Is this how your model is set up? Can you post the code from that lift model?

**Comment by ryanwk** [comment]
This is how my relationships are set up. I'm not sure if they are correct but that's how I think they should work according to my new ERD (img attached below), please correct me if I am wrong. 
```rb
class Exercise < ApplicationRecord
  belongs_to :user
  has_many :lifts
end

class Lift < ApplicationRecord
  has_many :users, through: :routines
  belongs_to :routines
  belongs_to :exercise
end

class Routine < ApplicationRecord
  belongs_to :user
  has_many :lifts
end

# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :lifts, through: :routines
  has_many :routines
  has_many :exercises
end
```

![image](https://user-images.githubusercontent.com/19196821/29875423-ffd92d5c-8d67-11e7-95ad-5b5734d5c10e.png)

**Comment by scottyscripts** [comment]
so a belongs_to relationship, the thing it belongs_to needs to be singular. so `belongs_to :user`. In a `has_many` relationship it should be plural, so `has_many :users`. Make these changes to your model, try again, and update me on what happens. Use rails docs as well, there are a ton of great examples of how it should look here ---> http://guides.rubyonrails.org/association_basics.html#the-belongs-to-association

**Comment by ryanwk** [comment]
ok, that makes sense, I've updated my relationships to reflect those changes. 

same error: 
```
[1] pry(#<LiftsController>)> exit
  Lift Load (0.5ms)  SELECT "lifts".* FROM "lifts" INNER JOIN "routines" ON "lifts"."routine_id" = "routines"."id" WHERE "routines"."user_id" = $1  [["user_id", 23]]
Completed 500 Internal Server Error in 4387ms (ActiveRecord: 39.9ms)


  
NoMethodError (undefined method `routines' for #<ActiveRecord::Associations::CollectionProxy []>):
  
app/controllers/lifts_controller.rb:19:in `create'
```

**Comment by scottyscripts** [comment]
So this is a different error than we had before. In binding.pry can you confirm that current user is defined? Also in binding.pry, try to create a lift and save it `@lift = current_user.lifts.build(lift_params)` then `@lift.save`. If it fails you can say `@lift.errors` and get a more detailed error message about what went wrong. This is what we did the other day for your other resource. Can you paste that error in here.

**Comment by ryanwk** [comment]
```
[1] pry(#<LiftsController>)> current_user
=> #<User:0x007f7f7ee9b5b0
 id: 23,
 email: "r@r.com",
 token: "e6957ca0523971a98bf2252ff55623f3",
 password_digest:
  "$2a$10$cyTHRpNO6/.Xy7WTXrlOu.K3wDKfU46WPDxb7UduY5Gmku/jMbfLa",
 created_at: Sun, 27 Aug 2017 18:46:52 UTC +00:00,
 updated_at: Wed, 30 Aug 2017 13:48:54 UTC +00:00>
[2] pry(#<LiftsController>)> 
[3] pry(#<LiftsController>)> @lift = current_user.lifts.build(lift_params) 
=> #<Lift:0x007f7f7fa332b0
 id: nil,
 routine_id: 2,
 exercise_id: 254,
 weight: 69,
 created_at: nil,
 updated_at: nil>
[4] pry(#<LiftsController>)> @lift.save
   (0.2ms)  BEGIN
  Routine Load (0.5ms)  SELECT  "routines".* FROM "routines" WHERE "routines"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Exercise Load (0.3ms)  SELECT  "exercises".* FROM "exercises" WHERE "exercises"."id" = $1 LIMIT $2  [["id", 254], ["LIMIT", 1]]
  SQL (23.3ms)  INSERT INTO "lifts" ("routine_id", "exercise_id", "weight", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["routine_id", 2], ["exercise_id", 254], ["weight", 69], ["created_at", 2017-08-30 14:17:56 UTC], ["updated_at", 2017-08-30 14:17:56 UTC]]
   (0.4ms)  COMMIT
=> true
[5] pry(#<LiftsController>)> @lift.errors
=> #<ActiveModel::Errors:0x007f7f7f911378
 @base=
  #<Lift:0x007f7f7fa332b0
   id: 1,
   routine_id: 2,
   exercise_id: 254,
   weight: 69,
   created_at: Wed, 30 Aug 2017 14:17:56 UTC +00:00,
   updated_at: Wed, 30 Aug 2017 14:17:56 UTC +00:00>,
 @details={},
 @messages={}>
[6] pry(#<LiftsController>)> 


```

**Comment by ryanwk** [comment]
```

=> [#<Routine:0x007f7f7bc84bd0
  id: 2,
  name: "upperbody",
  created_at: Mon, 28 Aug 2017 18:52:34 UTC +00:00,
  updated_at: Mon, 28 Aug 2017 18:52:34 UTC +00:00,
  user_id: 23>,

 #<Exercise:0x007f7f7ce45428
  id: 254,
  name: "pickle rick",
  created_at: Tue, 29 Aug 2017 17:24:36 UTC +00:00,
  updated_at: Tue, 29 Aug 2017 17:24:36 UTC +00:00,
  user_id: nil>,

```
user_id on exercise 254 is nil, is this the problem?

**Comment by ryanwk** [comment]
model:
```rb
class Exercise < ApplicationRecord
  belongs_to :user
  has_many :lifts
end

```
schema:
```
class ExerciseSerializer < ActiveModel::Serializer
  attributes :id, :name, :updated_at, :user_id

  def updated_at
    object.updated_at.to_date
  end
end

```
for attributes I tried ```:user, :user_id```

curl script:
```rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/exercises"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "exercise": {
      "name": "createdViaCurl"
    }
  }'
```
for the curl script I tried a variety of ids for data ```"user_id": "23", id: 23, etc```

no luck

**Comment by scottyscripts** [comment]
It's super important to critically read what is happening at each step! In binding.pry you successfully created the record when you did `@lift.save`. There were no errors here. Your issue isn't with saving the record. Don't make assumptions your issue is coming from this line. Creating and saving the record is successfully working, your error is happening afterwords

**Comment by ryanwk** [comment]
The error is coming from my create method in my lifts_controller. I tried this:
```rb
  # POST /lifts
  def create
    @lift = current_user.lifts.routines.build(lift_params)

    if @lift.save
      render json: @lift, status: :created
    else
      render json: @lift.errors, status: :unprocessable_entity
    end
  end
```

I tried 
```
  def create
    @lift = current_user.lifts.**routine**.build(lift_params)

    if @lift.save
      render json: @lift, status: :created
    else
```
tried:
  def create
    @lift = current_user.lifts.**routine**.build(lift_params)

    if @lift.save
      render json: @lift
    else
```
and other variations. No luck.

**Comment by ryanwk** [comment]
YEAAAAHH GOT IT.
```rb
  def create
    @lift = current_user.lifts.build(lift_params)

    if @lift.save
      render json: @lift, status: :created
    else
```

**Comment by ryanwk** [comment]
thanks guys!
