### ISSUE TITLE
Create new Player in Rails, not working

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/capstone-project#99]
I have 2 join tables (joins Player and Character, one join table is play_as_character, other is play_against_character) which allows me to access player.characters and player.opponents

[More context in previous issue](https://github.com/ga-wdi-boston/capstone-project/issues/90)

Player has name and rank.  I want to be able to create player by entering name, rank, characters, and opponents, but I think it's not working since I don't actually have columns named characters or opponents since it's covered by join tables.

```
curl --include --request POST http://localhost:3000/players \
  --header "Authorization: Token token=BAhJIiU5MjVjZTIyOWQ2ZWI5NGI2ZGM0YjEwYjg1ZTM4NzVjZQY6BkVG--276029c8095ad2312d24cb601a0cf0be55ac11d5" \
  --header "Content-Type: application/json" \
  --data '{
    "player": {
      "name": "seatuna",
      "rank": "bronze",
      "characters": 3, // I've also tried directly entering characters' names, didn't work
      "opponents": 1
    }
  }'
```

Error

```
Started POST "/players" for ::1 at 2016-04-04 16:59:27 -0400
Processing by PlayersController#create as */*
  Parameters: {"player"=>{"name"=>"seatuna", "rank"=>"bronze", "characters"=>3, "opponents"=>1}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "925ce229d6eb94b6dc4b10b85e3875ce"]]
Completed 500 Internal Server Error in 59ms (ActiveRecord: 2.9ms)

NoMethodError (undefined method `each' for 3:Fixnum):
  app/controllers/players_controller.rb:22:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.9ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (297.3ms)
```

Player schema

``` ruby
  create_table "players", force: :cascade do |t|
    t.string   "name"
    t.string   "rank"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
  end
```

Player model

``` ruby
class Player < ActiveRecord::Base
  belongs_to :user, inverse_of: :users
  has_many :characters, through: :play_as_characters
  has_many :play_as_characters
  has_many :opponents, through: :play_against_characters, source: :character
  has_many :play_against_characters

  validates_presence_of :characters
  validates_presence_of :opponents
end
```

I've tried shoveling in some characters and opponents but it doesn't work :( 

PlayersController

``` ruby
class PlayersController < OpenReadController
  before_action :set_player, only: [:show, :update, :destroy]

  def create

    if current_user
      @player = Player.new(player_params)
      @characters = Character.find(params[:characters]) # i've also tried params[:id]
      @opponents = Character.find(params[:opponents])
      @player.characters << @characters
      @player.opponents << @opponents


      if @player.save
        # @player.characters << @character
        # @player.opponents << @character
        render json: @player, status: :created, location: @player
      else
        render json: @player.errors, status: :unprocessable_entity
      end

    else
      head :bad_request
    end
  end

private

    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :rank, :characters, :opponents)
    end
end
```

**Comment by faetea** [comment]
The curl request only works for the structure of your database.  Have you tried doing three separate curl requests?

curl to players with:

```
  --data '{
    "player": {
      "name": "seatuna",
      "rank": "bronze",
      "user_id": "1"
    }
  }'
```

, and curl to characters with:

```
  --data '{
    "character": {
      "name": "SUPA-FISH",
    }
  }'
```

, and then curl to play_as_characters with:

```
  --data '{
    "play_as_character": {
      "player_id": 1,
      "character_id": 1
    }
  }'
```

Jeff or Matt might respond with a better answer, but I think thats how curl requests work with a join table like you are describing.

**Comment by GA-MEB** [comment]
@seatuna 
`:characters` and `:opponents` are keys within `:player` - they aren't in the root of the params hash, so you can't access them by writing `params[:characters]`. 
However, you could write `params[:player][:characters]`.

**Comment by GA-MEB** [comment]
You should also take those `:characters` and `:opponents` out of the strong params method's `permit`, since they aren't properties in the table - they're methods, made available by using `has_many`

**Comment by seatuna** [comment]
I'll try all these.  I'll let you know how it goes!

**Comment by jrhorn424** [comment]
You're basically trying to do operations for `play_as_character` and `play_against_character` inside the `PlayersController`. It could be argued that these join tables need their own controllers, then you could do basic CRUD against the rows in that table (two IDs). I think that's what @faetea might have been suggesting in her recent comment.

As a first step, I'd go with something a bit different.

``` diff
-     @characters = Character.find(params[:characters]) # i've also tried params[:id]
+     selected_character = Character.find(params[:selected_character]) # the plurals are bad since you're send a singular reference
-      @opponents = Character.find(params[:opponents])
+      selected_opponents = Character.find(params[:selected_opponent])

-      @player.characters << @characters
+      @player.characters.build(selected_character)
-      @player.opponents << @opponents
+      @player.opponents.build(selected_opponent)
```

``` diff
curl --include --request POST http://localhost:3000/players \
  --header "Authorization: Token token=BAhJIiU5MjVjZTIyOWQ2ZWI5NGI2ZGM0YjEwYjg1ZTM4NzVjZQY6BkVG--276029c8095ad2312d24cb601a0cf0be55ac11d5" \
  --header "Content-Type: application/json" \
  --data '{
    "player": {
      "name": "seatuna",
-      "rank": "bronze",
+      "rank": "bronze"
-      "characters": 3, // I've also tried directly entering characters' names, didn't work
-      "opponents": 1
-    }
+    },
+  "selected_character": 3,
+  "selected_opponent": 1
  }'
```

Notice the nesting of the JSON and how it corresponds to params access in the controller.

**Comment by seatuna** [comment]
Now I'm getting this error:

```
Started POST "/players" for ::1 at 2016-04-05 10:17:48 -0400
Processing by PlayersController#create as */*
  Parameters: {"player"=>{"name"=>"seatuna", "rank"=>"bronze"}, "selected_character"=>3, "selected_opponent"=>1}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "78f2e0b39027e69c0f3d221e078ae845"]]
  Character Load (0.2ms)  SELECT  "characters".* FROM "characters" WHERE "characters"."id" = $1 LIMIT 1  [["id", 3]]
  Character Load (0.2ms)  SELECT  "characters".* FROM "characters" WHERE "characters"."id" = $1 LIMIT 1  [["id", 1]]
Completed 500 Internal Server Error in 35ms (ActiveRecord: 5.1ms)

**ArgumentError (When assigning attributes, you must pass a hash as an argument.):
  app/controllers/players_controller.rb:25:in `create'**
```

Player controller create now looks like this:

``` ruby
def create

    if current_user
      @player = Player.new(player_params)
      selected_character = Character.find(params[:selected_character])
      selected_opponent = Character.find(params[:selected_opponent])
      @player.characters.build(selected_character)
      @player.opponents.build(selected_opponent)

      if @player.save
        render json: @player, status: :created, location: @player
      else
        render json: @player.errors, status: :unprocessable_entity
      end

    else
      head :bad_request
    end
  end
```

curl request

```
curl --include --request POST http://localhost:3000/players \
  --header "Authorization: Token token=BAhJIiU3OGYyZTBiMzkwMjdlNjljMGYzZDIyMWUwNzhhZTg0NQY6BkVG--3d4993bba6241c57d0e314baa66186a90f62d161" \
  --header "Content-Type: application/json" \
  --data '{
    "player": {
      "name": "seatuna",
      "rank": "bronze"
    },
    "selected_character": 3,
    "selected_opponent": 1
  }'
```

ughhhhh so clooooose!!!

Also, will this work if I try to enter multiple characters / opponents?

**Comment by jrhorn424** [comment]
> Also, will this work if I try to enter multiple characters / opponents?

No, but if it's a join you can do multiples by sending multiple requests.

**Comment by jrhorn424** [comment]
http://stackoverflow.com/questions/25115017/error-when-assigning-attributes-you-must-pass-a-hash-as-an-argument

**Comment by jrhorn424** [comment]
```diff
-       selected_character = Character.find(params[:selected_character])
+      selected_character = Character.find(id: params[:selected_character])

**Comment by jrhorn424** [comment]
What is `selected_character` before you do the `.build`s?

**Comment by seatuna** [comment]
it needs to be a character that exists in the characters table

**Comment by seatuna** [comment]
Now it's 404

```
Started POST "/players" for ::1 at 2016-04-05 10:48:05 -0400
Processing by PlayersController#create as */*
  Parameters: {"player"=>{"name"=>"seatuna", "rank"=>"bronze"}, "selected_character"=>3, "selected_opponent"=>1}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "78f2e0b39027e69c0f3d221e078ae845"]]
  Character Load (0.1ms)  SELECT  "characters".* FROM "characters" WHERE "characters"."id" = $1 LIMIT 1  [["id", nil]]
Completed 404 Not Found in 30ms (Views: 1.6ms | ActiveRecord: 4.3ms)
```

**Comment by seatuna** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

I had to shovel those characters instead of buildingggggggggggggggggggg

``` Ruby
def create

    if current_user
      @player = Player.new(player_params)
      selected_character = Character.find(params[:selected_character])
      selected_opponent = Character.find(params[:selected_opponent])
      @player.characters << selected_character
      @player.opponents << selected_opponent

      if @player.save
        render json: @player, status: :created, location: @player
      else
        render json: @player.errors, status: :unprocessable_entity
      end

    else
      head :bad_request
    end
  end
```

Thanks! I can finally move on with my life :sob:

**Comment by jrhorn424** [comment]
Let me have a look when you get a moment.

**Comment by jrhorn424** [comment]
@seatuna I'm sorry, I thought building was the correct idiom here. So sorry for leading you astray!

**Comment by seatuna** [comment]
That's ok, I figured it outtttttttttt _victory dance_

**Comment by seatuna** [comment]
Is this code terrible if I want to create multiple entries into the join table at once?

Another problem I encountered is that in order for this create to work, the user must enter 3 characters / opponents, any less will throw a 404 error.

``` ruby
def create

    if current_user
      @player = Player.new(player_params)
      selected_character1 = Character.find(params[:selected_character1])
      selected_opponent1 = Character.find(params[:selected_opponent1])
      selected_character2 = Character.find(params[:selected_character2])
      selected_opponent2 = Character.find(params[:selected_opponent2])
      selected_character3 = Character.find(params[:selected_character3])
      selected_opponent3 = Character.find(params[:selected_opponent3])

      @player.characters << selected_character1 << selected_character2 << selected_character3
      @player.opponents << selected_opponent1 << selected_opponent2 << selected_opponent3

      if @player.save
        render json: @player, status: :created, location: @player
      else
        render json: @player.errors, status: :unprocessable_entity
      end

    else
      head :bad_request
    end
  end
```

**Comment by jrhorn424** [comment]
Why not just use your previous code and issue three different ajax requests (or as many as you need to add everything you want)?

**Comment by seatuna** [comment]
I'm planning to make my form like this:

name:
rank:
char1:
char2:
char3:
opp1:
opp2:
opp3:
submit button

If I choose to use separate different ajax requests instead, wouldn't I need to create controllers for my join tables (play_as_character and play_against_character)?
Then I could do the follow:
1) create player with first character and first opponent
2) create join table records (play_as_character and play_against_character)
3) step 2 until all are entered

**Comment by faetea** [comment]
Why do you want to have so many characters and opponents in the form?  Why aren't the Create Player and the Add Character and the Add Opponent actions separate?

**Comment by jrhorn424** [comment]
You can dynamically add new inputs to forms and then iterate through them before submitting.
- http://jsfiddle.net/aaki/hMJEy/1/
- http://stackoverflow.com/questions/7362775/how-to-submit-a-dynamically-generated-form-to-ajax

**Comment by jrhorn424** [comment]
> If I choose to use separate different ajax requests instead, wouldn't I need to create controllers for my join tables (play_as_character and play_against_character)?
> Then I could do the follow:
> 1) create player with first character and first opponent
> 2) create join table records (play_as_character and play_against_character)
> 3) step 2 until all are entered

This is **fantastic** idea.

**Comment by seatuna** [comment]
okie dokie x_X
